WITH
bronze_layer AS (
    SELECT
        extract_date,
        project_id,
        project_name,
        program_name,
        application_no,
        cpr,
        indvidual_name,
        gender,
        date_of_birth,
        individual_segment,
        highest_education_qualification,
        specialization,
        gradudation_date,
        whitelisting,
        approved as is_approved,
        decision_date_approved_on_or_rejected_on as decision_date,
        type_of_opportunity,
        mobile,
        office,
        email,
        first_joining_date,
        joining_date_current,
        cr_license_no_current,
        commercial_name_current,
        job_title_current,
        salary_current,
        total_months_of_work_experience,
        joining_date_new_placement,
        cr_license_no_new_placement,
        commercial_name_new_placement,
        job_title_new_placement,
        placement_location,
        placement_region,
        placement_country,
        wage_support_type,
        total_monthly_offer_bhd,
        months_of_support,
        subsidy,
        total_monthly_subsidy_bhd_tamkeen as total_monthly_subsidy_tamkeen,
        total_salary_support_bhd_tamkeen as total_salary_support_tamkeen,
        travelcap_amount as travel_cap,
        travelactual_amount as travel_actual,
        travel_tamkeen_support as travel_support,
        visacap_amount as visa_cap,
        visaactual_amount as visa_actual,
        visa_tamkeen_support as visa_support,
        accommodationcap_amount as accommodation_cap,
        accommodationactual_amount as accommodation_actual,
        accommodationtamkeen_support as accommodation_support,
        transportcap_amount as transport_cap,
        transportactual_amount as transport_actual,
        transport_tamkeen_support as transport_support,
        per_diemcap_amount as per_diem_cap,
        per_diemactual_amount as per_diem_actual,
        per_diemtamkeen_support as per_diem_support,
        program_costcap as program_cost_cap,
        program_costactual_amount as program_cost_actual,
        program_cost_tamkeen_supprot AS program_cost_tamkeen_support,
        total_support_bhd_tamkeen as total_support_tamkeen,
        start_date_wage_support,
        end_date_wage_support,
        joining_date_new_employment,
        cr_license_no_new_employment,
        commercial_name_new_employment,
        job_title_new_employment,
        total_offer_bhd_new_employment,
        total_months_of_experience_new_employment,
        created_on,
        created_by,
        application_format,
        approved_by,
        CAST('OFFLINE_SHEETS' AS STRING) AS source_system_name
    FROM `tmkn-dwh-iceberg-dev-fc`.`tmkn-aws-dwh-dev-iceberg-bronze`.offline_sheets_grtandgre_individuals
),

silver_layer AS (
    SELECT
        extract_date,
        project_id,
        project_name,
        program_name,
        application_no,
        cpr,
        indvidual_name,
        gender,
        date_of_birth,
        individual_segment,
        highest_education_qualification,
        specialization,
        gradudation_date,
        whitelisting,
        is_approved,
        decision_date,
        type_of_opportunity,
        mobile,
        office,
        email,
        first_joining_date,
        joining_date_current,
        cr_license_no_current,
        commercial_name_current,
        job_title_current,
        salary_current,
        total_months_of_work_experience,
        joining_date_new_placement,
        cr_license_no_new_placement,
        commercial_name_new_placement,
        job_title_new_placement,
        placement_location,
        placement_region,
        placement_country,
        wage_support_type,
        total_monthly_offer_bhd,
        months_of_support,
        subsidy,
        total_monthly_subsidy_tamkeen,
        total_salary_support_tamkeen,
        travel_cap,
        travel_actual,
        travel_support,
        visa_cap,
        visa_actual,
        visa_support,
        accommodation_cap,
        accommodation_actual,
        accommodation_support,
        transport_cap,
        transport_actual,
        transport_support,
        per_diem_cap,
        per_diem_actual,
        per_diem_support,
        program_cost_cap,
        program_cost_actual,
        program_cost_tamkeen_support,
        total_support_tamkeen,
        start_date_wage_support,
        end_date_wage_support,
        joining_date_new_employment,
        cr_license_no_new_employment,
        commercial_name_new_employment,
        job_title_new_employment,
        total_offer_bhd_new_employment,
        total_months_of_experience_new_employment,
        created_on,
        created_by,
        application_format,
        approved_by,
        source_system_name
    FROM `tmkn-dwh-iceberg-dev-fc`.`tmkn-aws-dwh-dev-iceberg-silver`.offline_sheets_grtandgre_individuals
),

bronze_columns(column_position, column_name) AS (
    VALUES
        (1, 'extract_date'),
        (2, 'project_id'),
        (3, 'project_name'),
        (4, 'program_name'),
        (5, 'application_no'),
        (6, 'cpr'),
        (7, 'indvidual_name'),
        (8, 'gender'),
        (9, 'date_of_birth'),
        (10, 'individual_segment'),
        (11, 'highest_education_qualification'),
        (12, 'specialization'),
        (13, 'gradudation_date'),
        (14, 'whitelisting'),
        (15, 'is_approved'),
        (16, 'decision_date'),
        (17, 'type_of_opportunity'),
        (18, 'mobile'),
        (19, 'office'),
        (20, 'email'),
        (21, 'first_joining_date'),
        (22, 'joining_date_current'),
        (23, 'cr_license_no_current'),
        (24, 'commercial_name_current'),
        (25, 'job_title_current'),
        (26, 'salary_current'),
        (27, 'total_months_of_work_experience'),
        (28, 'joining_date_new_placement'),
        (29, 'cr_license_no_new_placement'),
        (30, 'commercial_name_new_placement'),
        (31, 'job_title_new_placement'),
        (32, 'placement_location'),
        (33, 'placement_region'),
        (34, 'placement_country'),
        (35, 'wage_support_type'),
        (36, 'total_monthly_offer_bhd'),
        (37, 'months_of_support'),
        (38, 'subsidy'),
        (39, 'total_monthly_subsidy_tamkeen'),
        (40, 'total_salary_support_tamkeen'),
        (41, 'travel_cap'),
        (42, 'travel_actual'),
        (43, 'travel_support'),
        (44, 'visa_cap'),
        (45, 'visa_actual'),
        (46, 'visa_support'),
        (47, 'accommodation_cap'),
        (48, 'accommodation_actual'),
        (49, 'accommodation_support'),
        (50, 'transport_cap'),
        (51, 'transport_actual'),
        (52, 'transport_support'),
        (53, 'per_diem_cap'),
        (54, 'per_diem_actual'),
        (55, 'per_diem_support'),
        (56, 'program_cost_cap'),
        (57, 'program_cost_actual'),
        (58, 'program_cost_tamkeen_support'),
        (59, 'total_support_tamkeen'),
        (60, 'start_date_wage_support'),
        (61, 'end_date_wage_support'),
        (62, 'joining_date_new_employment'),
        (63, 'cr_license_no_new_employment'),
        (64, 'commercial_name_new_employment'),
        (65, 'job_title_new_employment'),
        (66, 'total_offer_bhd_new_employment'),
        (67, 'total_months_of_experience_new_employment'),
        (68, 'created_on'),
        (69, 'created_by'),
        (70, 'application_format'),
        (71, 'approved_by'),
        (72, 'source_system_name')
),

silver_columns(column_position, column_name) AS (
    VALUES
        (1, 'extract_date'),
        (2, 'project_id'),
        (3, 'project_name'),
        (4, 'program_name'),
        (5, 'application_no'),
        (6, 'cpr'),
        (7, 'indvidual_name'),
        (8, 'gender'),
        (9, 'date_of_birth'),
        (10, 'individual_segment'),
        (11, 'highest_education_qualification'),
        (12, 'specialization'),
        (13, 'gradudation_date'),
        (14, 'whitelisting'),
        (15, 'is_approved'),
        (16, 'decision_date'),
        (17, 'type_of_opportunity'),
        (18, 'mobile'),
        (19, 'office'),
        (20, 'email'),
        (21, 'first_joining_date'),
        (22, 'joining_date_current'),
        (23, 'cr_license_no_current'),
        (24, 'commercial_name_current'),
        (25, 'job_title_current'),
        (26, 'salary_current'),
        (27, 'total_months_of_work_experience'),
        (28, 'joining_date_new_placement'),
        (29, 'cr_license_no_new_placement'),
        (30, 'commercial_name_new_placement'),
        (31, 'job_title_new_placement'),
        (32, 'placement_location'),
        (33, 'placement_region'),
        (34, 'placement_country'),
        (35, 'wage_support_type'),
        (36, 'total_monthly_offer_bhd'),
        (37, 'months_of_support'),
        (38, 'subsidy'),
        (39, 'total_monthly_subsidy_tamkeen'),
        (40, 'total_salary_support_tamkeen'),
        (41, 'travel_cap'),
        (42, 'travel_actual'),
        (43, 'travel_support'),
        (44, 'visa_cap'),
        (45, 'visa_actual'),
        (46, 'visa_support'),
        (47, 'accommodation_cap'),
        (48, 'accommodation_actual'),
        (49, 'accommodation_support'),
        (50, 'transport_cap'),
        (51, 'transport_actual'),
        (52, 'transport_support'),
        (53, 'per_diem_cap'),
        (54, 'per_diem_actual'),
        (55, 'per_diem_support'),
        (56, 'program_cost_cap'),
        (57, 'program_cost_actual'),
        (58, 'program_cost_tamkeen_support'),
        (59, 'total_support_tamkeen'),
        (60, 'start_date_wage_support'),
        (61, 'end_date_wage_support'),
        (62, 'joining_date_new_employment'),
        (63, 'cr_license_no_new_employment'),
        (64, 'commercial_name_new_employment'),
        (65, 'job_title_new_employment'),
        (66, 'total_offer_bhd_new_employment'),
        (67, 'total_months_of_experience_new_employment'),
        (68, 'created_on'),
        (69, 'created_by'),
        (70, 'application_format'),
        (71, 'approved_by'),
        (72, 'source_system_name')
),

bronze_normalized AS (
    SELECT
        CAST(extract_date AS STRING) AS extract_date,
        CAST(project_id AS STRING) AS project_id,
        CAST(project_name AS STRING) AS project_name,
        CAST(program_name AS STRING) AS program_name,
        CAST(application_no AS STRING) AS application_no,
        CAST(cpr AS STRING) AS cpr,
        CAST(indvidual_name AS STRING) AS indvidual_name,
        CAST(gender AS STRING) AS gender,
        CAST(date_of_birth AS STRING) AS date_of_birth,
        CAST(individual_segment AS STRING) AS individual_segment,
        CAST(highest_education_qualification AS STRING) AS highest_education_qualification,
        CAST(specialization AS STRING) AS specialization,
        CAST(gradudation_date AS STRING) AS gradudation_date,
        CAST(whitelisting AS STRING) AS whitelisting,
        CAST(is_approved AS STRING) AS is_approved,
        CAST(decision_date AS STRING) AS decision_date,
        CAST(type_of_opportunity AS STRING) AS type_of_opportunity,
        CAST(mobile AS STRING) AS mobile,
        CAST(office AS STRING) AS office,
        CAST(email AS STRING) AS email,
        CAST(first_joining_date AS STRING) AS first_joining_date,
        CAST(joining_date_current AS STRING) AS joining_date_current,
        CAST(cr_license_no_current AS STRING) AS cr_license_no_current,
        CAST(commercial_name_current AS STRING) AS commercial_name_current,
        CAST(job_title_current AS STRING) AS job_title_current,
        CAST(salary_current AS STRING) AS salary_current,
        CAST(total_months_of_work_experience AS STRING) AS total_months_of_work_experience,
        CAST(joining_date_new_placement AS STRING) AS joining_date_new_placement,
        CAST(cr_license_no_new_placement AS STRING) AS cr_license_no_new_placement,
        CAST(commercial_name_new_placement AS STRING) AS commercial_name_new_placement,
        CAST(job_title_new_placement AS STRING) AS job_title_new_placement,
        CAST(placement_location AS STRING) AS placement_location,
        CAST(placement_region AS STRING) AS placement_region,
        CAST(placement_country AS STRING) AS placement_country,
        CAST(wage_support_type AS STRING) AS wage_support_type,
        CAST(total_monthly_offer_bhd AS STRING) AS total_monthly_offer_bhd,
        CAST(months_of_support AS STRING) AS months_of_support,
        CAST(subsidy AS STRING) AS subsidy,
        CAST(total_monthly_subsidy_tamkeen AS STRING) AS total_monthly_subsidy_tamkeen,
        CAST(total_salary_support_tamkeen AS STRING) AS total_salary_support_tamkeen,
        CAST(travel_cap AS STRING) AS travel_cap,
        CAST(travel_actual AS STRING) AS travel_actual,
        CAST(travel_support AS STRING) AS travel_support,
        CAST(visa_cap AS STRING) AS visa_cap,
        CAST(visa_actual AS STRING) AS visa_actual,
        CAST(visa_support AS STRING) AS visa_support,
        CAST(accommodation_cap AS STRING) AS accommodation_cap,
        CAST(accommodation_actual AS STRING) AS accommodation_actual,
        CAST(accommodation_support AS STRING) AS accommodation_support,
        CAST(transport_cap AS STRING) AS transport_cap,
        CAST(transport_actual AS STRING) AS transport_actual,
        CAST(transport_support AS STRING) AS transport_support,
        CAST(per_diem_cap AS STRING) AS per_diem_cap,
        CAST(per_diem_actual AS STRING) AS per_diem_actual,
        CAST(per_diem_support AS STRING) AS per_diem_support,
        CAST(program_cost_cap AS STRING) AS program_cost_cap,
        CAST(program_cost_actual AS STRING) AS program_cost_actual,
        CAST(program_cost_tamkeen_support AS STRING) AS program_cost_tamkeen_support,
        CAST(total_support_tamkeen AS STRING) AS total_support_tamkeen,
        CAST(start_date_wage_support AS STRING) AS start_date_wage_support,
        CAST(end_date_wage_support AS STRING) AS end_date_wage_support,
        CAST(joining_date_new_employment AS STRING) AS joining_date_new_employment,
        CAST(cr_license_no_new_employment AS STRING) AS cr_license_no_new_employment,
        CAST(commercial_name_new_employment AS STRING) AS commercial_name_new_employment,
        CAST(job_title_new_employment AS STRING) AS job_title_new_employment,
        CAST(total_offer_bhd_new_employment AS STRING) AS total_offer_bhd_new_employment,
        CAST(total_months_of_experience_new_employment AS STRING) AS total_months_of_experience_new_employment,
        CAST(created_on AS STRING) AS created_on,
        CAST(created_by AS STRING) AS created_by,
        CAST(application_format AS STRING) AS application_format,
        CAST(approved_by AS STRING) AS approved_by,
        CAST(source_system_name AS STRING) AS source_system_name
    FROM bronze_layer
),

silver_normalized AS (
    SELECT
        CAST(extract_date AS STRING) AS extract_date,
        CAST(project_id AS STRING) AS project_id,
        CAST(project_name AS STRING) AS project_name,
        CAST(program_name AS STRING) AS program_name,
        CAST(application_no AS STRING) AS application_no,
        CAST(cpr AS STRING) AS cpr,
        CAST(indvidual_name AS STRING) AS indvidual_name,
        CAST(gender AS STRING) AS gender,
        CAST(date_of_birth AS STRING) AS date_of_birth,
        CAST(individual_segment AS STRING) AS individual_segment,
        CAST(highest_education_qualification AS STRING) AS highest_education_qualification,
        CAST(specialization AS STRING) AS specialization,
        CAST(gradudation_date AS STRING) AS gradudation_date,
        CAST(whitelisting AS STRING) AS whitelisting,
        CAST(is_approved AS STRING) AS is_approved,
        CAST(decision_date AS STRING) AS decision_date,
        CAST(type_of_opportunity AS STRING) AS type_of_opportunity,
        CAST(mobile AS STRING) AS mobile,
        CAST(office AS STRING) AS office,
        CAST(email AS STRING) AS email,
        CAST(first_joining_date AS STRING) AS first_joining_date,
        CAST(joining_date_current AS STRING) AS joining_date_current,
        CAST(cr_license_no_current AS STRING) AS cr_license_no_current,
        CAST(commercial_name_current AS STRING) AS commercial_name_current,
        CAST(job_title_current AS STRING) AS job_title_current,
        CAST(salary_current AS STRING) AS salary_current,
        CAST(total_months_of_work_experience AS STRING) AS total_months_of_work_experience,
        CAST(joining_date_new_placement AS STRING) AS joining_date_new_placement,
        CAST(cr_license_no_new_placement AS STRING) AS cr_license_no_new_placement,
        CAST(commercial_name_new_placement AS STRING) AS commercial_name_new_placement,
        CAST(job_title_new_placement AS STRING) AS job_title_new_placement,
        CAST(placement_location AS STRING) AS placement_location,
        CAST(placement_region AS STRING) AS placement_region,
        CAST(placement_country AS STRING) AS placement_country,
        CAST(wage_support_type AS STRING) AS wage_support_type,
        CAST(total_monthly_offer_bhd AS STRING) AS total_monthly_offer_bhd,
        CAST(months_of_support AS STRING) AS months_of_support,
        CAST(subsidy AS STRING) AS subsidy,
        CAST(total_monthly_subsidy_tamkeen AS STRING) AS total_monthly_subsidy_tamkeen,
        CAST(total_salary_support_tamkeen AS STRING) AS total_salary_support_tamkeen,
        CAST(travel_cap AS STRING) AS travel_cap,
        CAST(travel_actual AS STRING) AS travel_actual,
        CAST(travel_support AS STRING) AS travel_support,
        CAST(visa_cap AS STRING) AS visa_cap,
        CAST(visa_actual AS STRING) AS visa_actual,
        CAST(visa_support AS STRING) AS visa_support,
        CAST(accommodation_cap AS STRING) AS accommodation_cap,
        CAST(accommodation_actual AS STRING) AS accommodation_actual,
        CAST(accommodation_support AS STRING) AS accommodation_support,
        CAST(transport_cap AS STRING) AS transport_cap,
        CAST(transport_actual AS STRING) AS transport_actual,
        CAST(transport_support AS STRING) AS transport_support,
        CAST(per_diem_cap AS STRING) AS per_diem_cap,
        CAST(per_diem_actual AS STRING) AS per_diem_actual,
        CAST(per_diem_support AS STRING) AS per_diem_support,
        CAST(program_cost_cap AS STRING) AS program_cost_cap,
        CAST(program_cost_actual AS STRING) AS program_cost_actual,
        CAST(program_cost_tamkeen_support AS STRING) AS program_cost_tamkeen_support,
        CAST(total_support_tamkeen AS STRING) AS total_support_tamkeen,
        CAST(start_date_wage_support AS STRING) AS start_date_wage_support,
        CAST(end_date_wage_support AS STRING) AS end_date_wage_support,
        CAST(joining_date_new_employment AS STRING) AS joining_date_new_employment,
        CAST(cr_license_no_new_employment AS STRING) AS cr_license_no_new_employment,
        CAST(commercial_name_new_employment AS STRING) AS commercial_name_new_employment,
        CAST(job_title_new_employment AS STRING) AS job_title_new_employment,
        CAST(total_offer_bhd_new_employment AS STRING) AS total_offer_bhd_new_employment,
        CAST(total_months_of_experience_new_employment AS STRING) AS total_months_of_experience_new_employment,
        CAST(created_on AS STRING) AS created_on,
        CAST(created_by AS STRING) AS created_by,
        CAST(application_format AS STRING) AS application_format,
        CAST(approved_by AS STRING) AS approved_by,
        CAST(source_system_name AS STRING) AS source_system_name
    FROM silver_layer
),

bronze_minus_silver AS (
    SELECT * FROM bronze_normalized
    EXCEPT ALL
    SELECT * FROM silver_normalized
),

silver_minus_bronze AS (
    SELECT * FROM silver_normalized
    EXCEPT ALL
    SELECT * FROM bronze_normalized
),

validation_results AS (
    SELECT
        'offline_sheets_grtandgre_individuals' AS table_name,
        'record_count' AS validation_point,
        CAST((SELECT COUNT(*) FROM bronze_layer) AS BIGINT) AS bronze_layer_count,
        CAST((SELECT COUNT(*) FROM silver_layer) AS BIGINT) AS silver_layer_count,
        CASE
            WHEN (SELECT COUNT(*) FROM bronze_layer) = (SELECT COUNT(*) FROM silver_layer)
                THEN 'PASS'
            ELSE 'FAIL'
        END AS validation_status

    UNION ALL

    SELECT
        'offline_sheets_grtandgre_individuals' AS table_name,
        'column_count' AS validation_point,
        CAST((SELECT COUNT(*) FROM bronze_columns) AS BIGINT) AS bronze_layer_count,
        CAST((SELECT COUNT(*) FROM silver_columns) AS BIGINT) AS silver_layer_count,
        CASE
            WHEN (SELECT COUNT(*) FROM bronze_columns) = (SELECT COUNT(*) FROM silver_columns)
                THEN 'PASS'
            ELSE 'FAIL'
        END AS validation_status

    UNION ALL

    SELECT
        'offline_sheets_grtandgre_individuals' AS table_name,
        'column_names_match' AS validation_point,
        CAST((
            SELECT COUNT(*)
            FROM bronze_columns b
            FULL OUTER JOIN silver_columns s
              ON b.column_position = s.column_position
             AND b.column_name = s.column_name
            WHERE b.column_name IS NULL
               OR s.column_name IS NULL
        ) AS BIGINT) AS bronze_layer_count,
        CAST(0 AS BIGINT) AS silver_layer_count,
        CASE
            WHEN NOT EXISTS (
                SELECT 1
                FROM bronze_columns b
                FULL OUTER JOIN silver_columns s
                  ON b.column_position = s.column_position
                 AND b.column_name = s.column_name
                WHERE b.column_name IS NULL
                   OR s.column_name IS NULL
            ) THEN 'PASS'
            ELSE 'FAIL'
        END AS validation_status

    UNION ALL

    SELECT
        'offline_sheets_grtandgre_individuals' AS table_name,
        'mismatching_rows_bronze_minus_silver' AS validation_point,
        CAST((SELECT COUNT(*) FROM bronze_minus_silver) AS BIGINT) AS bronze_layer_count,
        CAST(0 AS BIGINT) AS silver_layer_count,
        CASE
            WHEN (SELECT COUNT(*) FROM bronze_minus_silver) = 0
                THEN 'PASS'
            ELSE 'FAIL'
        END AS validation_status

    UNION ALL

    SELECT
        'offline_sheets_grtandgre_individuals' AS table_name,
        'mismatching_rows_silver_minus_bronze' AS validation_point,
        CAST(0 AS BIGINT) AS bronze_layer_count,
        CAST((SELECT COUNT(*) FROM silver_minus_bronze) AS BIGINT) AS silver_layer_count,
        CASE
            WHEN (SELECT COUNT(*) FROM silver_minus_bronze) = 0
                THEN 'PASS'
            ELSE 'FAIL'
        END AS validation_status
)

SELECT *
FROM validation_results
ORDER BY validation_point;
