select
program_name,
program_type,
reference,
application_id,
application_status,
amendmentno,
utilizedamount,
unutilizedamount,
totalapprovedamount,
totalavailableamt,
utilizedamt,
unutilizedamt,
customershareamt,
haswagesupportmolemployees,
cpr_number,
customer_enterprise_name,
approved_on_date,
contract_start_date,
monitoring_due_date,
contract_end_date,
total_approved_amount_tamkeen_share,
created_on,
submitted_on,
spending_period_end_date
--source_system_name
--is_deleted
--report_date
--dbt_updated_at
--latest
from dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".amendment_base_os2 order by application_id 