pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Python Version') {
            steps {
                bat '"C:\\Users\\MODICHERLA\\AppData\\Local\\Python\\bin\\python.exe" --version'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '''
                "C:\\Users\\MODICHERLA\\AppData\\Local\\Python\\bin\\python.exe" -m venv venv
                call venv\\Scripts\\activate
                pip install -r silver_layer_data_validation\\requirements.txt
                '''
            }
        }

        stage('Run Python Script') {
            steps {
                bat '''
                call venv\\Scripts\\activate
                python silver_layer_data_validation\\main_runner.py
                '''
            }
        }

        stage('Archive Output') {
            steps {
                archiveArtifacts artifacts: 'silver_layer_data_validation/output/**/*', allowEmptyArchive: true
            }
        }
    }
}