WITH BASE AS (
    SELECT DISTINCT
	APP.ID,
    APPSUP.AMENDMENTREQUESTID,
    APPSUP.APPLICATIONID,
    APP.CREATEDON,
	APP.APPROVEDON,
	amdment.SUBMITTEDON,
	--aps.SUBMITTEDTOEXTASSESSORON, --column not found
    APPSUP.ISACTIVE,
    APPSUP.PROVIDERID,
    APPSUP.EXTERNALPROVIDERID,
	CusIndApp.GENDERID,
	CusIndApp.DATEOFBIRTH,
	PORTUSR.NAME,
	OJTCUS.NAMEEN,
	--aps.LABEL, --column not found--ossys_bpm_activity_definition
	SS.REQUESTEDAMT,
	TRA.TKSHAREAMT,
	ACT.USER_ID,
	APPSUP.REFERENCENUMBER,
	Emp.TOTALMONTHSEXPERIENCE,
	ProgVer.COMMERCIALNAME_EN,
	APP.CUSTOMERTYPEID,
	CMP.REGISTRATIONDATE,
	EMP.JOBCURRENTWAGE,
    'Neo2' AS SOURCE_SYSTEM_NAME,
    CAST(current_timestamp AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_APPLICATIONSUPPORT APPSUP
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION4 APP 
ON APP.ID = APPSUP.APPLICATIONID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_AMENDMENTREQUEST amdment 
ON amdment.ID = APPSUP.AMENDMENTREQUESTID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_INDIVIDUAL CusIndApp 
On APPSUP.INDIVIDUALID = CusIndApp.ID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QM6_PORTALUSER PORTUSR 
ON PORTUSR.ID = APP.PORTALUSERID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_EMPLOYEE Emp 
ON Emp.APPLICATIONSUPPORTID = APPSUP.ID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMER OJTCUS 
ON Emp.EMPLOYERID = OJTCUS.ID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_VW9_TRAINING TRA 
ON TRA.APPLICATIONSUPPORTID = APPSUP.ID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_PROGRAMVERSION ProgVer 
ON ProgVer.ID = APP.PROGRAMVERSIONID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATIONCUSTOMER APPCUS 
ON APP.ID = APPCUS.APPLICATIONID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMERPROFILE CUSPROF 
ON CUSPROF.ID = APPCUS.CUSTOMERPROFILEID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMER CUS 
ON CUSPROF.CUSTOMERID = CUS.ID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_COMPANY CMP 
ON CUS.ID = CMP.ID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_SUPPORTSTRUCTURE SS
ON APPSUP.ID = SS.APPLICATIONSUPPORTID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_1AT_ASSESSMENT ass
ON ass.ID = APPSUP.APPLICATIONID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSSYS_BPM_PROCESS pro
ON pro.TOP_PROCESS_ID = ass.PROCESSID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSSYS_BPM_ACTIVITY act
ON act.Process_Id = pro.Id
)
SELECT 
    ID,
    AMENDMENTREQUESTID,
    APPLICATIONID,
    CAST(CREATEDON AS timestamp) AS CREATEDON,
    CAST(APPROVEDON AS timestamp) AS APPROVEDON,
    SUBMITTEDON,
    ISACTIVE,
    PROVIDERID,
    EXTERNALPROVIDERID,
    GENDERID,
    CAST(DATEOFBIRTH AS timestamp) AS DATEOFBIRTH,
    NAME,
    NAMEEN,
    REQUESTEDAMT,
    TKSHAREAMT,
    USER_ID,
    REFERENCENUMBER,
    TOTALMONTHSEXPERIENCE,
    COMMERCIALNAME_EN,
    CUSTOMERTYPEID,
    REGISTRATIONDATE,
    JOBCURRENTWAGE,
    SOURCE_SYSTEM_NAME,
    DBT_UPDATED_AT
FROM BASE
