-- Optional target table wrapper:
-- CREATE TABLE assessment_base_os2 AS

WITH cte_osusr_1at_assessment AS (
    SELECT
        ass.ID,
        ass.APPLICATIONID,
        ass.AMENDMENTREQUESTID,
        ass.ASSESSMENTROLE1,
        ass.ASSESSMENTROLE2,
        ass.REVIEWROLE,
        ass.APPROVEROLE,
        ass.PROCESSID,
        kt1.NAME AS ASSESSMENTTEAM1_NAME,
        kt2.NAME AS ASSESSMENTTEAM2_NAME,
        kt3.NAME AS REVIEWTEAM1_NAME,
        kt4.NAME AS APPROVETEAM1_NAME,
        assessmentstatus.LABEL AS ASSESSMENTSTATUSID,
        ass.ASSESSMENTROLEMOL,
        kt5.NAME AS ASSESSMENTTEAMMOL_NAME,
        ass.REVIEWROLE1,
        ass.REVIEWROLE2,
        ass.REVIEWTEAM2,
        ass.MONITORINGROLE1,
        ass.MONITORINGROLE2,
        ass.MONITORINGTEAM1,
        ass.MONITORINGTEAM2,
        FALSE AS IS_DELETED,
        'Neo2' AS SOURCE_SYSTEM_NAME,
        ass.UPDATEDON,
        ass.CREATEDON,
        CAST(current_timestamp AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT,
        ROW_NUMBER() OVER (
            PARTITION BY ass.ID
            ORDER BY ass.UPDATEDON DESC, ass.CREATEDON DESC
        ) AS RNK
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_1AT_ASSESSMENT ass
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_1AT_ASSESSMENTSTATUS assessmentstatus
        ON ass.ASSESSMENTSTATUSID = assessmentstatus.CODE
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_KUO_TEAM kt1
        ON ass.ASSESSMENTTEAM1 = kt1.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_KUO_TEAM kt2
        ON ass.ASSESSMENTTEAM2 = kt2.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_KUO_TEAM kt3
        ON ass.REVIEWTEAM1 = kt3.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_KUO_TEAM kt4
        ON ass.APPROVETEAM1 = kt4.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_KUO_TEAM kt5
        ON ass.ASSESSMENTTEAMMOL = kt5.ID
)
SELECT
    ID,
    APPLICATIONID,
    AMENDMENTREQUESTID,
    ASSESSMENTROLE1,
    ASSESSMENTROLE2,
    REVIEWROLE,
    APPROVEROLE,
    PROCESSID,
    NULLIF(TRIM(CAST(ASSESSMENTTEAM1_NAME AS VARCHAR)), '') AS ASSESSMENTTEAM1_NAME,
    NULLIF(TRIM(CAST(ASSESSMENTTEAM2_NAME AS VARCHAR)), '') AS ASSESSMENTTEAM2_NAME,
    NULLIF(TRIM(CAST(REVIEWTEAM1_NAME AS VARCHAR)), '') AS REVIEWTEAM1_NAME,
    NULLIF(TRIM(CAST(APPROVETEAM1_NAME AS VARCHAR)), '') AS APPROVETEAM1_NAME,
    ASSESSMENTSTATUSID,
    ASSESSMENTROLEMOL,
    NULLIF(TRIM(CAST(ASSESSMENTTEAMMOL_NAME AS VARCHAR)), '') AS ASSESSMENTTEAMMOL_NAME,
    REVIEWROLE1,
    REVIEWROLE2,
    REVIEWTEAM2,
    MONITORINGROLE1,
    MONITORINGROLE2,
    MONITORINGTEAM1,
    MONITORINGTEAM2,
    IS_DELETED,
    UPPER(NULLIF(TRIM(CAST(SOURCE_SYSTEM_NAME AS VARCHAR)), '')) AS SOURCE_SYSTEM_NAME,
    CAST(UPDATEDON AS timestamp) AS UPDATEDON,
    CAST(CREATEDON AS timestamp) AS CREATEDON,
    CAST(DBT_UPDATED_AT AS timestamp) AS DBT_UPDATED_AT
FROM cte_osusr_1at_assessment
WHERE RNK = 1;
