with cte_OSUSR_2DA_EMPLOYEE AS(
 
SELECT
    A.APPLICATIONSUPPORTID,
    A.EMAILADDRESS,
    A.MOBILECOUNTRYPREFIX,
    A.MOBILENUMBER,
    c2.LABEL as ACADEMICDEGREE,
    A.UNIVERSITYNAME,
    C3.COUNTRYNAME as UNIVERSITYLOCATION,
    A.DEGREESPECIALIZATION,
    CAST(A.DATEDEGREEGRADUATION AS date) as DATEDEGREEGRADUATION,
    C4.LABEL as JOBLEVEL,
    A.JOBTITLE,
    A.JOBDEPARTMENT,
    A.JOBRESPONSABILITIES,
    A.JOBCURRENTWAGE,
    C5.LABEL as  SALARYSTATUS,
    CAST(A.JOININGDATE AS date) as JOININGDATE,
    A.CURRENTMONTHSEXPERIENCE,
    A.TOTALMONTHSEXPERIENCE,
    C6.LABEL as EMPLOYMENTTYPE,
    C1.LABEL as EMPLOYEECONTRACTTYPE,
    CAST(A.EMPLOYMENTCONTRACTSTARTDATE AS date) as EMPLOYMENTCONTRACTSTARTDATE,
    CAST(A.EMPLOYMENTCONTRACTENDDATE AS date) as EMPLOYMENTCONTRACTENDDATE,
    C7.LABEL as SEGMENTTYPE ,
    A.FREQUENCYOFPAYMENT,
    A.UNIVERSITYLOCATIONS,
    C8.NAMEEN as EMPLOYER,
    A.EMPLOYERID ,
    CAST(A.LASTWORKINGDAYDATE AS date) as LASTWORKINGDAYDATE,
    A.EMPLOYERCODE,
    C9.LABEL AS REMOVEEMPLOYEEREASONS,
    A.REMOVEEMPLOYEEREASONSOTHER,
    A.EMPLOYERNAME,
    A.IBAN,
    C10.LABEL AS ISPHYSICALLYDISABLED,
    A.JOBCODE,
    A.SIOSALARY,
    C11.LABEL as TYPEOFWORKARRANGEMENT,
    A.ISRELATEDTOCROWNER,
    A.RELATION,
    A.ISOUTSOURCED,
    A.ISREPLACINGNONBAHRAINI,
    A.EMPLOYEETYPEID,
    A.CONTRACTTYPE,
    CAST(A.CONTRACTSTARTDATE AS date) as CONTRACTSTARTDATE,
    CAST(A.CONTRACTENDDATE AS date) as CONTRACTENDDATE,
    'Neo2' AS SOURCE_SYSTEM_NAME,
    cast(current_timestamp AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_EMPLOYEE A
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_EMPLOYEECONTRACTTYPE C1
    ON C1.CODE = A.EMPLOYEECONTRACTTYPEID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_398_ACADEMICDEGREE C2
    ON C2.CODE = A.ACADEMICDEGREEID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_398_COUNTRY C3
    ON C3.ID = TRY_CAST(A.UNIVERSITYLOCATION AS BIGINT)
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_JOBLEVEL C4
    ON C4.CODE = A.JOBLEVELID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_SALARYSTATUS C5
    ON C5.CODE = A.SALARYSTATUSID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_EMPLOYMENTTYPE C6
    ON C6.CODE = A.EMPLOYMENTTYPEID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_APPLICANTSEGMENT C7
    ON C7.CODE = A.SEGMENTTYPEID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMER C8
    ON C8.ID = A.EMPLOYERID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_REMOVEEMPLOYEEREASONS C9
    ON C9.CODE = A.REMOVEEMPLOYEEREASONSID
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MM5_YESNOOPTION4 C10
    ON C10.ID = A.ISPHYSICALLYDISABLED
LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_TYPEOFWORKARRANGEMENT C11
    ON C11.ID = A.TYPEOFWORKARRANGEMENTID

)
select * from cte_OSUSR_2DA_EMPLOYEE