WITH source_cte AS (
    SELECT
        F.ID,
        F.FINANCINGAMOUNTREQUESTED,
        F.TENOR,
        F.GRACEPERIOD,
        FT.LABEL AS FACILITYTYPE,
        YN1.LABEL AS REVOLVINGLOAN,
        F.AVAILABILITYPERIOD,
        DT.LABEL AS DISBURSEMENTTYPE,
        FPT.LABEL AS FINANCINGPRODUCTTYPE,
        F.FINANCINGPRODUCTTYPEOTHER,
        PF.LABEL AS PAYMENTFREQUENCY,
        TRY_CAST(F.BANKAPPROVALDATE AS TIMESTAMP) AS BANKAPPROVALDATE,
        YN2.LABEL AS FACILITIESWITHBANK,
        YN3.LABEL AS WORKINGCAPITALFACILITIESWITH,
        F.INTERNALRISKRATING,
        F.SECURITYCOVERAGE,
        F.CASHCONVERSIONCYCLE,
        F.DEBTSERVICECOVERAGERATIO,
        F.MACHINERYANDEQUIPMENT,
        F.TECHNOLOGY,
        F.MARKETINGANDBRANDING,
        F.WORKINGCAPITAL,
        F.FIXTURESANDFITTINGS,
        F.FACILITYBREAKUPOTHERAMOUNT,
        F.FACILITYBREAKUPOTHERVALUE,
        F.COMMENTWORKCAPITAL,
        F.COMMENTREVOLVINGLOAN,
        F.FIXEDASSETSAMTREQUESTED,
        F.FIXEDASSESTSAMTREMAINING,
        F.WORKINGCAPITALAMTREQUESTED,
        F.WORKINGCAPITALAMTREMAINING,
        F.COMMENTWORKINGCAPITAL,
        F.FINANCINGAMTREQUESTED,
        F.FINANCINGAMTREMAINING,
        F.WORKINGCAPITALCAPID,
        F.WORKINGCAPITALREMANINGCAP,
        F.FINANCINGAMTCAPID,
        F.FINANCINGAMTREMANINGCAP,
        F.ISANYFIELDUPDATEDFORAMENDMEN,
        FALSE AS IS_DELETED,
        F.ISACTIVE,
        F.CREATEDBY,
        F.CREATEDON,
        F.UPDATEDBY,
        F.UPDATEDON,
        'Neo2' AS SOURCE_SYSTEM_NAME,
        CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS DBT_UPDATED_AT,
        ROW_NUMBER() OVER (
            PARTITION BY F.ID
            ORDER BY COALESCE(F.UPDATEDON, F.CREATEDON) DESC, F.CREATEDON DESC
        ) AS RNK
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_FINANCING F
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_H95_FACILITYTYPE FT
        ON F.FACILITYTYPEID = FT.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_398_YESNOOPTION YN1
        ON F.REVOLVINGLOAN = YN1.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_DISBURSEMENTTYPE DT
        ON F.DISBURSEMENTTYPEID = DT.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_FINANCINGPRODUCTTYPE FPT
        ON F.FINANCINGPRODUCTTYPEID = FPT.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_H95_PAYMENTFREQUENCY PF
        ON F.PAYMENTFREQUENCYID = PF.CODE
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MM5_YESNOOPTION4 YN2
        ON F.FACILITIESWITHBANK = YN2.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MM5_YESNOOPTION4 YN3
        ON F.WORKINGCAPITALFACILITIESWITH = YN3.ID
)

SELECT
    ID,
    FINANCINGAMOUNTREQUESTED,
    TENOR,
    GRACEPERIOD,
    FACILITYTYPE,
    REVOLVINGLOAN,
    AVAILABILITYPERIOD,
    DISBURSEMENTTYPE,
    FINANCINGPRODUCTTYPE,
    FINANCINGPRODUCTTYPEOTHER,
    PAYMENTFREQUENCY,
    TRY_CAST(BANKAPPROVALDATE AS TIMESTAMP) AS BANKAPPROVALDATE,
    FACILITIESWITHBANK,
    WORKINGCAPITALFACILITIESWITH,
    INTERNALRISKRATING,
    SECURITYCOVERAGE,
    CASHCONVERSIONCYCLE,
    DEBTSERVICECOVERAGERATIO,
    MACHINERYANDEQUIPMENT,
    TECHNOLOGY,
    MARKETINGANDBRANDING,
    WORKINGCAPITAL,
    FIXTURESANDFITTINGS,
    FACILITYBREAKUPOTHERAMOUNT,
    FACILITYBREAKUPOTHERVALUE,
    COMMENTWORKCAPITAL,
    COMMENTREVOLVINGLOAN,
    FIXEDASSETSAMTREQUESTED,
    FIXEDASSESTSAMTREMAINING,
    WORKINGCAPITALAMTREQUESTED,
    WORKINGCAPITALAMTREMAINING,
    COMMENTWORKINGCAPITAL,
    FINANCINGAMTREQUESTED,
    FINANCINGAMTREMAINING,
    WORKINGCAPITALCAPID,
    WORKINGCAPITALREMANINGCAP,
    FINANCINGAMTCAPID,
    FINANCINGAMTREMANINGCAP,
    ISANYFIELDUPDATEDFORAMENDMEN,
    IS_DELETED,
    ISACTIVE,
    CREATEDBY,
    UPDATEDBY,
    TRY_CAST(CREATEDON AS TIMESTAMP) AS CREATEDON,
    TRY_CAST(UPDATEDON AS TIMESTAMP) AS UPDATEDON,
    DBT_UPDATED_AT,
    UPPER(TRIM(SOURCE_SYSTEM_NAME)) AS SOURCE_SYSTEM_NAME
FROM source_cte
WHERE RNK = 1;
