WITH CTE_IBAN_FINANCE AS (
    SELECT
        IBAN.ID,
        IBAN.IBANNUMBER,
        IBST.LABEL AS IBAN_STATUS,
        IBAN.CUSTOMERPROFILEID,
        IBAN.PORTALUSERID,
        IBAN.IBANSTATUSID,
        IBAN.BANKID,
        IBAN.DOCCHECKLISTGUID,
        IBAN.UPDATEDBY,
        IBAN.ISDEFAULT,
        IBAN.ISVERIFIEDBYTARABUT,
        IBAN.ISSALARYIBAN,
        IBAN.EXTERNALBANKID,
        IBAN.CURRENCY,
        IBAN.DEACTIVATEDON,
        IBAN.DOCDEACTIVATEGUID,
        IBAN.REASONSFORDEACTIVATION,
        CASE
            WHEN CusType.LABEL = 'Individual' THEN IND.CPRNUMBER
            ELSE CMP.CODE
        END AS PAYEE_CPR_CR_LICENSE,
        CUS.NAMEEN AS CUSTOMER_NAME_COMMERCIAL_NAME_ENGLISH,
        IBAN.EMAIL AS EMAIL,
        CONCAT('+', IBAN.MOBILECOUNTRYPREFIX, ' ', IBAN.MOBILENUMBER) AS MOBILE_NUMBER,
        IBAN.ACCOUNTNAME AS ACCOUNT_NAME,
        BANK.BANKNAME AS BANK_NAME,
        CASE
            WHEN IBAN.CREATEDON = CAST('1900-01-01 00:00:00.000' AS TIMESTAMP)
                THEN NULL
            ELSE IBAN.CREATEDON + INTERVAL '3' HOUR
        END AS CREATEDON,
        IBAN.CREATEDBY AS CREATED_BY,
        BANK.SWIFTBANKCODE AS SWIFT_CODE,
        BANK.BICCODE AS BIC_CODE,
        CusType.LABEL AS CUSTOMER_TYPE,
        IBAN.UPDATEDON AS UPDATEDON,
        CASE
            WHEN IBAN.IBANSTATUSID = 'VER' THEN IBAN.UPDATEDON
            ELSE NULL
        END AS VERIFIED_ON,
        ROW_NUMBER() OVER (
            PARTITION BY IBAN.ID
            ORDER BY IBAN.CREATEDON DESC, IBAN.CREATEDON DESC
        ) AS RNK,
        FALSE AS IS_DELETED,
        'Neo2' AS SOURCE_SYSTEM_NAME,
        CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS DBT_UPDATED_AT
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_TLV_IBAN IBAN
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_TLV_BANK BANK
        ON BANK.ID = IBAN.BANKID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_TLV_IBANSTATUS IBST
        ON IBAN.IBANSTATUSID = IBST.CODE
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMERPROFILE CUSPROF
        ON CUSPROF.ID = IBAN.CUSTOMERPROFILEID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMER CUS
        ON CUSPROF.CUSTOMERID = CUS.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMERTYPE CusType
        ON CusType.CODE = CUS.CUSTOMERTYPEID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_INDIVIDUAL IND
        ON CUSPROF.CUSTOMERID = IND.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_COMPANY CMP
        ON CUSPROF.CUSTOMERID = CMP.ID
)

SELECT
    CAST(ID AS INTEGER) AS ID,
    IBANNUMBER,
    IBAN_STATUS,
    CUSTOMERPROFILEID,
    PORTALUSERID,
    IBANSTATUSID,
    BANKID,
    DOCCHECKLISTGUID,
    UPDATEDBY,
    ISDEFAULT,
    ISVERIFIEDBYTARABUT,
    ISSALARYIBAN,
    EXTERNALBANKID,
    CURRENCY,
    DEACTIVATEDON,
    DOCDEACTIVATEGUID,
    REASONSFORDEACTIVATION,
    PAYEE_CPR_CR_LICENSE,
    CUSTOMER_NAME_COMMERCIAL_NAME_ENGLISH,
    EMAIL,
    MOBILE_NUMBER,
    ACCOUNT_NAME,
    BANK_NAME,
    CAST(CREATEDON AS TIMESTAMP) AS CREATEDON,
    CREATED_BY,
    SWIFT_CODE,
    BIC_CODE,
    CUSTOMER_TYPE,
    CAST(UPDATEDON AS TIMESTAMP) AS UPDATEDON,
    CAST(VERIFIED_ON AS TIMESTAMP) AS VERIFIED_ON,
    IS_DELETED,
    UPPER(TRIM(SOURCE_SYSTEM_NAME)) AS SOURCE_SYSTEM_NAME,
    CAST(DBT_UPDATED_AT AS TIMESTAMP) AS DBT_UPDATED_AT
FROM CTE_IBAN_FINANCE
WHERE RNK = 1;

