WITH CTE_MOIC AS (

    SELECT
        MOIC1.*,
        FALSE AS IS_DELETED,
        'Neo2' AS SOURCE_SYSTEM_NAME,
        CAST(current_timestamp AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT,

        ROW_NUMBER() OVER (PARTITION BY MOIC1.APPLICATIONID ORDER BY MOIC1.UPDATEDON DESC, MOIC1.CREATEDON DESC) AS RNK

    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MYA_MOIC_CRDETAILS MOIC1

    WHERE MOIC1.PAYMENTREQUESTID = 0
      AND MOIC1.ELIGIBILITYCRITERIAREQUESTTY = 'ASS'
      AND MOIC1.CRNUMBER IS NOT NULL
      AND MOIC1.CRNUMBER <> ''

),

CTE_LMRA AS (

    SELECT
        LMRA.*

    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MYA_LMRA_DETAILS LMRA

    WHERE LMRA.PAYMENTREQUESTID = 0
      AND LMRA.ELIGIBILITYCRITERIAREQUESTTY = 'ASS'

),

CTE_SIO AS (

    SELECT
        SIO.*

    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MYA_SIO_ESTABLISHMENTDETAILS SIO

    WHERE SIO.PAYMENTREQUESTID = 0
      AND SIO.ELIGIBILITYCRITERIAREQUESTTY = 'ASS'

)

SELECT
    CAST(current_timestamp AT TIME ZONE 'UTC' AS date) AS EXTRACT_DATE,

    -- =========================================================================
    -- MOIC CRDETAILS
    -- =========================================================================

    MOIC1.ID,
    MOIC1.APPLICATIONID AS ID_APPLICATION,
    MOIC1.PAYMENTREQUESTID,
    MOIC1.ELIGIBILITYCRITERIAREQUESTTY,
    MOIC1.CRNUMBER,
    MOIC1.COMPANYCATEGORYID,
    MOIC1.COMPANYTYPECODE,
    MOIC1.NATIONALITYCODE,
    MOIC1.PSMONITORINGID,
    MOIC1.AMENDMENTREQUESTID,
    MOIC1.COMNERCIALNAMEEN,
    MOIC1.COMNERCIALNAMEAR,
    MOIC1.ENTERPRISEGENDERID,
    MOIC1.ENTERPRISEAGE,
    MOIC1.COMPANYTYPE,
    MOIC1.ISVIRTUAL,
    MOIC1.REGISTRATIONDATE,
    MOIC1.EXPIRATIONDATE,
    MOIC1.NATIONALITY,
    MOIC1.STATUS,
    MOIC1.ISSUEDCAPITAL,
    MOIC1.LOCALINVESTMENT,
    MOIC1.FOREIGNINVESTMENT,
    MOIC1.GCCINVESTMENT,
    MOIC1.ADDRESSFLAT,
    MOIC1.ADDRESSROAD,
    MOIC1.ADDRESSBUILDING,
    MOIC1.ADDRESSTOWN,
    MOIC1.ADDRESSBLOCK,

    -- =========================================================================
    -- Existing SP Logic
    -- =========================================================================

    UPPER(TRIM(MOIC1.COMNERCIALNAMEEN)) AS COMMERCIAL_NAME_EN,
    UPPER(TRIM(MOIC1.COMNERCIALNAMEAR)) AS COMMERCIAL_NAME_AR,
    MOIC1.ENTERPRISEGENDERID AS ENTERPRISE_GENDER,

    CASE
        WHEN MOIC1.COMPANYCATEGORYID IS NULL
          OR MOIC1.COMPANYCATEGORYID = '' THEN
            CASE
                WHEN LMRA.ACTIVEWORKERS
                   + LMRA.PARALLELEXPATS
                   + SIO.TOTALBAHRAINIWORKERS > 100 THEN 'LARGE'

                WHEN LMRA.ACTIVEWORKERS
                   + LMRA.PARALLELEXPATS
                   + SIO.TOTALBAHRAINIWORKERS > 50 THEN 'MEDI'

                WHEN LMRA.ACTIVEWORKERS
                   + LMRA.PARALLELEXPATS
                   + SIO.TOTALBAHRAINIWORKERS < 51 THEN 'SMALL'

                ELSE 'unclassified'
            END
        ELSE MOIC1.COMPANYCATEGORYID
    END AS ENTERPRISE_SIZE,

    MOIC1.ENTERPRISEAGE AS ENTERPRISE_AGE,
    MOIC1.COMPANYTYPE AS CR_TYPE,

    CASE
        WHEN MOIC1.ISVIRTUAL = FALSE THEN 'No'
        WHEN MOIC1.ISVIRTUAL = TRUE THEN 'Yes'
        ELSE NULL
    END AS IS_VIRTUAL,

    CAST(MOIC1.REGISTRATIONDATE AS date) AS REGISTRATION_DATE,
    CAST(MOIC1.EXPIRATIONDATE AS date) AS EXPIRATION_DATE,
    MOIC1.NATIONALITY AS CR_NATIONALITY,
    MOIC1.STATUS AS CR_LICENSE_STATUS,
    MOIC1.ISSUEDCAPITAL AS CAPITAL_ISSUED,
    MOIC1.LOCALINVESTMENT AS CAPITAL_LOCAL_INVESTMENT,
    MOIC1.FOREIGNINVESTMENT AS CAPITAL_FOREIGN_INVESTMENT,
    MOIC1.GCCINVESTMENT AS CAPITAL_GCC_INVESTMENT,
    MOIC1.ADDRESSFLAT AS ADDRESS_FLAT,
    MOIC1.ADDRESSROAD AS ADDRESS_ROAD,
    MOIC1.ADDRESSBUILDING AS ADDRESS_BUILDING,
    MOIC1.ADDRESSTOWN AS ADDRESS_AREA,
    MOIC1.ADDRESSBLOCK AS ADDRESS_BLOCK,

    -- =========================================================================
    -- LMRA DETAILS
    -- =========================================================================

    LMRA.ID AS LMRA_ID,
    LMRA.APPLICATIONID AS LMRA_APPLICATIONID,
    LMRA.PAYMENTREQUESTID AS LMRA_PAYMENTREQUESTID,
    LMRA.ELIGIBILITYCRITERIAREQUESTTY AS LMRA_ELIGIBILITYCRITERIAREQUESTTY,
    LMRA.CODE,
    LMRA.TOTALBAHRAINIDISABLEWORKERS,
    LMRA.ISSUBJECTTOBAHRAINIZATION,
    LMRA.BAHRAINIZATIONTARGETPCT,
    LMRA.BAHRAINIZATIONCURRENTPCT,
    LMRA.BAHRAINIZATIONRATEDIFFPCT,
    LMRA.NOOFINVESTORS,
    LMRA.HWTOWORKS,
    LMRA.ACTIVEWORKERS,
    LMRA.PARALLELEXPATS,
    LMRA.INPROGRESSREQUESTS,
    LMRA.TOTALNOOFNONBAHRANIWORKS,
    LMRA.NOOFNONBAHRAINIPARALLEL,
    LMRA.AMENDMENTREQUESTID AS LMRA_AMENDMENTREQUESTID,

    CAST(LMRA.CREATEDON AS timestamp) AS LMRA_CREATEDON,
    CAST(LMRA.UPDATEDON AS timestamp) AS LMRA_UPDATEDON,

    -- =========================================================================
    -- SIO DETAILS
    -- =========================================================================

    SIO.ID AS SIO_ID,
    SIO.APPLICATIONID AS SIO_APPLICATIONID,
    SIO.PAYMENTREQUESTID AS SIO_PAYMENTREQUESTID,
    SIO.ELIGIBILITYCRITERIAREQUESTTY AS SIO_ELIGIBILITYCRITERIAREQUESTTY,
    SIO.CODE AS SIO_CODE,
    SIO.TOTALBAHRAINIWORKERS,
    SIO.TOTALBAHRAINISALARIES,
    SIO.TOTALEXPATRIATESALARIES,
    SIO.TOTALBAHRAINISALARIES600,
    SIO.TOTALEXPATRIATESSALARIES600,
    SIO.SITEVISITMONITORINGID,
    SIO.AMENDMENTREQUESTID AS SIO_AMENDMENTREQUESTID,

    CAST(MOIC1.CREATEDON AS timestamp) AS CREATEDON,
    CAST(MOIC1.UPDATEDON AS timestamp) AS UPDATEDON,

    MOIC1.IS_DELETED,
    UPPER(TRIM(MOIC1.SOURCE_SYSTEM_NAME)) AS SOURCE_SYSTEM_NAME,
    MOIC1.DBT_UPDATED_AT

FROM CTE_MOIC MOIC1

LEFT JOIN CTE_LMRA LMRA
    ON LMRA.APPLICATIONID = MOIC1.APPLICATIONID

LEFT JOIN CTE_SIO SIO
    ON SIO.APPLICATIONID = MOIC1.APPLICATIONID

WHERE MOIC1.RNK = 1
