-- Optional target table wrapper:
-- CREATE TABLE silver.payment_support_base_os2 AS

WITH CTE_PAYMENTSUPPORT AS (
    SELECT
        A.ID,
        A.PAYMENTRESQUESTID,
        A.APPLICATIONSUPPORTID,
        ST.LABEL AS SUPPORTTYPE,
        PSS.LABEL AS PAYMENTSUPPORTSTATUS,
        A.DOCUMENTINSTANCEGUID,
        PSS.ICONCLASS,
        PSS.COLORCODE,
        A.ISDOCUMENTSCOMPLETE,
        A.ITEMCOSTCURRENCYID,
        C.NAMEEN AS ITEMCOSTCURRENCY,
        A.CUSTOMERCOSTFX,
        A.ITEMCOSTNOVATAMT_FC,
        A.ITEMLINEDISCOUNTAMT,
        A.ITEMCOSTDISCOUNTPCT,
        A.ITEMCOSTVATPCT,
        A.ITEMQTDTOCLAIM,
        A.ITEMQUOTEDISCOUNTAMT,
        A.ITEMCOSTDISCOUNTAMT,
        A.ITEMVATAMTUN_FC,
        A.ITEMCOSTUN,
        A.ITEMCOSTTOTAL,
        A.ITEMCOSTUN_FC,
        A.ITEMCOSTTOTAL_FC,
        A.SUPPORTEDAMT,
        A.TKSHAREUNAMTAUTO,
        A.TKSHAREUN,
        A.TKSHAREPCT,
        A.TKSHAREPCTNOVAT,
        A.TKSHARETOTAL,
        A.CUSTOMERSHAREUN,
        A.CUSTOMERSHARETOTAL,
        A.ITEMQTDDELIVERED,
        PDS.LABEL AS PAYMENTDELIVERYSTATUS,
        A.REMARKS,
        A.INTERNALDOCUMENTINSTANCEGUID,
        FALSE AS IS_DELETED,
        'Neo2' AS SOURCE_SYSTEM_NAME,
        A.UPDATEDON,
        A.CREATEDON,
        A.CREATEDBY,
        A.UPDATEDBY,
        CAST(current_timestamp AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT,
        ROW_NUMBER() OVER (
            PARTITION BY A.ID
            ORDER BY COALESCE(A.UPDATEDON, A.CREATEDON) DESC, A.CREATEDON DESC
        ) AS RNK
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_WZ3_PAYMENTSUPPORT A
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_WZ3_PAYMENTREQUEST PR
        ON PR.ID = A.PAYMENTRESQUESTID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_APPLICATIONSUPPORT AST
        ON AST.ID = A.APPLICATIONSUPPORTID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_398_SUPPORTTYPE ST
        ON ST.CODE = A.SUPPORTTYPEID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_WZ3_PAYMENTSUPPORTSTATUS PSS
        ON PSS.CODE = A.PAYMENTSUPPORTSTATUSID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MM5_CURRENCY4 C
        ON C.ISOCODE = A.ITEMCOSTCURRENCYID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_WZ3_PAYMENTDELIVERYSTATUS PDS
        ON PDS.CODE = A.PAYMENTDELIVERYSTATUSID
)

SELECT
    ID,
    PAYMENTRESQUESTID,
    APPLICATIONSUPPORTID,
    SUPPORTTYPE,
    PAYMENTSUPPORTSTATUS,
    DOCUMENTINSTANCEGUID,
    ICONCLASS,
    COLORCODE,
    ISDOCUMENTSCOMPLETE,
    ITEMCOSTCURRENCY,
    CUSTOMERCOSTFX,
    ITEMCOSTNOVATAMT_FC,
    ITEMLINEDISCOUNTAMT,
    ITEMCOSTDISCOUNTPCT,
    ITEMCOSTVATPCT,
    ITEMQTDTOCLAIM,
    ITEMQUOTEDISCOUNTAMT,
    ITEMCOSTDISCOUNTAMT,
    ITEMVATAMTUN_FC,
    ITEMCOSTUN,
    ITEMCOSTTOTAL,
    ITEMCOSTUN_FC,
    ITEMCOSTTOTAL_FC,
    SUPPORTEDAMT,
    TKSHAREUNAMTAUTO,
    TKSHAREUN,
    TKSHAREPCT,
    TKSHAREPCTNOVAT,
    TKSHARETOTAL,
    CUSTOMERSHAREUN,
    CUSTOMERSHARETOTAL,
    ITEMQTDDELIVERED,
    PAYMENTDELIVERYSTATUS,
    REMARKS,
    INTERNALDOCUMENTINSTANCEGUID,
    IS_DELETED,
    UPPER(TRIM(SOURCE_SYSTEM_NAME)) AS SOURCE_SYSTEM_NAME,
    CAST(UPDATEDON AS timestamp) AS UPDATEDON,
    CAST(CREATEDON AS timestamp) AS CREATEDON,
    CREATEDBY,
    UPDATEDBY,
    DBT_UPDATED_AT
FROM CTE_PAYMENTSUPPORT PS
WHERE RNK = 1;
