SELECT
	A.ID,
    B.LABEL AS PROGRAMSTATUS,
    C.COMMERCIALNAME_EN AS PROGRAMGROUP,
    A.PROGRAMVERSIONID,
    D.LABEL AS CUSTOMERTYPE,
    E.LABEL AS PROFILETYPE,
	A.REFERENCE,
	A.INITIALS,
	A.NAME,
	A.DESCRIPTION,
	A.ISSPECIALPROGRAM,
	A.CANCELREASON,
	A.ACTIVEDATE,
	A.ENDDATE,
	A.CMSPROGRAM_EN,
	A.CMSPROGRAM_AR,
	A.ISSHOWINTERESTENABLED,
	A.PROGRAMMINORVERSIONID,
    FALSE as IS_DELETED,
   'Neo2' AS SOURCE_SYSTEM_NAME,
   CAST(current_timestamp AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_PROGRAM A
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_PROGRAMSTATUS B
       ON A.PROGRAMSTATUSID = B.CODE
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_PROGRAMGROUP C
       ON A.PROGRAMGROUPID = C.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMERTYPE D
       ON A.CUSTOMERTYPEID = D.CODE
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_PROFILETYPE E
       ON A.PROFILETYPEID = E.CODE
