WITH CTE_OSUSR_VW9_TRAININGDELIVERYTYPE AS (
    SELECT
        TDT.LABEL,
        FALSE AS IS_DELETED,
        'NEO2' AS SOURCE_SYSTEM_NAME,
        TDT.BRONZE_UPDATED_ON AS UPDATEDON,
        TDT.BRONZE_CREATED_ON AS CREATEDON,
        CAST(current_timestamp AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_VW9_TRAININGDELIVERYTYPE TDT
)
SELECT
    LABEL,
    IS_DELETED,
    UPPER(TRIM(SOURCE_SYSTEM_NAME)) AS SOURCE_SYSTEM_NAME,
    CAST(UPDATEDON AS timestamp) AS UPDATEDON,
    CAST(CREATEDON AS timestamp) AS CREATEDON,
    CAST(DBT_UPDATED_AT AS timestamp) AS DBT_UPDATED_AT
FROM CTE_OSUSR_VW9_TRAININGDELIVERYTYPE TDT;
