WITH cte_OSUSR_2DA_SUPPORTSTRUCTURE AS (
    SELECT
        SS.APPLICATIONSUPPORTID,
        PTS.NAMEEN AS PROGRAMSUPPORTTYPESUBITEMID,
        SS.DESCRIPTION,
        SS.REQUESTEDAMT,
        SS.TKSHAREOVR,
        SS.TKSHARE,
        Y.LABEL AS ISELIGIBLE,
        SS.ELIGIBLEERRORMESAGE,
        SS.DUEDATE,
        SS.REQUIRESINSPECTION,
        SS.ITEMAMTAVAILABLE,
        SS.ITEMAMTINPROGRESS,
        SS.ITEMAMTCLAIMED,
        SS.NUMBEROFCLAIMS,
        FALSE AS IS_DELETED,
        'NEO2' AS SOURCE_SYSTEM_NAME,
        SS.UPDATEDON,
        SS.CREATEDON,
        CAST(current_timestamp AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT,
        ROW_NUMBER() OVER (
            PARTITION BY SS.APPLICATIONSUPPORTID
            ORDER BY COALESCE(SS.UPDATEDON, SS.CREATEDON) DESC, SS.CREATEDON DESC
        ) AS rnk
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_SUPPORTSTRUCTURE SS
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_PROGRAMSUPPORTTYPESUBITEM3 PTS
        ON PTS.ID = SS.PROGRAMSUPPORTTYPESUBITEMID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MM5_YESNOOPTION4 Y
        ON Y.ID = SS.ISELIGIBLE
)

SELECT
    CAST(APPLICATIONSUPPORTID AS integer) AS APPLICATIONSUPPORTID,
    PROGRAMSUPPORTTYPESUBITEMID,
    DESCRIPTION AS DESCRIPTION,
    REQUESTEDAMT,
    TKSHAREOVR,
    TKSHARE,
    ISELIGIBLE,
    ELIGIBLEERRORMESAGE AS ELIGIBLEERRORMESAGE,
    CAST(DUEDATE AS date) AS DUEDATE,
    CAST(REQUIRESINSPECTION AS integer) AS REQUIRESINSPECTION,
    ITEMAMTAVAILABLE,
    ITEMAMTINPROGRESS,
    ITEMAMTCLAIMED,
    CAST(NUMBEROFCLAIMS AS integer) AS NUMBEROFCLAIMS,
    IS_DELETED AS IS_DELETED,
    UPPER(TRIM(SOURCE_SYSTEM_NAME)) AS SOURCE_SYSTEM_NAME,
    CAST(UPDATEDON AS timestamp) AS UPDATEDON,
    CAST(CREATEDON AS timestamp) AS CREATEDON,
    CAST(DBT_UPDATED_AT AS timestamp) AS DBT_UPDATED_AT
FROM cte_OSUSR_2DA_SUPPORTSTRUCTURE A
WHERE rnk = 1;