WITH BASE_DATA AS (

    SELECT DISTINCT
        CAST(CURRENT_DATE AS DATE)                       AS EXTRACT_DATE,
        APP.ID                                           AS ID_APPLICATION,
        APP.REFERENCENUMBER                              AS APPLICATION_NO,
        AMT.AMENDMENTREQUESTID                           AS ID_AMENDMENT,
        APP_STA.LABEL                                    AS WORKFLOW_STATUS,
        ASSESSMENTSTATUS.LABEL                           AS WORKFLOW_STATUS_ASSESSMENT,
        APPSUPWFS.LABEL                                  AS SUPPORT_DECISION,
        PROGVER.COMMERCIALNAME_EN                        AS PROGRAM_NAME,
        APP.SUBMITTEDON                                  AS SUBMITTED_ON_APPLICATION,
        APP.APPROVEDON                                   AS APPROVED_ON_APPLICATION,
        CASE
            WHEN APP.STARTON = TIMESTAMP '1900-01-01 00:00:00.000' THEN NULL
            ELSE CAST(APP.STARTON AS DATE)
        END                                              AS CONTRACT_START_DATE_APPLICATION,
        CASE
            WHEN APP.ENDON = TIMESTAMP '1900-01-01 00:00:00.000' THEN NULL
            ELSE CAST(APP.ENDON AS DATE)
        END                                              AS CONTRACT_END_DATE_APPLICATION,
        -- APP.APPROVALLETTERACCEPTEDON                     AS APPROVAL_LETTER_ACCEPTED_ON_APPLICATION,
        CAST(NULL AS VARCHAR)                           AS APPROVAL_LETTER_ACCEPTED_ON_APPLICATION,
        UPPER(LTRIM(RTRIM(CUS.NAMEEN)))                  AS FULL_NAME_CUSTOMER,
        CUSINDAPP.CPRNUMBER                              AS CPR,
        AUTHTRA.NAME                                    AS TRAINING_PROVIDER_NAME,
        TRAININGPROGRAM.NAME                            AS TRAINING_NAME,
        TRAININGTYPE.LABEL                              AS TRAINING_PROGRAM_TYPE,
        PAYTYPE.LABEL                                   AS TRAINING_PAYMENT_TYPE,
        CASE
            WHEN TRA.PAYEETYPEID = 'CST' THEN 'Customer'
            WHEN TRA.PAYEETYPEID = 'TP'  THEN 'Training Provider'
            ELSE NULL
        END                                              AS PAYEE,
        TRA.TRAININGSTARTDATE                            AS TRAINING_START_DATE,
        TRA.TRAININGENDDATE                              AS TRAINING_END_DATE,
        TRA.TRAININGASSESSMENTDATE                       AS TRAINING_ASSESSMENT_DATE,
        TRA.ITEMCOSTTOTAL                               AS CERTIFICATION_CAP_AMOUNT_BHD,
        TRA.ITEMCAPAMT                                  AS TAMKEEN_CAP_AMOUNT_BHD,
        TRA.TKSHAREAMT                                  AS TAMKEEN_SHARE_AMOUNT_BHD,
        (TRA.TKSHAREACTUALPCT * 100)                     AS TAMKEEN_SHARE_PERCENT,
        (100 - (TRA.TKSHAREACTUALPCT * 100))             AS CUSTOMER_SHARE_PERCENT,
        TRA.CUSTOMERSHARE                               AS CUSTOMER_SHARE_AMOUNT_WITH_VAT_BHD,
        CASE
            WHEN TRA.ITEMCAPAMT = 0 THEN NULL
            WHEN TRA.ITEMAMTCLAIMED    > 0 THEN TRA.ITEMCAPAMT - TRA.ITEMAMTCLAIMED
            WHEN TRA.ITEMAMTAVAILABLE  > 0 THEN TRA.ITEMCAPAMT - TRA.ITEMAMTAVAILABLE
            WHEN TRA.ITEMAMTINPROGRESS > 0 THEN TRA.ITEMCAPAMT - TRA.ITEMAMTINPROGRESS
            ELSE NULL
        END                                              AS UNUTILIZED_AMOUNT_BHD,
        TRA.ITEMVATAMT                                  AS TOTAL_VAT_AMOUNT_BHD,
        -- CASE
        --     WHEN APPSUPEXT.TKSHARETOTALAMT = 0 THEN NULL
        --     ELSE ROUND(APPSUPEXT.TKSHARETOTALAMT, 3)
        -- END                                              AS EFFECTIVE_TAMKEEN_SHARE_AMOUNT_BHD,
        TRA.CERTIFICATIONID,
        TRA.TRAININGDELIVERYTYPEID,
        TRA.ITEMAMTAVAILABLE,
        TRA.ITEMAMTINPROGRESS,
        TRA.CUSTOMERSHARETOTAL,
        TRA.TRAININGPAYMENTTYPEID,
        TRA.TKSHAREAMTAUTO,
        TRA.PAYEETYPEID,
        TRAININGPROGRAM.AUTHORIZEDPROVIDERID,
        TRAININGPROGRAM.OVERVIEW,
        TRAININGPROGRAM.AWARDINGBODYNAME,
        TRAININGPROGRAM.TRAININGPROGAMSTATUSID,
        TRAININGPROGRAM.ESTIMATEDTRAININGCOST,
        TRAININGPROGRAM.TRAININGHOURS,
        TRAININGPROGRAM.TRAININGKNOWLEDGEAREAID,
        TRAININGPROGRAM.TRAININGDETAILAREAID,
        TRAININGPROGRAM.INPUTCAPAMOUNT,
        TRAININGPROGRAM.CERTIFICATEID,
        TRAININGPROGRAM.TRAININGPROGRAMTYPEID,
        TRAININGPROGRAM.TRAININGTYPEID,
        TRAININGPROGRAM.APPLICANTSEGMENTID,
        TRAININGPROGRAM.ISMOLRELATED,
        TRAININGPROGRAM.ISEXEMPTED,
        TRAININGPROGRAM.ISALLOWPAPER,
        TRAININGPROGRAM.TRAINING_SUPPORTTYPE,
        TRAININGPROGRAM.ISSUBMITTEDINAPP,
        CAST(current_timestamp AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT

    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_APPLICATIONSUPPORT APPSUP
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION APP
        ON APP.ID = APPSUP.APPLICATIONID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_1AT_ASSESSMENT AMT
        ON AMT.APPLICATIONID = APP.ID
        AND APP.ISACTIVE = TRUE
    INNER JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATIONCUSTOMER APPCUS
        ON APP.ID = APPCUS.APPLICATIONID
    INNER JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMERPROFILE CUSPROF
        ON CUSPROF.ID = APPCUS.CUSTOMERPROFILEID
    INNER JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMER CUS
        ON CUSPROF.CUSTOMERID = CUS.ID
    INNER JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_VW9_TRAINING TRA
        ON TRA.APPLICATIONSUPPORTID = APPSUP.ID
    INNER JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_VW9_CERTIFICATION TRACERTIF
        ON TRACERTIF.ID = TRA.CERTIFICATIONID
    INNER JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_R9T_TRAININGPROGRAM TRAININGPROGRAM
        ON TRACERTIF.TRAININGPROGRAMID = TRAININGPROGRAM.ID
    INNER JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_TRAININGTYPE TRAININGTYPE
        ON TRAININGTYPE."ORDER" = TRAININGPROGRAM.TRAININGTYPEID
    INNER JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_INDIVIDUAL CUSINDAPP
        ON APPSUP.INDIVIDUALID = CUSINDAPP.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_GUR_AUTHORIZEDENTITIES AUTHTRA
        ON TRAININGPROGRAM.AUTHORIZEDPROVIDERID = AUTHTRA.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_PROGRAMVERSION PROGVER
        ON PROGVER.ID = APP.PROGRAMVERSIONID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_PROGRAM PROGRAM
        ON PROGVER.PROGRAMID = PROGRAM.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_VW9_TRAININGPAYMENTTYPE PAYTYPE
        ON PAYTYPE.CODE = TRA.TRAININGPAYMENTTYPEID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_398_APPLICATIONSTATUS APP_STA
        ON APP_STA.CODE = APP.APPLICATIONSTATUSID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_APPLICATIONSUPPORTSTATUS APPSUPWFS
        ON APPSUPWFS.CODE = APPSUP.APPLICATIONSUPPORTSTATUSID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_1AT_ASSESSMENTSTATUS ASSESSMENTSTATUS
        ON AMT.ASSESSMENTSTATUSID = ASSESSMENTSTATUS.CODE

    WHERE PROGRAM.PROFILETYPEID = 'IND'
      AND APPSUP.ISACTIVE = TRUE
      AND APP.ISACTIVE = TRUE
      AND (
            (APPSUP.ACTIVESTATUSID = 'INA'
             AND APPSUP.APPLICATIONSUPPORTSTATUSID = 'REM')
         OR APPSUP.ACTIVESTATUSID = 'ACT'
      )

)

SELECT *
FROM BASE_DATA