WITH cte_analysis_form AS (

    SELECT
        CAST(date_add('hour', 3, current_timestamp) AS DATE)      AS EXTRACT_DATE,
        APP.ID AS ID_APPLICATION,
        APP.GUID AS ID_GUID,
        APP.REFERENCENUMBER AS APPLICATION_NO,
        FIELD.NAME AS QUESTION,
        FIELDVALUE.VALUETEXT AS ANSWER_TEXT,
        FIELDVALUE.VALUEBOOLEAN AS ANSWER_BOOLEAN,
        FIELDVALUE.VALUEDATE AS ANSWER_DATE,
        FIELDVALUE.VALUENUMBER AS ANSWER_NUMBER,
        FIELD.CODE AS FIELD_CODE,
        SECTION.ID AS ID_SECTION,
        SECTION.FORMID AS FORMID_SECTION,
        SECTION.NAME AS NAME_SECTION,
        SECTION.DESCRIPTION AS DESCRIPTION_SECTION,
        SECTION.ISVISIBLE AS ISVISIBLE_SECTION,
        SECTION.WEIGHT AS WEIGHT_SECTION,

        SECFIELD.ID AS ID_SECFIELD,
        SECFIELD.SECTIONID AS SECTIONID_SECFIELD,
        SECFIELD.FIELDID AS FIELDID_SECFIELD,
        SECFIELD.ROWPOSITION,
        SECFIELD.COLUMNPOSITION,
        SECFIELD.NUMBERCOLUMNS,
        SECFIELD.ISVISIBLE AS ISVISIBLE_SECFIELD,
        SECFIELD.ISENABLED AS ISENABLED_SECFIELD,
        SECFIELD.ISMANDATORY AS ISMANDATORY_SECFIELD,
        SECFIELD.WEIGHT AS WEIGHT_SECFIELD,
        SECFIELD.HASMANUALVERIFICATION,

        FORMINST.ID AS ID_FORMINST,
        FORMINST.FORMID AS FORMID_FORMINST,
        FORMINST.ISVALID AS ISVALID_FORMINST,

        FORM.ID AS ID_FORM,
        FORM.DOMAINID AS DOMAINID_FORM,
        FORM.NAME AS NAME_FORM,
        FORM.DESCRIPTION AS DESCRIPTION_FORM,
        FORM.BASEURL,
        FORM.URLPATH,
        FORM.ISACTIVE AS ISACTIVE_FORM,

        FIELDVALUE.ISVALID AS ISVALID_FIELDVALUE,
        FIELDVALUE.ISMANUALVERIFIED AS ISMANUALVERIFIED_FIELDVALUE,

        FIELD.ID AS ID_FIELD,
        FIELD.ISACTIVE AS ISACTIVE_FIELD,
        FIELD.DOMAINID AS DOMAINID_FIELD,
        FIELD.DATATYPEID,
        FIELD.FIELDINPUTTYPEID,
        FIELD.DESCRIPTION AS DESCRIPTION_FIELD,
        FIELD.REGEX,
        FIELD.DEFAULTTEXT,
        FIELD.MINIMUMTEXTLENGTH,
        FIELD.MAXIMUMTEXTLENGTH,
        FIELD.DEFAULTDATE,
        FIELD.MINIMUMDATE,
        FIELD.MAXIMUMDATE,
        FIELD.GROUPSEPARATOR,
        FIELD.DECIMALSEPARATOR,
        FIELD.DECIMALPLACES,
        FIELD.DEFAULTNUMBER,
        FIELD.MINIMUMNUMBER,
        FIELD.MAXIMUMNUMBER,
        FIELD.EXPRESSION
        --'ANALYSIS' AS FORM_TYPE

    FROM  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION AS APP
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORMINSTANCE AS FORMINST 
        ON FORMINST.GUID = APP.ANALYSISINSTANCEFORMGUID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORM AS FORM 
        ON FORM.ID = FORMINST.FORMID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTION AS SECTION 
        ON SECTION.FORMID= FORM.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTIONFIELD AS SECFIELD 
        ON SECFIELD.SECTIONID = SECTION.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELD AS FIELD 
        ON FIELD.ID = SECFIELD.FIELDID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELDVALUE AS FIELDVALUE 
        ON FIELDVALUE.FORMINSTANCEID = FORMINST.ID 
        AND FIELDVALUE.SECTIONFIELDID = SECFIELD.ID

),

cte_application_form AS (

    SELECT
        CAST(date_add('hour', 3, current_timestamp) AS DATE)      AS EXTRACT_DATE,
        APP.ID AS ID_APPLICATION,
        APP.GUID AS ID_GUID,
        APP.REFERENCENUMBER AS APPLICATION_NO,
        FIELD.NAME AS QUESTION,
        FIELDVALUE.VALUETEXT AS ANSWER_TEXT,
        FIELDVALUE.VALUEBOOLEAN AS ANSWER_BOOLEAN,
        FIELDVALUE.VALUEDATE AS ANSWER_DATE,
        FIELDVALUE.VALUENUMBER AS ANSWER_NUMBER,
        FIELD.CODE AS FIELD_CODE,
        SECTION.ID AS ID_SECTION,
        SECTION.FORMID AS FORMID_SECTION,
        SECTION.NAME AS NAME_SECTION,
        SECTION.DESCRIPTION AS DESCRIPTION_SECTION,
        SECTION.ISVISIBLE AS ISVISIBLE_SECTION,
        SECTION.WEIGHT AS WEIGHT_SECTION,

        SECFIELD.ID AS ID_SECFIELD,
        SECFIELD.SECTIONID AS SECTIONID_SECFIELD,
        SECFIELD.FIELDID AS FIELDID_SECFIELD,
        SECFIELD.ROWPOSITION,
        SECFIELD.COLUMNPOSITION,
        SECFIELD.NUMBERCOLUMNS,
        SECFIELD.ISVISIBLE AS ISVISIBLE_SECFIELD,
        SECFIELD.ISENABLED AS ISENABLED_SECFIELD,
        SECFIELD.ISMANDATORY AS ISMANDATORY_SECFIELD,
        SECFIELD.WEIGHT AS WEIGHT_SECFIELD,
        SECFIELD.HASMANUALVERIFICATION,

        FORMINST.ID AS ID_FORMINST,
        FORMINST.FORMID AS FORMID_FORMINST,
        FORMINST.ISVALID AS ISVALID_FORMINST,

        FORM.ID AS ID_FORM,
        FORM.DOMAINID AS DOMAINID_FORM,
        FORM.NAME AS NAME_FORM,
        FORM.DESCRIPTION AS DESCRIPTION_FORM,
        FORM.BASEURL,
        FORM.URLPATH,
        FORM.ISACTIVE AS ISACTIVE_FORM,

        FIELDVALUE.ISVALID AS ISVALID_FIELDVALUE,
        FIELDVALUE.ISMANUALVERIFIED AS ISMANUALVERIFIED_FIELDVALUE,

        FIELD.ID AS ID_FIELD,
        FIELD.ISACTIVE AS ISACTIVE_FIELD,
        FIELD.DOMAINID AS DOMAINID_FIELD,
        FIELD.DATATYPEID,
        FIELD.FIELDINPUTTYPEID,
        FIELD.DESCRIPTION AS DESCRIPTION_FIELD,
        FIELD.REGEX,
        FIELD.DEFAULTTEXT,
        FIELD.MINIMUMTEXTLENGTH,
        FIELD.MAXIMUMTEXTLENGTH,
        FIELD.DEFAULTDATE,
        FIELD.MINIMUMDATE,
        FIELD.MAXIMUMDATE,
        FIELD.GROUPSEPARATOR,
        FIELD.DECIMALSEPARATOR,
        FIELD.DECIMALPLACES,
        FIELD.DEFAULTNUMBER,
        FIELD.MINIMUMNUMBER,
        FIELD.MAXIMUMNUMBER,
        FIELD.EXPRESSION
        --'APPLICATION' AS FORM_TYPE

    FROM  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION AS APP
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORMINSTANCE AS FORMINST 
        ON FORMINST.GUID = APP.APPLICATIONINSTANCEFORMGUID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORM AS FORM 
        ON FORM.ID = FORMINST.FORMID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTION AS SECTION 
        ON SECTION.FORMID= FORM.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTIONFIELD AS SECFIELD 
        ON SECFIELD.SECTIONID = SECTION.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELD AS FIELD 
        ON FIELD.ID = SECFIELD.FIELDID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELDVALUE AS FIELDVALUE 
        ON FIELDVALUE.FORMINSTANCEID = FORMINST.ID 
        AND FIELDVALUE.SECTIONFIELDID = SECFIELD.ID

),

cte_customer_form AS (

    SELECT
        CAST(date_add('hour', 3, current_timestamp) AS DATE)      AS EXTRACT_DATE,
        APP.ID AS ID_APPLICATION,
        APP.GUID AS ID_GUID,
        APP.REFERENCENUMBER AS APPLICATION_NO,
        FIELD.NAME AS QUESTION,
        FIELDVALUE.VALUETEXT AS ANSWER_TEXT,
        FIELDVALUE.VALUEBOOLEAN AS ANSWER_BOOLEAN,
        FIELDVALUE.VALUEDATE AS ANSWER_DATE,
        FIELDVALUE.VALUENUMBER AS ANSWER_NUMBER,
        FIELD.CODE AS FIELD_CODE,
        SECTION.ID AS ID_SECTION,
        SECTION.FORMID AS FORMID_SECTION,
        SECTION.NAME AS NAME_SECTION,
        SECTION.DESCRIPTION AS DESCRIPTION_SECTION,
        SECTION.ISVISIBLE AS ISVISIBLE_SECTION,
        SECTION.WEIGHT AS WEIGHT_SECTION,

        SECFIELD.ID AS ID_SECFIELD,
        SECFIELD.SECTIONID AS SECTIONID_SECFIELD,
        SECFIELD.FIELDID AS FIELDID_SECFIELD,
        SECFIELD.ROWPOSITION,
        SECFIELD.COLUMNPOSITION,
        SECFIELD.NUMBERCOLUMNS,
        SECFIELD.ISVISIBLE AS ISVISIBLE_SECFIELD,
        SECFIELD.ISENABLED AS ISENABLED_SECFIELD,
        SECFIELD.ISMANDATORY AS ISMANDATORY_SECFIELD,
        SECFIELD.WEIGHT AS WEIGHT_SECFIELD,
        SECFIELD.HASMANUALVERIFICATION,

        FORMINST.ID AS ID_FORMINST,
        FORMINST.FORMID AS FORMID_FORMINST,
        FORMINST.ISVALID AS ISVALID_FORMINST,

        FORM.ID AS ID_FORM,
        FORM.DOMAINID AS DOMAINID_FORM,
        FORM.NAME AS NAME_FORM,
        FORM.DESCRIPTION AS DESCRIPTION_FORM,
        FORM.BASEURL,
        FORM.URLPATH,
        FORM.ISACTIVE AS ISACTIVE_FORM,

        FIELDVALUE.ISVALID AS ISVALID_FIELDVALUE,
        FIELDVALUE.ISMANUALVERIFIED AS ISMANUALVERIFIED_FIELDVALUE,

        FIELD.ID AS ID_FIELD,
        FIELD.ISACTIVE AS ISACTIVE_FIELD,
        FIELD.DOMAINID AS DOMAINID_FIELD,
        FIELD.DATATYPEID,
        FIELD.FIELDINPUTTYPEID,
        FIELD.DESCRIPTION AS DESCRIPTION_FIELD,
        FIELD.REGEX,
        FIELD.DEFAULTTEXT,
        FIELD.MINIMUMTEXTLENGTH,
        FIELD.MAXIMUMTEXTLENGTH,
        FIELD.DEFAULTDATE,
        FIELD.MINIMUMDATE,
        FIELD.MAXIMUMDATE,
        FIELD.GROUPSEPARATOR,
        FIELD.DECIMALSEPARATOR,
        FIELD.DECIMALPLACES,
        FIELD.DEFAULTNUMBER,
        FIELD.MINIMUMNUMBER,
        FIELD.MAXIMUMNUMBER,
        FIELD.EXPRESSION
    FROM  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION AS APP
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORMINSTANCE AS FORMINST 
        ON FORMINST.GUID = APP.CUSTOMERINSTANCEFORMGUID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORM AS FORM 
        ON FORM.ID = FORMINST.FORMID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTION AS SECTION 
        ON SECTION.FORMID= FORM.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTIONFIELD AS SECFIELD 
        ON SECFIELD.SECTIONID = SECTION.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELD AS FIELD 
        ON FIELD.ID = SECFIELD.FIELDID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELDVALUE AS FIELDVALUE 
        ON FIELDVALUE.FORMINSTANCEID = FORMINST.ID 
        AND FIELDVALUE.SECTIONFIELDID = SECFIELD.ID

),

cte_evc_form AS (

    SELECT
        CAST(date_add('hour', 3, current_timestamp) AS DATE)      AS EXTRACT_DATE,
        APP.ID AS ID_APPLICATION,
        APP.GUID AS ID_GUID,
        APP.REFERENCENUMBER AS APPLICATION_NO,
        FIELD.NAME AS QUESTION,
        FIELDVALUE.VALUETEXT AS ANSWER_TEXT,
        FIELDVALUE.VALUEBOOLEAN AS ANSWER_BOOLEAN,
        FIELDVALUE.VALUEDATE AS ANSWER_DATE,
        FIELDVALUE.VALUENUMBER AS ANSWER_NUMBER,
        FIELD.CODE AS FIELD_CODE,
        SECTION.ID AS ID_SECTION,
        SECTION.FORMID AS FORMID_SECTION,
        SECTION.NAME AS NAME_SECTION,
        SECTION.DESCRIPTION AS DESCRIPTION_SECTION,
        SECTION.ISVISIBLE AS ISVISIBLE_SECTION,
        SECTION.WEIGHT AS WEIGHT_SECTION,

        SECFIELD.ID AS ID_SECFIELD,
        SECFIELD.SECTIONID AS SECTIONID_SECFIELD,
        SECFIELD.FIELDID AS FIELDID_SECFIELD,
        SECFIELD.ROWPOSITION,
        SECFIELD.COLUMNPOSITION,
        SECFIELD.NUMBERCOLUMNS,
        SECFIELD.ISVISIBLE AS ISVISIBLE_SECFIELD,
        SECFIELD.ISENABLED AS ISENABLED_SECFIELD,
        SECFIELD.ISMANDATORY AS ISMANDATORY_SECFIELD,
        SECFIELD.WEIGHT AS WEIGHT_SECFIELD,
        SECFIELD.HASMANUALVERIFICATION,

        FORMINST.ID AS ID_FORMINST,
        FORMINST.FORMID AS FORMID_FORMINST,
        FORMINST.ISVALID AS ISVALID_FORMINST,

        FORM.ID AS ID_FORM,
        FORM.DOMAINID AS DOMAINID_FORM,
        FORM.NAME AS NAME_FORM,
        FORM.DESCRIPTION AS DESCRIPTION_FORM,
        FORM.BASEURL,
        FORM.URLPATH,
        FORM.ISACTIVE AS ISACTIVE_FORM,

        FIELDVALUE.ISVALID AS ISVALID_FIELDVALUE,
        FIELDVALUE.ISMANUALVERIFIED AS ISMANUALVERIFIED_FIELDVALUE,

        FIELD.ID AS ID_FIELD,
        FIELD.ISACTIVE AS ISACTIVE_FIELD,
        FIELD.DOMAINID AS DOMAINID_FIELD,
        FIELD.DATATYPEID,
        FIELD.FIELDINPUTTYPEID,
        FIELD.DESCRIPTION AS DESCRIPTION_FIELD,
        FIELD.REGEX,
        FIELD.DEFAULTTEXT,
        FIELD.MINIMUMTEXTLENGTH,
        FIELD.MAXIMUMTEXTLENGTH,
        FIELD.DEFAULTDATE,
        FIELD.MINIMUMDATE,
        FIELD.MAXIMUMDATE,
        FIELD.GROUPSEPARATOR,
        FIELD.DECIMALSEPARATOR,
        FIELD.DECIMALPLACES,
        FIELD.DEFAULTNUMBER,
        FIELD.MINIMUMNUMBER,
        FIELD.MAXIMUMNUMBER,
        FIELD.EXPRESSION
        --'EVC' AS FORM_TYPE

    FROM  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION AS APP
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORMINSTANCE AS FORMINST 
        ON FORMINST.GUID = APP.EVCINSTANCEFORMGUID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORM AS FORM 
        ON FORM.ID = FORMINST.FORMID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTION AS SECTION 
        ON SECTION.FORMID= FORM.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTIONFIELD AS SECFIELD 
        ON SECFIELD.SECTIONID = SECTION.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELD AS FIELD 
        ON FIELD.ID = SECFIELD.FIELDID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELDVALUE AS FIELDVALUE 
        ON FIELDVALUE.FORMINSTANCEID = FORMINST.ID 
        AND FIELDVALUE.SECTIONFIELDID = SECFIELD.ID

),

cte_findata_form AS (

    SELECT
        CAST(date_add('hour', 3, current_timestamp) AS DATE)      AS EXTRACT_DATE,
        APP.ID AS ID_APPLICATION,
        APP.GUID AS ID_GUID,
        APP.REFERENCENUMBER AS APPLICATION_NO,
        FIELD.NAME AS QUESTION,
        FIELDVALUE.VALUETEXT AS ANSWER_TEXT,
        FIELDVALUE.VALUEBOOLEAN AS ANSWER_BOOLEAN,
        FIELDVALUE.VALUEDATE AS ANSWER_DATE,
        FIELDVALUE.VALUENUMBER AS ANSWER_NUMBER,
        FIELD.CODE AS FIELD_CODE,
        SECTION.ID AS ID_SECTION,
        SECTION.FORMID AS FORMID_SECTION,
        SECTION.NAME AS NAME_SECTION,
        SECTION.DESCRIPTION AS DESCRIPTION_SECTION,
        SECTION.ISVISIBLE AS ISVISIBLE_SECTION,
        SECTION.WEIGHT AS WEIGHT_SECTION,

        SECFIELD.ID AS ID_SECFIELD,
        SECFIELD.SECTIONID AS SECTIONID_SECFIELD,
        SECFIELD.FIELDID AS FIELDID_SECFIELD,
        SECFIELD.ROWPOSITION,
        SECFIELD.COLUMNPOSITION,
        SECFIELD.NUMBERCOLUMNS,
        SECFIELD.ISVISIBLE AS ISVISIBLE_SECFIELD,
        SECFIELD.ISENABLED AS ISENABLED_SECFIELD,
        SECFIELD.ISMANDATORY AS ISMANDATORY_SECFIELD,
        SECFIELD.WEIGHT AS WEIGHT_SECFIELD,
        SECFIELD.HASMANUALVERIFICATION,

        FORMINST.ID AS ID_FORMINST,
        FORMINST.FORMID AS FORMID_FORMINST,
        FORMINST.ISVALID AS ISVALID_FORMINST,

        FORM.ID AS ID_FORM,
        FORM.DOMAINID AS DOMAINID_FORM,
        FORM.NAME AS NAME_FORM,
        FORM.DESCRIPTION AS DESCRIPTION_FORM,
        FORM.BASEURL,
        FORM.URLPATH,
        FORM.ISACTIVE AS ISACTIVE_FORM,

        FIELDVALUE.ISVALID AS ISVALID_FIELDVALUE,
        FIELDVALUE.ISMANUALVERIFIED AS ISMANUALVERIFIED_FIELDVALUE,

        FIELD.ID AS ID_FIELD,
        FIELD.ISACTIVE AS ISACTIVE_FIELD,
        FIELD.DOMAINID AS DOMAINID_FIELD,
        FIELD.DATATYPEID,
        FIELD.FIELDINPUTTYPEID,
        FIELD.DESCRIPTION AS DESCRIPTION_FIELD,
        FIELD.REGEX,
        FIELD.DEFAULTTEXT,
        FIELD.MINIMUMTEXTLENGTH,
        FIELD.MAXIMUMTEXTLENGTH,
        FIELD.DEFAULTDATE,
        FIELD.MINIMUMDATE,
        FIELD.MAXIMUMDATE,
        FIELD.GROUPSEPARATOR,
        FIELD.DECIMALSEPARATOR,
        FIELD.DECIMALPLACES,
        FIELD.DEFAULTNUMBER,
        FIELD.MINIMUMNUMBER,
        FIELD.MAXIMUMNUMBER,
        FIELD.EXPRESSION
        --'FINDATA' AS FORM_TYPE

    FROM  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION AS APP
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORMINSTANCE AS FORMINST 
        ON FORMINST.GUID = APP.FINDATAINSTANCEFORMGUID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORM AS FORM 
        ON FORM.ID = FORMINST.FORMID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTION AS SECTION 
        ON SECTION.FORMID= FORM.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTIONFIELD AS SECFIELD 
        ON SECFIELD.SECTIONID = SECTION.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELD AS FIELD 
        ON FIELD.ID = SECFIELD.FIELDID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELDVALUE AS FIELDVALUE 
        ON FIELDVALUE.FORMINSTANCEID = FORMINST.ID 
        AND FIELDVALUE.SECTIONFIELDID = SECFIELD.ID

),

cte_grantcalc_form AS (

    SELECT
        CAST(date_add('hour', 3, current_timestamp) AS DATE)      AS EXTRACT_DATE,
        APP.ID AS ID_APPLICATION,
        APP.GUID AS ID_GUID,
        APP.REFERENCENUMBER AS APPLICATION_NO,
        FIELD.NAME AS QUESTION,
        FIELDVALUE.VALUETEXT AS ANSWER_TEXT,
        FIELDVALUE.VALUEBOOLEAN AS ANSWER_BOOLEAN,
        FIELDVALUE.VALUEDATE AS ANSWER_DATE,
        FIELDVALUE.VALUENUMBER AS ANSWER_NUMBER,
        FIELD.CODE AS FIELD_CODE,
        SECTION.ID AS ID_SECTION,
        SECTION.FORMID AS FORMID_SECTION,
        SECTION.NAME AS NAME_SECTION,
        SECTION.DESCRIPTION AS DESCRIPTION_SECTION,
        SECTION.ISVISIBLE AS ISVISIBLE_SECTION,
        SECTION.WEIGHT AS WEIGHT_SECTION,

        SECFIELD.ID AS ID_SECFIELD,
        SECFIELD.SECTIONID AS SECTIONID_SECFIELD,
        SECFIELD.FIELDID AS FIELDID_SECFIELD,
        SECFIELD.ROWPOSITION,
        SECFIELD.COLUMNPOSITION,
        SECFIELD.NUMBERCOLUMNS,
        SECFIELD.ISVISIBLE AS ISVISIBLE_SECFIELD,
        SECFIELD.ISENABLED AS ISENABLED_SECFIELD,
        SECFIELD.ISMANDATORY AS ISMANDATORY_SECFIELD,
        SECFIELD.WEIGHT AS WEIGHT_SECFIELD,
        SECFIELD.HASMANUALVERIFICATION,

        FORMINST.ID AS ID_FORMINST,
        FORMINST.FORMID AS FORMID_FORMINST,
        FORMINST.ISVALID AS ISVALID_FORMINST,

        FORM.ID AS ID_FORM,
        FORM.DOMAINID AS DOMAINID_FORM,
        FORM.NAME AS NAME_FORM,
        FORM.DESCRIPTION AS DESCRIPTION_FORM,
        FORM.BASEURL,
        FORM.URLPATH,
        FORM.ISACTIVE AS ISACTIVE_FORM,

        FIELDVALUE.ISVALID AS ISVALID_FIELDVALUE,
        FIELDVALUE.ISMANUALVERIFIED AS ISMANUALVERIFIED_FIELDVALUE,

        FIELD.ID AS ID_FIELD,
        FIELD.ISACTIVE AS ISACTIVE_FIELD,
        FIELD.DOMAINID AS DOMAINID_FIELD,
        FIELD.DATATYPEID,
        FIELD.FIELDINPUTTYPEID,
        FIELD.DESCRIPTION AS DESCRIPTION_FIELD,
        FIELD.REGEX,
        FIELD.DEFAULTTEXT,
        FIELD.MINIMUMTEXTLENGTH,
        FIELD.MAXIMUMTEXTLENGTH,
        FIELD.DEFAULTDATE,
        FIELD.MINIMUMDATE,
        FIELD.MAXIMUMDATE,
        FIELD.GROUPSEPARATOR,
        FIELD.DECIMALSEPARATOR,
        FIELD.DECIMALPLACES,
        FIELD.DEFAULTNUMBER,
        FIELD.MINIMUMNUMBER,
        FIELD.MAXIMUMNUMBER,
        FIELD.EXPRESSION
        --'GRANTCALC' AS FORM_TYPE

    FROM  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION AS APP
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORMINSTANCE AS FORMINST 
        ON FORMINST.GUID = APP.GRANTCALCINSTANCEFORMGUID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORM AS FORM 
        ON FORM.ID = FORMINST.FORMID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTION AS SECTION 
        ON SECTION.FORMID= FORM.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTIONFIELD AS SECFIELD 
        ON SECFIELD.SECTIONID = SECTION.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELD AS FIELD 
        ON FIELD.ID = SECFIELD.FIELDID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELDVALUE AS FIELDVALUE 
        ON FIELDVALUE.FORMINSTANCEID = FORMINST.ID 
        AND FIELDVALUE.SECTIONFIELDID = SECFIELD.ID

),

cte_hipo_form AS (

    SELECT
        CAST(date_add('hour', 3, current_timestamp) AS DATE)      AS EXTRACT_DATE,
        APP.ID AS ID_APPLICATION,
        APP.GUID AS ID_GUID,
        APP.REFERENCENUMBER AS APPLICATION_NO,
        FIELD.NAME AS QUESTION,
        FIELDVALUE.VALUETEXT AS ANSWER_TEXT,
        FIELDVALUE.VALUEBOOLEAN AS ANSWER_BOOLEAN,
        FIELDVALUE.VALUEDATE AS ANSWER_DATE,
        FIELDVALUE.VALUENUMBER AS ANSWER_NUMBER,
        FIELD.CODE AS FIELD_CODE,
        SECTION.ID AS ID_SECTION,
        SECTION.FORMID AS FORMID_SECTION,
        SECTION.NAME AS NAME_SECTION,
        SECTION.DESCRIPTION AS DESCRIPTION_SECTION,
        SECTION.ISVISIBLE AS ISVISIBLE_SECTION,
        SECTION.WEIGHT AS WEIGHT_SECTION,

        SECFIELD.ID AS ID_SECFIELD,
        SECFIELD.SECTIONID AS SECTIONID_SECFIELD,
        SECFIELD.FIELDID AS FIELDID_SECFIELD,
        SECFIELD.ROWPOSITION,
        SECFIELD.COLUMNPOSITION,
        SECFIELD.NUMBERCOLUMNS,
        SECFIELD.ISVISIBLE AS ISVISIBLE_SECFIELD,
        SECFIELD.ISENABLED AS ISENABLED_SECFIELD,
        SECFIELD.ISMANDATORY AS ISMANDATORY_SECFIELD,
        SECFIELD.WEIGHT AS WEIGHT_SECFIELD,
        SECFIELD.HASMANUALVERIFICATION,

        FORMINST.ID AS ID_FORMINST,
        FORMINST.FORMID AS FORMID_FORMINST,
        FORMINST.ISVALID AS ISVALID_FORMINST,

        FORM.ID AS ID_FORM,
        FORM.DOMAINID AS DOMAINID_FORM,
        FORM.NAME AS NAME_FORM,
        FORM.DESCRIPTION AS DESCRIPTION_FORM,
        FORM.BASEURL,
        FORM.URLPATH,
        FORM.ISACTIVE AS ISACTIVE_FORM,

        FIELDVALUE.ISVALID AS ISVALID_FIELDVALUE,
        FIELDVALUE.ISMANUALVERIFIED AS ISMANUALVERIFIED_FIELDVALUE,

        FIELD.ID AS ID_FIELD,
        FIELD.ISACTIVE AS ISACTIVE_FIELD,
        FIELD.DOMAINID AS DOMAINID_FIELD,
        FIELD.DATATYPEID,
        FIELD.FIELDINPUTTYPEID,
        FIELD.DESCRIPTION AS DESCRIPTION_FIELD,
        FIELD.REGEX,
        FIELD.DEFAULTTEXT,
        FIELD.MINIMUMTEXTLENGTH,
        FIELD.MAXIMUMTEXTLENGTH,
        FIELD.DEFAULTDATE,
        FIELD.MINIMUMDATE,
        FIELD.MAXIMUMDATE,
        FIELD.GROUPSEPARATOR,
        FIELD.DECIMALSEPARATOR,
        FIELD.DECIMALPLACES,
        FIELD.DEFAULTNUMBER,
        FIELD.MINIMUMNUMBER,
        FIELD.MAXIMUMNUMBER,
        FIELD.EXPRESSION
        --'HIPO' AS FORM_TYPE

    FROM  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION AS APP
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORMINSTANCE AS FORMINST 
        ON FORMINST.GUID = APP.HIPOINSTANCEFORMGUID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORM AS FORM 
        ON FORM.ID = FORMINST.FORMID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTION AS SECTION 
        ON SECTION.FORMID= FORM.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTIONFIELD AS SECFIELD 
        ON SECFIELD.SECTIONID = SECTION.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELD AS FIELD 
        ON FIELD.ID = SECFIELD.FIELDID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELDVALUE AS FIELDVALUE 
        ON FIELDVALUE.FORMINSTANCEID = FORMINST.ID 
        AND FIELDVALUE.SECTIONFIELDID = SECFIELD.ID

),

cte_profiling_form AS (

    SELECT
        CAST(date_add('hour', 3, current_timestamp) AS DATE)      AS EXTRACT_DATE,
        APP.ID AS ID_APPLICATION,
        APP.GUID AS ID_GUID,
        APP.REFERENCENUMBER AS APPLICATION_NO,
        FIELD.NAME AS QUESTION,
        FIELDVALUE.VALUETEXT AS ANSWER_TEXT,
        FIELDVALUE.VALUEBOOLEAN AS ANSWER_BOOLEAN,
        FIELDVALUE.VALUEDATE AS ANSWER_DATE,
        FIELDVALUE.VALUENUMBER AS ANSWER_NUMBER,
        FIELD.CODE AS FIELD_CODE,
        SECTION.ID AS ID_SECTION,
        SECTION.FORMID AS FORMID_SECTION,
        SECTION.NAME AS NAME_SECTION,
        SECTION.DESCRIPTION AS DESCRIPTION_SECTION,
        SECTION.ISVISIBLE AS ISVISIBLE_SECTION,
        SECTION.WEIGHT AS WEIGHT_SECTION,

        SECFIELD.ID AS ID_SECFIELD,
        SECFIELD.SECTIONID AS SECTIONID_SECFIELD,
        SECFIELD.FIELDID AS FIELDID_SECFIELD,
        SECFIELD.ROWPOSITION,
        SECFIELD.COLUMNPOSITION,
        SECFIELD.NUMBERCOLUMNS,
        SECFIELD.ISVISIBLE AS ISVISIBLE_SECFIELD,
        SECFIELD.ISENABLED AS ISENABLED_SECFIELD,
        SECFIELD.ISMANDATORY AS ISMANDATORY_SECFIELD,
        SECFIELD.WEIGHT AS WEIGHT_SECFIELD,
        SECFIELD.HASMANUALVERIFICATION,

        FORMINST.ID AS ID_FORMINST,
        FORMINST.FORMID AS FORMID_FORMINST,
        FORMINST.ISVALID AS ISVALID_FORMINST,

        FORM.ID AS ID_FORM,
        FORM.DOMAINID AS DOMAINID_FORM,
        FORM.NAME AS NAME_FORM,
        FORM.DESCRIPTION AS DESCRIPTION_FORM,
        FORM.BASEURL,
        FORM.URLPATH,
        FORM.ISACTIVE AS ISACTIVE_FORM,

        FIELDVALUE.ISVALID AS ISVALID_FIELDVALUE,
        FIELDVALUE.ISMANUALVERIFIED AS ISMANUALVERIFIED_FIELDVALUE,

        FIELD.ID AS ID_FIELD,
        FIELD.ISACTIVE AS ISACTIVE_FIELD,
        FIELD.DOMAINID AS DOMAINID_FIELD,
        FIELD.DATATYPEID,
        FIELD.FIELDINPUTTYPEID,
        FIELD.DESCRIPTION AS DESCRIPTION_FIELD,
        FIELD.REGEX,
        FIELD.DEFAULTTEXT,
        FIELD.MINIMUMTEXTLENGTH,
        FIELD.MAXIMUMTEXTLENGTH,
        FIELD.DEFAULTDATE,
        FIELD.MINIMUMDATE,
        FIELD.MAXIMUMDATE,
        FIELD.GROUPSEPARATOR,
        FIELD.DECIMALSEPARATOR,
        FIELD.DECIMALPLACES,
        FIELD.DEFAULTNUMBER,
        FIELD.MINIMUMNUMBER,
        FIELD.MAXIMUMNUMBER,
        FIELD.EXPRESSION
        --'PROFILING' AS FORM_TYPE

    FROM  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION AS APP
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORMINSTANCE AS FORMINST 
        ON FORMINST.GUID = APP.PROFILINGINSTANCEGUID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FORM AS FORM 
        ON FORM.ID = FORMINST.FORMID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTION AS SECTION 
        ON SECTION.FORMID= FORM.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_SECTIONFIELD AS SECFIELD 
        ON SECFIELD.SECTIONID = SECTION.ID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELD AS FIELD 
        ON FIELD.ID = SECFIELD.FIELDID
    INNER JOIN  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_QFS_FIELDVALUE AS FIELDVALUE 
        ON FIELDVALUE.FORMINSTANCEID = FORMINST.ID 
        AND FIELDVALUE.SECTIONFIELDID = SECFIELD.ID

),

cte_combined AS (

    SELECT * FROM cte_analysis_form
    UNION ALL
    SELECT * FROM cte_application_form
    UNION ALL
    SELECT * FROM cte_customer_form
    UNION ALL
    SELECT * FROM cte_evc_form
    UNION ALL
    SELECT * FROM cte_findata_form
    UNION ALL
    SELECT * FROM cte_grantcalc_form
    UNION ALL
    SELECT * FROM cte_hipo_form
    UNION ALL
    SELECT * FROM cte_profiling_form

),

cte_filtered AS (

    SELECT
        EXTRACT_DATE,
        ID_APPLICATION,
        ID_GUID,
        APPLICATION_NO,

        QUESTION,
        ANSWER_TEXT,
        ANSWER_BOOLEAN,
        ANSWER_DATE,
        ANSWER_NUMBER,
        FIELD_CODE,

        ID_SECTION,
        FORMID_SECTION,
        NAME_SECTION,
        DESCRIPTION_SECTION,
        ISVISIBLE_SECTION,
        WEIGHT_SECTION,

        ID_SECFIELD,
        SECTIONID_SECFIELD,
        FIELDID_SECFIELD,
        ROWPOSITION,
        COLUMNPOSITION,
        NUMBERCOLUMNS,
        ISVISIBLE_SECFIELD,
        ISENABLED_SECFIELD,
        ISMANDATORY_SECFIELD,
        WEIGHT_SECFIELD,
        HASMANUALVERIFICATION,

        ID_FORMINST,
        FORMID_FORMINST,
        ISVALID_FORMINST,

        ID_FORM,
        DOMAINID_FORM,
        NAME_FORM,
        DESCRIPTION_FORM,
        BASEURL,
        URLPATH,
        ISACTIVE_FORM,

        ISVALID_FIELDVALUE,
        ISMANUALVERIFIED_FIELDVALUE,

        ID_FIELD,
        ISACTIVE_FIELD,
        DOMAINID_FIELD,
        DATATYPEID,
        FIELDINPUTTYPEID,
        DESCRIPTION_FIELD,
        REGEX,
        DEFAULTTEXT,
        MINIMUMTEXTLENGTH,
        MAXIMUMTEXTLENGTH,
        DEFAULTDATE,
        MINIMUMDATE,
        MAXIMUMDATE,
        GROUPSEPARATOR,
        DECIMALSEPARATOR,
        DECIMALPLACES,
        DEFAULTNUMBER,
        MINIMUMNUMBER,
        MAXIMUMNUMBER,
        EXPRESSION,
		FALSE                                                   AS IS_DELETED,
        'Neo2'                                                  AS SOURCE_SYSTEM_NAME,
		CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS DBT_UPDATED_AT
        --BRONZE_CREATED_ON,
        --BRONZE_UPDATED_ON

    FROM cte_combined

    WHERE FIELD_CODE IN (
        'INT.ENT.17', 'INT.ENT.17-Old', 'INT.ENT.17-Old-Old',
        'INT.ENT.18', 'INT.ENT.18-Old', 'INT.ENT.18-Old-Old',
        'INT.ENT.19', 'INT.ENT.19-Old', 'INT.ENT.19-Old-Old',
        'INT.ENT.15', 'INT.ENT.15-Old', 'INT.ENT.15-Old-Old',
        'EXT.ENT.Sector', 'EXT.ENT.Sector-Old', 'EXT.ENT.Sector-Old-Old',
        'EXT.HC.WorkArrangement', 'EXT.HC.WorkArrangement-Old', 'EXT.HC.WorkArrangement-Old-Old',
        'EXT.ENT.InOperation', 'EXT.ENT.InOperation-Old', 'EXT.ENT.InOperation-Old-Old',
        'EXT.ENT.Sector.Other', 'EXT.ENT.Sector.Other-Old', 'EXT.ENT.Sector.Other-Old-Old',
        'AS.HIPO.SECTOR1', 'AS.HIPO.SECTOR1-Old', 'AS.HIPO.SECTOR1-Old-Old',
        'AS.HIPO.COMPANY', 'AS.HIPO.COMPANY-Old', 'AS.HIPO.COMPANY-Old-Old',
        'INT.ENT.Target.Date', 'INT.ENT.Target.Date-Old', 'INT.ENT.Target.Date-Old-Old',
        'INT.ENT.Scalable', 'INT.ENT.Scalable-Old', 'INT.ENT.Scalable-Old-Old',
        'INT.ENT.IPs', 'INT.ENT.IPs-Old', 'INT.ENT.IPs-Old-Old',
        'INT.ENT.Main.Obj', 'INT.ENT.Main.Obj-Old', 'INT.ENT.Main.Obj-Old-Old',
        'INT.ENT.Detailed.Obj', 'INT.ENT.Detailed.Obj-Old', 'INT.ENT.Detailed.Obj-Old-Old',
        'INT.ENT.Prod.Inno', 'INT.ENT.Prod.Inno-Old', 'INT.ENT.Prod.Inno-Old-Old',
        'INT.ENT.20', 'INT.ENT.20-Old', 'INT.ENT.20-Old-Old',
        'Profile02.a', 'Profile02.a-Old', 'Profile02.a-Old-Old',
        'Profile.NEP', 'Profile.NEP-Old', 'Profile.NEP-Old-Old'
    )

)

SELECT
		CAST(EXTRACT_DATE AS DATE) AS EXTRACT_DATE,
		CAST(ID_APPLICATION AS INTEGER) AS ID_APPLICATION,
		ID_GUID,
		APPLICATION_NO,
		QUESTION,
		ANSWER_TEXT,
		ANSWER_BOOLEAN,
		CAST(ANSWER_DATE AS TIMESTAMP) AS ANSWER_DATE,
		CAST(ANSWER_NUMBER AS INTEGER) AS ANSWER_NUMBER,
		FIELD_CODE,

		CAST(ID_SECTION AS INTEGER) AS ID_SECTION,
		CAST(FORMID_SECTION AS INTEGER) AS FORMID_SECTION,
		NAME_SECTION,
		DESCRIPTION_SECTION,
		ISVISIBLE_SECTION,
		CAST(WEIGHT_SECTION AS INTEGER) AS WEIGHT_SECTION,

		CAST(ID_SECFIELD AS INTEGER) AS ID_SECFIELD,
		CAST(SECTIONID_SECFIELD AS INTEGER) AS SECTIONID_SECFIELD,
		CAST(FIELDID_SECFIELD AS INTEGER) AS FIELDID_SECFIELD,
		CAST(ROWPOSITION AS INTEGER) AS ROWPOSITION,
		CAST(COLUMNPOSITION AS INTEGER) AS COLUMNPOSITION,
		CAST(NUMBERCOLUMNS AS INTEGER) AS NUMBERCOLUMNS,
		ISVISIBLE_SECFIELD,
		ISENABLED_SECFIELD,
		ISMANDATORY_SECFIELD,
		CAST(WEIGHT_SECFIELD AS INTEGER) AS WEIGHT_SECFIELD,
		HASMANUALVERIFICATION,

		CAST(ID_FORMINST AS INTEGER) AS ID_FORMINST,
		CAST(FORMID_FORMINST AS INTEGER) AS FORMID_FORMINST,
		ISVALID_FORMINST,

		CAST(ID_FORM AS INTEGER) AS ID_FORM,
		CAST(DOMAINID_FORM AS INTEGER) AS DOMAINID_FORM,
		NAME_FORM,
		DESCRIPTION_FORM,
		BASEURL,
		URLPATH,
		ISACTIVE_FORM,

		ISVALID_FIELDVALUE,
		ISMANUALVERIFIED_FIELDVALUE,

		CAST(ID_FIELD AS INTEGER) AS ID_FIELD,
		ISACTIVE_FIELD,
		CAST(DOMAINID_FIELD AS INTEGER) AS DOMAINID_FIELD,
		DATATYPEID,
		FIELDINPUTTYPEID,
		DESCRIPTION_FIELD,
		REGEX,
		DEFAULTTEXT,
		CAST(MINIMUMTEXTLENGTH AS INTEGER) AS MINIMUMTEXTLENGTH,
		CAST(MAXIMUMTEXTLENGTH AS INTEGER) AS MAXIMUMTEXTLENGTH,
		CAST(DEFAULTDATE AS TIMESTAMP) AS DEFAULTDATE,
		CAST(MINIMUMDATE AS TIMESTAMP) AS MINIMUMDATE,
		CAST(MAXIMUMDATE AS TIMESTAMP) AS MAXIMUMDATE,
		GROUPSEPARATOR,
		DECIMALSEPARATOR,
		CAST(DECIMALPLACES AS INTEGER) AS DECIMALPLACES,
		CAST(DEFAULTNUMBER AS INTEGER) AS DEFAULTNUMBER,
		CAST(MINIMUMNUMBER AS INTEGER) AS MINIMUMNUMBER,
		CAST(MAXIMUMNUMBER AS INTEGER) AS MAXIMUMNUMBER,
		EXPRESSION,

		IS_DELETED,
        UPPER(TRIM(SOURCE_SYSTEM_NAME))                AS SOURCE_SYSTEM_NAME,
		CAST(DBT_UPDATED_AT AS TIMESTAMP)                   AS DBT_UPDATED_AT

FROM cte_filtered
