WITH source_cte AS (
    SELECT
        a.APPLICATIONSUPPORTID,
        a.STARTDATE,
        a.ENDDATE,
        JL.CODE AS NEWJOBLEVELID,
        JL.LABEL AS NEWJOBLEVEL,
        a.NEWTITLE,
        a.NEWDEPARTMENT,
        a.NEWRESPONSABILITIES,
        a.REQUESTEDINCREMENTAMOUNT,
        a.NEWWAGE,
        a.REQUESTEDSTIPEND,
        C.COUNTRYNAME AS PLACEMENTLOCATION,
        a.HOSTORGANIZATIONNAME,
        a.PLACEMENTJOBTITLE,
        a.PLACEMENTJOBRESPONSABILITIES,
        a.PLACEMENTSKILLSANDKNOWLEDGE,
        a.DIRECTSUPERVISORNAME,
        a.DIRECTSUPERVISORMOBILEPREFIX,
        a.DIRECTSUPERVISORCONTACTNUMBE,
        a.PLACEMENTSTARTDATE,
        a.PLACEMENTENDDATE,
        a.TOTALDURATION,
        a.TKSHAREAMT,
        a.CUSTOMERSHAREAMT,
        FOP.LABEL AS FREQUENCYOFPAYMENT,
        a.ISELIGIBLE,
        a.TKSHAREUNAMT,
        WT.CODE AS WAGETRACKID,
        WT.LABEL AS WAGETRACK,
        SS.CODE AS NEWWAGESALARYSTATUSID,
        SS.LABEL AS NEWWAGESALARYSTATUS,
        a.NEWWAGESOURCEINDICATOR,
        a.STIPENDTRAINING_PROVIDERNAME,
        a.STIPENDTRAINING_PROGRAMID,
        a.STIPENDTRAINING_PROGRAMNAME,
        a.INCREMENTPERCENTAGE,
        a.TYPEOFPLEDGEID,
        a.EXTRAS,
        a.ISNEWWAGEABOVE1800,
        a.CREATEDON,
        a.UPDATEDON,
        FALSE AS IS_DELETED,
        'NEO2' AS SOURCE_SYSTEM_NAME,
        CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT,
        a.CURRENTWAGEOVERRIDE,
        a.NEWWAGEOVERRIDE,
        ROW_NUMBER() OVER (
            PARTITION BY a.APPLICATIONSUPPORTID
            ORDER BY a.UPDATEDON DESC NULLS LAST, a.CREATEDON DESC NULLS LAST
        ) AS RNK
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_VYW_WAGE a
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_3QQ_WAGETRACK WT
        ON CAST(WT.CODE AS VARCHAR) = CAST(a.WAGETRACKID AS VARCHAR)
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MM5_COUNTRY4 C
        ON CAST(C.ID AS VARCHAR) = CAST(a.PLACEMENTLOCATION AS VARCHAR)
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_VYW_FREQUENCYOFPAYMENT FOP
        ON CAST(FOP.CODE AS VARCHAR) = CAST(a.FREQUENCYOFPAYMENT AS VARCHAR)
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_SALARYSTATUS SS
        ON CAST(SS.CODE AS VARCHAR) = CAST(a.NEWWAGESALARYSTATUSID AS VARCHAR)
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_2DA_JOBLEVEL JL
        ON CAST(JL.CODE AS VARCHAR) = CAST(a.NEWJOBLEVELID AS VARCHAR)
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_VYW_WAGESTIPENDTYPE WST
        ON WST.WAGEID = a.APPLICATIONSUPPORTID
)

SELECT
    CAST(APPLICATIONSUPPORTID AS INTEGER) AS APPLICATIONSUPPORTID,
    CAST(STARTDATE AS timestamp) AS STARTDATE,
    CAST(ENDDATE AS timestamp) AS ENDDATE,
    NEWJOBLEVELID,
    NEWJOBLEVEL,
    NEWTITLE,
    NEWDEPARTMENT,
    NEWRESPONSABILITIES,
    REQUESTEDINCREMENTAMOUNT,
    NEWWAGE,
    CAST(REQUESTEDSTIPEND AS INTEGER) AS REQUESTEDSTIPEND,
    PLACEMENTLOCATION,
    HOSTORGANIZATIONNAME,
    PLACEMENTJOBTITLE,
    PLACEMENTJOBRESPONSABILITIES,
    PLACEMENTSKILLSANDKNOWLEDGE,
    DIRECTSUPERVISORNAME,
    DIRECTSUPERVISORMOBILEPREFIX,
    DIRECTSUPERVISORCONTACTNUMBE,
    CAST(PLACEMENTSTARTDATE AS timestamp) AS PLACEMENTSTARTDATE,
    CAST(PLACEMENTENDDATE AS timestamp) AS PLACEMENTENDDATE,
    CAST(TOTALDURATION AS INTEGER) AS TOTALDURATION,
    TKSHAREAMT,
    CUSTOMERSHAREAMT,
    FREQUENCYOFPAYMENT,
    ISELIGIBLE,
    TKSHAREUNAMT,
    WAGETRACKID,
    WAGETRACK,
    NEWWAGESALARYSTATUSID,
    NEWWAGESALARYSTATUS,
    NEWWAGESOURCEINDICATOR,
    STIPENDTRAINING_PROVIDERNAME,
    CAST(STIPENDTRAINING_PROGRAMID AS INTEGER) AS STIPENDTRAINING_PROGRAMID,
    STIPENDTRAINING_PROGRAMNAME,
    INCREMENTPERCENTAGE,
    TYPEOFPLEDGEID,
    EXTRAS,
    ISNEWWAGEABOVE1800,
    CAST(CREATEDON AS timestamp) AS CREATEDON,
    CAST(UPDATEDON AS timestamp) AS UPDATEDON,
    IS_DELETED,
    UPPER(TRIM(SOURCE_SYSTEM_NAME)) AS SOURCE_SYSTEM_NAME,
    CAST(DBT_UPDATED_AT AS timestamp) AS DBT_UPDATED_AT,
    CURRENTWAGEOVERRIDE,
    NEWWAGEOVERRIDE
FROM source_cte a
WHERE RNK = 1