with bronze_layer as
(
select
CAST(app.id AS VARCHAR) AS id
,CAST(app.referencenumber AS VARCHAR) AS referencenumber
,CAST(app.programversionid AS VARCHAR) AS programversionid
,CAST(app.decisionprogramversionid AS VARCHAR) AS decisionprogramversionid
,CAST(app.portaluserid AS VARCHAR) AS portaluserid
,CAST(custtype.label AS VARCHAR) AS customertype  --join  OSUSR_ZMZ_CUSTOMERTYPE(CODE)
,CAST(app.programcap AS VARCHAR) AS programcap
,CAST(app.applicationcap AS VARCHAR) AS applicationcap
,CAST(app.tkshareamt AS VARCHAR) AS tkshareamt
,CAST(app.applicationcapunutilized AS VARCHAR) AS applicationcapunutilized
,CAST(app.customershareamt AS VARCHAR) AS customershareamt
,CAST(app.totalcostwvat AS VARCHAR) AS totalcostwvat
,CAST(app.starton AS VARCHAR) AS starton
,CAST(app.endon AS VARCHAR) AS endon
,CAST(app.monitoringduedate AS VARCHAR) AS monitoringduedate
,CAST(app.spendingperiodduedate AS VARCHAR) AS spendingperiodduedate
,CAST(app.claimingperiodduedate AS VARCHAR) AS claimingperiodduedate
,CAST(app.duration AS VARCHAR) AS duration
,CAST(app.isactive AS VARCHAR) AS isactive
,CAST(app.submittedon AS VARCHAR) AS submittedon
,CAST(app.approvedon AS VARCHAR) AS approvedon
,cast(app.amendappinstancedocgudi_ar as VARCHAR) as amendappinstancedocgudi_ar
,CAST(app.haswagesupportmolemployees AS VARCHAR) AS haswagesupportmolemployees
,CAST(app.calculatedeconomicvalue AS VARCHAR) AS calculatedeconomicvalue
,CAST(app.calculatedgrantamount AS VARCHAR) AS calculatedgrantamount
,CAST(appstatus.label AS VARCHAR) AS applicationstatus  --join OSUSR_398_APPLICATIONSTATUS (CODE)
,CAST(hip.label AS VARCHAR) AS ishipooption  --join OSUSR_MM5_YESNOOPTION(ID)
,CAST(elig.label AS VARCHAR) AS iseligibleoption  --OSUSR_MM5_YESNOOPTION(ID)
,CAST(app.programcapid AS VARCHAR) AS programcapid
,CAST(appdetails.primaryname AS VARCHAR) AS primaryname
,CAST(appdetails.primaryemail AS VARCHAR) AS primaryemail
,CAST(appdetails.primarygenderid AS VARCHAR) AS primarygenderid
,CAST(prim.label AS VARCHAR) AS primarymemberdesignation --join OSUSR_NTP_MEMBERDESIGNATION (CODE)
,CAST(appdetails.primarymobilecountryprefix AS VARCHAR) AS primarymobilecountryprefix
,CAST(appdetails.primarymobilenumber AS VARCHAR) AS primarymobilenumber
,CAST(appdetails.secondaryname AS VARCHAR) AS secondaryname
,CAST(appdetails.secondaryemail AS VARCHAR) AS secondaryemail
,CAST(appdetails.secondarygenderid AS VARCHAR) AS secondarygenderid
,CAST(sec.label AS VARCHAR) AS secondarymemberdesignation --join OSUSR_NTP_MEMBERDESIGNATION (CODE)
,CAST(appdetails.secondarymobilecountryprefix AS VARCHAR) AS secondarymobilecountryprefix
,CAST(appdetails.secondarymobilenumber AS VARCHAR) AS secondarymobilenumber
,CAST(appprocess.programgroupid AS VARCHAR) AS programgroupid
,CAST(appprocess.applicationstepid AS VARCHAR) AS applicationstepid
,CAST(appprocess.step1completed AS VARCHAR) AS step1completed
,CAST(appprocess.step2completed AS VARCHAR) AS step2completed
,CAST(appprocess.step3completed AS VARCHAR) AS step3completed
,cast(app.createdby as VARCHAR ) as createdby
,CAST(app.createdon AS VARCHAR) AS createdon
,cast(app.updatedby as VARCHAR) as updatedby
,CAST(app.updatedon AS VARCHAR) AS updatedon ---End of first set
,CAST(NULL AS VARCHAR) AS userid
,CAST(NULL AS VARCHAR) AS programid
,CAST(NULL AS VARCHAR) AS applicationtypeid
,CAST(NULL AS VARCHAR) AS applicationloanstatusid
,CAST(NULL AS VARCHAR) AS applicationapprovaltypeid
,CAST(NULL AS VARCHAR) AS approverid
,CAST(NULL AS VARCHAR) AS assessorid
,CAST(NULL AS VARCHAR) AS rmid
,CAST(NULL AS VARCHAR) AS payabletoid
,CAST(NULL AS VARCHAR) AS identifier
,CAST(NULL AS VARCHAR) AS commercialname
,CAST(NULL AS VARCHAR) AS cr
,CAST(NULL AS VARCHAR) AS contractstartdate
,CAST(NULL AS VARCHAR) AS contractenddate
,CAST(NULL AS VARCHAR) AS spendingperiodenddate
,CAST(NULL AS VARCHAR) AS financingapprovedon
,CAST(NULL AS VARCHAR) AS assessorrecomendation
,CAST(NULL AS VARCHAR) AS approverdecision
,CAST(NULL AS VARCHAR) AS isgrantapproved
,CAST(NULL AS VARCHAR) AS isinterestedinfinancing
,CAST(NULL AS VARCHAR) AS isfinancingapproved
,CAST(NULL AS VARCHAR) AS financingcontractstartdate
,CAST(NULL AS VARCHAR) AS financingcontractenddate
,CAST(NULL AS VARCHAR) AS isaccordingtomoldirection
,CAST(NULL AS VARCHAR) AS crmref
,CAST(NULL AS VARCHAR) AS crmentity
,CAST(NULL AS VARCHAR) AS applicationtype
,CAST(NULL AS VARCHAR) AS approver_name
,CAST(NULL AS VARCHAR) AS assessor_name
--,CAST(NULL AS VARCHAR) AS rmname  --column missing
,CAST(FALSE AS VARCHAR) AS is_deleted --end of second set
,CAST(NULL AS VARCHAR) AS tmkn_maincompany
,CAST(NULL AS VARCHAR) as tmkn_maincompanyname --no column in source table
,CAST(NULL AS VARCHAR) as tmkn_branchname --no column in source table
,CAST(NULL AS VARCHAR) AS tmkn_name
,CAST(NULL AS VARCHAR) AS tmkn_applicantname
,CAST(NULL AS VARCHAR) AS tmkn_applicationdate
,CAST(NULL AS VARCHAR) AS tmkn_effectivedate
,CAST(NULL AS VARCHAR) AS tmkn_submittedon
,CAST(NULL AS VARCHAR) AS tmkn_approvedon
,CAST(NULL AS VARCHAR) AS tmkn_confirmedon
,CAST(NULL AS VARCHAR) AS tmkn_estdateidle
,CAST(NULL AS VARCHAR) AS tmkn_contractstartdate
,CAST(NULL AS VARCHAR) AS tmkn_contractenddate
,CAST(NULL AS VARCHAR) AS tmkn_monitoringduedate
,CAST(NULL AS VARCHAR) AS tmkn_billforthemonth
,CAST(NULL AS VARCHAR) AS tmkn_opperiodfrom
,CAST(NULL AS VARCHAR) AS tmkn_opperiodto
,CAST(NULL AS VARCHAR) AS tmkn_crregistrationdate
,CAST(NULL AS VARCHAR) AS tmkn_crexpirydate
,CAST(NULL AS VARCHAR) AS tmkn_primarysmartcardexpirydate
,CAST(NULL AS VARCHAR) AS tmkn_authorizedsmartcardexpirydate
,CAST(NULL AS VARCHAR) AS tmkn_financialsyeart1
,CAST(NULL AS VARCHAR) AS tmkn_financialsyeart2
,CAST(NULL AS VARCHAR) AS tmkn_productservice
,CAST(NULL AS VARCHAR) AS tmkn_crnumbermain
,CAST(NULL AS VARCHAR) AS tmkn_commercialnamear
,CAST(NULL AS VARCHAR) AS tmkn_primarycpr
,CAST(NULL AS VARCHAR) AS tmkn_primaryfirstname
,CAST(NULL AS VARCHAR) AS tmkn_primarylastname
,CAST(NULL AS VARCHAR)as tmkn_primarynationalityname --No column in source table
,CAST(NULL AS VARCHAR) AS tmkn_authorizedfirstname
,CAST(NULL AS VARCHAR) AS tmkn_authorizedlastname
,CAST(NULL AS VARCHAR) AS tmkn_authorizedemail
,CAST(NULL AS VARCHAR) AS tmkn_authorizedcpr
,CAST(NULL AS VARCHAR) AS tmkn_authorizedmobilenumber
,CAST(NULL AS VARCHAR) AS tmkn_iban
,CAST(NULL AS VARCHAR) AS tmkn_revenuey1
,CAST(NULL AS VARCHAR) AS tmkn_revenuey2
,CAST(NULL AS VARCHAR) AS tmkn_revenuepctdifference
,CAST(NULL AS VARCHAR) AS tmkn_grossprofity1
,CAST(NULL AS VARCHAR) AS tmkn_grossprofity2
,CAST(NULL AS VARCHAR) AS tmkn_grossprofitmarginyr1
,CAST(NULL AS VARCHAR) AS tmkn_grossprofitmarginyr2
,CAST(NULL AS VARCHAR) AS tmkn_grossprofitpctdifference
,CAST(NULL AS VARCHAR) AS tmkn_grossprofitmargindifference
,CAST(NULL AS VARCHAR) AS tmkn_netprofity1
,CAST(NULL AS VARCHAR) AS tmkn_netprofity2
,CAST(NULL AS VARCHAR) AS tmkn_netprofitmarginyr1
,CAST(NULL AS VARCHAR) AS tmkn_netprofitmarginyr2
,CAST(NULL AS VARCHAR) AS tmkn_netprofitpctdifference
,CAST(NULL AS VARCHAR) AS tmkn_netprofitmargindifference
,CAST(NULL AS VARCHAR) AS tmkn_cogsy1
,CAST(NULL AS VARCHAR) AS tmkn_cogsy2
,CAST(NULL AS VARCHAR) AS tmkn_cogspctdifference
,CAST(NULL AS VARCHAR) AS tmkn_totalassetsy1
,CAST(NULL AS VARCHAR) AS tmkn_totalassetsy2
,CAST(NULL AS VARCHAR) AS tmkn_totalassetspctdifference
,CAST(NULL AS VARCHAR) AS tmkn_fixedassetsy1
,CAST(NULL AS VARCHAR) AS tmkn_fixedassetsy2
,CAST(NULL AS VARCHAR) AS tmkn_fixedassetspctdifference
,CAST(NULL AS VARCHAR) AS tmkn_currentassetsy1
,CAST(NULL AS VARCHAR) AS tmkn_currentassetsy2
,CAST(NULL AS VARCHAR) AS tmkn_currentassestspctdifference
,CAST(NULL AS VARCHAR) AS tmkn_currentliabilitiesy1
,CAST(NULL AS VARCHAR) AS tmkn_currentliabilitiesy2
,CAST(NULL AS VARCHAR) AS tmkn_currentliabilitiespctdifference
,CAST(NULL AS VARCHAR) AS tmkn_noncurrentliabilitiesy1
,CAST(NULL AS VARCHAR) AS tmkn_noncurrentliabilitiesy2
,CAST(NULL AS VARCHAR) AS tmkn_noncurrentliabilitiespctdifference
,CAST(NULL AS VARCHAR) AS tmkn_ownersequityy1
,CAST(NULL AS VARCHAR) AS tmkn_ownersequityy2
,CAST(NULL AS VARCHAR) AS tmkn_ownersequitypctdifference
,CAST(NULL AS VARCHAR) AS tmkn_totalliabilitiesownersequityy1
,CAST(NULL AS VARCHAR) AS tmkn_totalliabilitiesownersequityy2
,CAST(NULL AS VARCHAR) AS tmkn_totalliabilitiesandownersequitypctdiffere
,CAST(NULL AS VARCHAR) AS tmkn_consolidatedratio
,CAST(NULL AS VARCHAR) AS tmkn_scoringmodelbusiness
,CAST(NULL AS VARCHAR) AS tmkn_scoringmodelentrepreneur
,CAST(NULL AS VARCHAR) AS tmkn_scoringmodelfinancials
,CAST(NULL AS VARCHAR) AS tmkn_scoringmodelindustry
,CAST(NULL AS VARCHAR) AS tmkn_grantcurrentbahrainizationrate
,CAST(NULL AS VARCHAR) AS tmkn_gbahrainizationresult
,CAST(NULL AS VARCHAR) AS tmkn_humancapitalgrantpercentage
,CAST(NULL AS VARCHAR) AS tmkn_humancapitalgrant
,CAST(NULL AS VARCHAR) AS tmkn_gnoofbahemployees
,CAST(NULL AS VARCHAR) AS tmkn_gnoofnonbahemployees
,CAST(NULL AS VARCHAR) AS tmkn_noofdisabledbahrainis
,CAST(NULL AS VARCHAR) AS tmkn_gnoofemployees
,CAST(NULL AS VARCHAR) AS tmkn_totalworkers
,CAST(NULL AS VARCHAR) AS tmkn_noofmonthsinoperations
,CAST(NULL AS VARCHAR) AS tmkn_siototalbahrainino
,CAST(NULL AS VARCHAR) AS tmkn_siototalexpatriatesno
,CAST(NULL AS VARCHAR) AS tmkn_totalemployeesallcrs
,CAST(NULL AS VARCHAR) AS tmkn_netexports
,CAST(NULL AS VARCHAR) AS tmkn_totalbas
,CAST(NULL AS VARCHAR) AS tmkn_consumedbas
,CAST(NULL AS VARCHAR) AS tmkn_availablebas
,CAST(NULL AS VARCHAR) AS tmkn_oldtotalbas
,CAST(NULL AS VARCHAR) AS tmkn_oldconsumedbas
,CAST(NULL AS VARCHAR) AS tmkn_oldavailablebas
,CAST(NULL AS VARCHAR) AS tmkn_totaltap
,CAST(NULL AS VARCHAR) AS tmkn_consumedtap
,CAST(NULL AS VARCHAR) AS tmkn_availabletap
,CAST(NULL AS VARCHAR) AS tmkn_totalbds
,CAST(NULL AS VARCHAR) AS tmkn_consumedbds
,CAST(NULL AS VARCHAR) AS tmkn_availablebds
,CAST(NULL AS VARCHAR) AS tmkn_totalqms
,CAST(NULL AS VARCHAR) AS tmkn_consumedqms
,CAST(NULL AS VARCHAR) AS tmkn_availableqms
,CAST(NULL AS VARCHAR) AS tmkn_totalict
,CAST(NULL AS VARCHAR) AS tmkn_consumedict
,CAST(NULL AS VARCHAR) AS tmkn_availableict
,CAST(NULL AS VARCHAR) AS tmkn_totalmas
,CAST(NULL AS VARCHAR) AS tmkn_consumedmas
,CAST(NULL AS VARCHAR) AS tmkn_availablemas
,CAST(NULL AS VARCHAR) AS tmkn_totalgap
,CAST(NULL AS VARCHAR) AS tmkn_consumedgap
,CAST(NULL AS VARCHAR) AS tmkn_availablegap
,CAST(NULL AS VARCHAR) AS tmkn_totalccs
,CAST(NULL AS VARCHAR) AS tmkn_consumedccs
,CAST(NULL AS VARCHAR) AS tmkn_availableccs
,CAST(NULL AS VARCHAR) AS tmkn_actplangrant
,CAST(NULL AS VARCHAR) AS tmkn_actpaidamount
,CAST(NULL AS VARCHAR) AS tmkn_plangrant
,CAST(NULL AS VARCHAR) AS tmkn_ppe_2022
,CAST(NULL AS VARCHAR) AS tmkn_ppe_2023
,CAST(NULL AS VARCHAR) AS tmkn_ppe_2024
,CAST(NULL AS VARCHAR) AS tmkn_capex_2022
,CAST(NULL AS VARCHAR) AS tmkn_capex_2023
,CAST(NULL AS VARCHAR) AS tmkn_capex_2024
from 
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATION as app left join 
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATIONCONTACTDETAILS as appdetails on appdetails.applicationid = app.id left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_APPLICATIONPROCESS as appprocess on appprocess.applicationid = appdetails.applicationid left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_398_APPLICATIONSTATUS as appstatus on appstatus.code  = app.APPLICATIONSTATUSID left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_CUSTOMERTYPE as custtype on custtype.code  = app.customertypeid  left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MM5_YESNOOPTION4 as hip on hip.id  = app.ishipooptionid   left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_MM5_YESNOOPTION4 as elig on elig.id  = app.iseligibleoptionid    left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_MEMBERDESIGNATION as prim on prim.code  = appdetails.primarymemberdesignationid left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_NTP_MEMBERDESIGNATION as sec on sec.code  = appdetails.secondarymemberdesignationid

union ALL

select
CAST(ntpapp.id AS VARCHAR) AS id
,CAST(ntpapp.IDENTIFIER AS VARCHAR) AS referencenumber
,CAST(ntpapp.PROGRAMID AS VARCHAR) AS programversionid
,CAST(NULL AS VARCHAR) AS decisionprogramversionid
,CAST(USERID AS VARCHAR) AS portaluserid
,CAST(NULL AS VARCHAR) AS customertype  --join  OSUSR_ZMZ_CUSTOMERTYPE(CODE)
,CAST(NULL AS VARCHAR) AS programcap
,CAST(NULL AS VARCHAR) AS applicationcap
,CAST(NULL AS VARCHAR) AS tkshareamt
,CAST(NULL AS VARCHAR) AS applicationcapunutilized
,CAST(NULL AS VARCHAR) AS customershareamt
,CAST(NULL AS VARCHAR) AS totalcostwvat
,CAST(ntpapp.CONTRACTSTARTDATE AS VARCHAR) AS starton
,CAST(ntpapp.CONTRACTENDDATE AS VARCHAR) AS endon
,CAST(NULL AS VARCHAR) AS monitoringduedate
,CAST(ntpapp.SPENDINGPERIODENDDATE AS VARCHAR) AS spendingperiodduedate
,CAST(NULL AS VARCHAR) AS claimingperiodduedate
,CAST(NULL AS VARCHAR) AS duration
,CAST(NULL AS VARCHAR) AS isactive
,CAST(NULL AS VARCHAR) AS submittedon
,CAST(ntpapp.approvedon AS VARCHAR) AS approvedon
,CAST(NULL AS VARCHAR) AS amendappinstancedocgudi_ar
,CAST(NULL AS VARCHAR) AS haswagesupportmolemployees
,CAST(NULL AS VARCHAR) AS calculatedeconomicvalue
,CAST(NULL AS VARCHAR) AS calculatedgrantamount
,appstatus.label as applicationstatus  --join OSUSR_398_APPLICATIONSTATUS (CODE)
,CAST(NULL AS VARCHAR) AS ishipooption  --join OSUSR_MM5_YESNOOPTION(ID)
,CAST(NULL AS VARCHAR) AS iseligibleoption  --OSUSR_MM5_YESNOOPTION(ID)
,CAST(NULL AS VARCHAR) AS programcapid
,CAST(NULL AS VARCHAR) AS primaryname
,CAST(NULL AS VARCHAR) AS primaryemail
,CAST(NULL AS VARCHAR) AS primarygenderid
,CAST(NULL AS VARCHAR) AS primarymemberdesignation --join OSUSR_NTP_MEMBERDESIGNATION (CODE)
,CAST(NULL AS VARCHAR) AS primarymobilecountryprefix
,CAST(NULL AS VARCHAR) AS primarymobilenumber
,CAST(NULL AS VARCHAR) AS secondaryname
,CAST(NULL AS VARCHAR) AS secondaryemail
,CAST(NULL AS VARCHAR) AS secondarygenderid
,CAST(NULL AS VARCHAR) AS secondarymemberdesignation --join OSUSR_NTP_MEMBERDESIGNATION (CODE)
,CAST(NULL AS VARCHAR) AS secondarymobilecountryprefix
,CAST(NULL AS VARCHAR) AS secondarymobilenumber
,CAST(NULL AS VARCHAR) AS programgroupid
,CAST(NULL AS VARCHAR) AS applicationstepid
,CAST(NULL AS VARCHAR) AS step1completed
,CAST(NULL AS VARCHAR) AS step2completed
,CAST(NULL AS VARCHAR) AS step3completed
,CAST(NULL AS VARCHAR) AS createdby
,CAST(ntpapp.createdon AS VARCHAR) AS createdon
,CAST(NULL AS VARCHAR) AS updatedby
,CAST(NULL AS VARCHAR) AS updatedon ---End of first set
,CAST(ntpapp.userid AS VARCHAR) AS userid
,CAST(ntpapp.programid AS VARCHAR) AS programid
,cast(ntpapp.applicationtypeid as VARCHAR) as applicationtypeid
,CAST(ntpapp.applicationloanstatusid AS VARCHAR) AS applicationloanstatusid
,CAST(ntpapp.applicationapprovaltypeid AS VARCHAR) AS applicationapprovaltypeid
,cast(ntpapp.approverid as VARCHAR) approverid
,cast(ntpapp.assessorid as VARCHAR) assessorid
,CAST(ntpapp.rmid AS VARCHAR) AS rmid
,CAST(ntpapp.payabletoid AS VARCHAR) AS payabletoid
,CAST(ntpapp.identifier AS VARCHAR) AS identifier
,CAST(ntpapp.commercialname AS VARCHAR) AS commercialname
,CAST(ntpapp.cr AS VARCHAR) AS cr
,CAST(ntpapp.contractstartdate AS VARCHAR) AS contractstartdate
,CAST(ntpapp.contractenddate AS VARCHAR) AS contractenddate
,CAST(ntpapp.spendingperiodenddate AS VARCHAR) AS spendingperiodenddate
,CAST(ntpapp.financingapprovedon AS VARCHAR) AS financingapprovedon
,CAST(ntpapp.assessorrecomendation AS VARCHAR) AS assessorrecomendation
,CAST(ntpapp.approverdecision AS VARCHAR) AS approverdecision
,CAST(ntpapp.isgrantapproved AS VARCHAR) AS isgrantapproved
,CAST(ntpapp.isinterestedinfinancing AS VARCHAR) AS isinterestedinfinancing
,CAST(ntpapp.isfinancingapproved AS VARCHAR) AS isfinancingapproved
,CAST(ntpapp.financingcontractstartdate AS VARCHAR) AS financingcontractstartdate
,CAST(ntpapp.financingcontractenddate AS VARCHAR) AS financingcontractenddate
,CAST(ntpapp.isaccordingtomoldirection AS VARCHAR) AS isaccordingtomoldirection
,cast(ntpapp.crmref as VARCHAR) crmref --column missing
,cast(ntpapp.crmentity as VARCHAR) crmentity  --column missing
,CAST(px1app.label AS VARCHAR) AS applicationtype
,CAST(approver.name  AS VARCHAR) AS approver_name
,CAST(assessor.name  AS VARCHAR) AS assessor_name
--,rmname  --column misisng
,cast (FALSE AS VARCHAR) as is_deleted
,CAST(NULL AS VARCHAR) AS tmkn_maincompany
,CAST(NULL AS VARCHAR) as tmkn_maincompanyname --no column in source table
,CAST(NULL AS VARCHAR) as tmkn_branchname --no column in source table
,CAST(NULL AS VARCHAR) AS tmkn_name
,CAST(NULL AS VARCHAR) AS tmkn_applicantname
,CAST(NULL AS VARCHAR) AS tmkn_applicationdate
,CAST(NULL AS VARCHAR) AS tmkn_effectivedate
,CAST(NULL AS VARCHAR) AS tmkn_submittedon
,CAST(NULL AS VARCHAR) AS tmkn_approvedon
,CAST(NULL AS VARCHAR) AS tmkn_confirmedon
,CAST(NULL AS VARCHAR) AS tmkn_estdateidle
,CAST(NULL AS VARCHAR) AS tmkn_contractstartdate
,CAST(NULL AS VARCHAR) AS tmkn_contractenddate
,CAST(NULL AS VARCHAR) AS tmkn_monitoringduedate
,CAST(NULL AS VARCHAR) AS tmkn_billforthemonth
,CAST(NULL AS VARCHAR) AS tmkn_opperiodfrom
,CAST(NULL AS VARCHAR) AS tmkn_opperiodto
,CAST(NULL AS VARCHAR) AS tmkn_crregistrationdate
,CAST(NULL AS VARCHAR) AS tmkn_crexpirydate
,CAST(NULL AS VARCHAR) AS tmkn_primarysmartcardexpirydate
,CAST(NULL AS VARCHAR) AS tmkn_authorizedsmartcardexpirydate
,CAST(NULL AS VARCHAR) AS tmkn_financialsyeart1
,CAST(NULL AS VARCHAR) AS tmkn_financialsyeart2
,CAST(NULL AS VARCHAR) AS tmkn_productservice
,CAST(NULL AS VARCHAR) AS tmkn_crnumbermain
,CAST(NULL AS VARCHAR) AS tmkn_commercialnamear
,CAST(NULL AS VARCHAR) AS tmkn_primarycpr
,CAST(NULL AS VARCHAR) AS tmkn_primaryfirstname
,CAST(NULL AS VARCHAR) AS tmkn_primarylastname
,CAST(NULL AS VARCHAR)as tmkn_primarynationalityname --No column in source table
,CAST(NULL AS VARCHAR) AS tmkn_authorizedfirstname
,CAST(NULL AS VARCHAR) AS tmkn_authorizedlastname
,CAST(NULL AS VARCHAR) AS tmkn_authorizedemail
,CAST(NULL AS VARCHAR) AS tmkn_authorizedcpr
,CAST(NULL AS VARCHAR) AS tmkn_authorizedmobilenumber
,CAST(NULL AS VARCHAR) AS tmkn_iban
,CAST(NULL AS VARCHAR) AS tmkn_revenuey1
,CAST(NULL AS VARCHAR) AS tmkn_revenuey2
,CAST(NULL AS VARCHAR) AS tmkn_revenuepctdifference
,CAST(NULL AS VARCHAR) AS tmkn_grossprofity1
,CAST(NULL AS VARCHAR) AS tmkn_grossprofity2
,CAST(NULL AS VARCHAR) AS tmkn_grossprofitmarginyr1
,CAST(NULL AS VARCHAR) AS tmkn_grossprofitmarginyr2
,CAST(NULL AS VARCHAR) AS tmkn_grossprofitpctdifference
,CAST(NULL AS VARCHAR) AS tmkn_grossprofitmargindifference
,CAST(NULL AS VARCHAR) AS tmkn_netprofity1
,CAST(NULL AS VARCHAR) AS tmkn_netprofity2
,CAST(NULL AS VARCHAR) AS tmkn_netprofitmarginyr1
,CAST(NULL AS VARCHAR) AS tmkn_netprofitmarginyr2
,CAST(NULL AS VARCHAR) AS tmkn_netprofitpctdifference
,CAST(NULL AS VARCHAR) AS tmkn_netprofitmargindifference
,CAST(NULL AS VARCHAR) AS tmkn_cogsy1
,CAST(NULL AS VARCHAR) AS tmkn_cogsy2
,CAST(NULL AS VARCHAR) AS tmkn_cogspctdifference
,CAST(NULL AS VARCHAR) AS tmkn_totalassetsy1
,CAST(NULL AS VARCHAR) AS tmkn_totalassetsy2
,CAST(NULL AS VARCHAR) AS tmkn_totalassetspctdifference
,CAST(NULL AS VARCHAR) AS tmkn_fixedassetsy1
,CAST(NULL AS VARCHAR) AS tmkn_fixedassetsy2
,CAST(NULL AS VARCHAR) AS tmkn_fixedassetspctdifference
,CAST(NULL AS VARCHAR) AS tmkn_currentassetsy1
,CAST(NULL AS VARCHAR) AS tmkn_currentassetsy2
,CAST(NULL AS VARCHAR) AS tmkn_currentassestspctdifference
,CAST(NULL AS VARCHAR) AS tmkn_currentliabilitiesy1
,CAST(NULL AS VARCHAR) AS tmkn_currentliabilitiesy2
,CAST(NULL AS VARCHAR) AS tmkn_currentliabilitiespctdifference
,CAST(NULL AS VARCHAR) AS tmkn_noncurrentliabilitiesy1
,CAST(NULL AS VARCHAR) AS tmkn_noncurrentliabilitiesy2
,CAST(NULL AS VARCHAR) AS tmkn_noncurrentliabilitiespctdifference
,CAST(NULL AS VARCHAR) AS tmkn_ownersequityy1
,CAST(NULL AS VARCHAR) AS tmkn_ownersequityy2
,CAST(NULL AS VARCHAR) AS tmkn_ownersequitypctdifference
,CAST(NULL AS VARCHAR) AS tmkn_totalliabilitiesownersequityy1
,CAST(NULL AS VARCHAR) AS tmkn_totalliabilitiesownersequityy2
,CAST(NULL AS VARCHAR) AS tmkn_totalliabilitiesandownersequitypctdiffere
,CAST(NULL AS VARCHAR) AS tmkn_consolidatedratio
,CAST(NULL AS VARCHAR) AS tmkn_scoringmodelbusiness
,CAST(NULL AS VARCHAR) AS tmkn_scoringmodelentrepreneur
,CAST(NULL AS VARCHAR) AS tmkn_scoringmodelfinancials
,CAST(NULL AS VARCHAR) AS tmkn_scoringmodelindustry
,CAST(NULL AS VARCHAR) AS tmkn_grantcurrentbahrainizationrate
,CAST(NULL AS VARCHAR) AS tmkn_gbahrainizationresult
,CAST(NULL AS VARCHAR) AS tmkn_humancapitalgrantpercentage
,CAST(NULL AS VARCHAR) AS tmkn_humancapitalgrant
,CAST(NULL AS VARCHAR) AS tmkn_gnoofbahemployees
,CAST(NULL AS VARCHAR) AS tmkn_gnoofnonbahemployees
,CAST(NULL AS VARCHAR) AS tmkn_noofdisabledbahrainis
,CAST(NULL AS VARCHAR) AS tmkn_gnoofemployees
,CAST(NULL AS VARCHAR) AS tmkn_totalworkers
,CAST(NULL AS VARCHAR) AS tmkn_noofmonthsinoperations
,CAST(NULL AS VARCHAR) AS tmkn_siototalbahrainino
,CAST(NULL AS VARCHAR) AS tmkn_siototalexpatriatesno
,CAST(NULL AS VARCHAR) AS tmkn_totalemployeesallcrs
,CAST(NULL AS VARCHAR) AS tmkn_netexports
,CAST(NULL AS VARCHAR) AS tmkn_totalbas
,CAST(NULL AS VARCHAR) AS tmkn_consumedbas
,CAST(NULL AS VARCHAR) AS tmkn_availablebas
,CAST(NULL AS VARCHAR) AS tmkn_oldtotalbas
,CAST(NULL AS VARCHAR) AS tmkn_oldconsumedbas
,CAST(NULL AS VARCHAR) AS tmkn_oldavailablebas
,CAST(NULL AS VARCHAR) AS tmkn_totaltap
,CAST(NULL AS VARCHAR) AS tmkn_consumedtap
,CAST(NULL AS VARCHAR) AS tmkn_availabletap
,CAST(NULL AS VARCHAR) AS tmkn_totalbds
,CAST(NULL AS VARCHAR) AS tmkn_consumedbds
,CAST(NULL AS VARCHAR) AS tmkn_availablebds
,CAST(NULL AS VARCHAR) AS tmkn_totalqms
,CAST(NULL AS VARCHAR) AS tmkn_consumedqms
,CAST(NULL AS VARCHAR) AS tmkn_availableqms
,CAST(NULL AS VARCHAR) AS tmkn_totalict
,CAST(NULL AS VARCHAR) AS tmkn_consumedict
,CAST(NULL AS VARCHAR) AS tmkn_availableict
,CAST(NULL AS VARCHAR) AS tmkn_totalmas
,CAST(NULL AS VARCHAR) AS tmkn_consumedmas
,CAST(NULL AS VARCHAR) AS tmkn_availablemas
,CAST(NULL AS VARCHAR) AS tmkn_totalgap
,CAST(NULL AS VARCHAR) AS tmkn_consumedgap
,CAST(NULL AS VARCHAR) AS tmkn_availablegap
,CAST(NULL AS VARCHAR) AS tmkn_totalccs
,CAST(NULL AS VARCHAR) AS tmkn_consumedccs
,CAST(NULL AS VARCHAR) AS tmkn_availableccs
,CAST(NULL AS VARCHAR) AS tmkn_actplangrant
,CAST(NULL AS VARCHAR) AS tmkn_actpaidamount
,CAST(NULL AS VARCHAR) AS tmkn_plangrant
,CAST(NULL AS VARCHAR) AS tmkn_ppe_2022
,CAST(NULL AS VARCHAR) AS tmkn_ppe_2023
,CAST(NULL AS VARCHAR) AS tmkn_ppe_2024
,CAST(NULL AS VARCHAR) AS tmkn_capex_2022
,CAST(NULL AS VARCHAR) AS tmkn_capex_2023
,CAST(NULL AS VARCHAR) AS tmkn_capex_2024
from 
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_PX1_APPLICATION as ntpapp  left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_PX1_APPLICATIONTYPE as px1app  on px1app.id = ntpapp.applicationtypeid left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_PX1_APPLICATIONSTATUS as appstatus  on appstatus.id = ntpapp.applicationstatusid  left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSSYS_USER as approver on approver.id = ntpapp.approverid left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSSYS_USER as assessor on assessor.id = ntpapp.assessorid left join
dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSSYS_USER as rmuser on rmuser.id = ntpapp.rmid  

union ALL

select
CAST(tmkn_applicationId AS VARCHAR) AS id
,CAST(tmkn_name AS VARCHAR) AS referencenumber
,CAST(NULL AS VARCHAR) AS programversionid
,CAST(NULL AS VARCHAR) AS decisionprogramversionid
,CAST(NULL AS VARCHAR) AS portaluserid
,CAST(NULL AS VARCHAR) AS customertype  --join  OSUSR_ZMZ_CUSTOMERTYPE(CODE)
,CAST(NULL AS VARCHAR) AS programcap
,CAST(NULL AS VARCHAR) AS applicationcap
,CAST(NULL AS VARCHAR) AS tkshareamt
,CAST(NULL AS VARCHAR) AS applicationcapunutilized
,CAST(NULL AS VARCHAR) AS customershareamt
,CAST(NULL AS VARCHAR) AS totalcostwvat
,CAST(tmkn_contractstartdate AS VARCHAR) AS starton
,CAST(tmkn_contractenddate AS VARCHAR) AS endon
,CAST(tmkn_monitoringduedate AS VARCHAR) AS monitoringduedate
,CAST(tmkn_opperiodto AS VARCHAR) AS spendingperiodduedate
,CAST(NULL AS VARCHAR) AS claimingperiodduedate
,CAST(NULL AS VARCHAR) AS duration
,CAST(NULL AS VARCHAR) AS isactive
,CAST(tmkn_submittedon AS VARCHAR) AS submittedon
,CAST(tmkn_approvedon AS VARCHAR) AS approvedon
,CAST(NULL AS VARCHAR) AS amendappinstancedocgudi_ar
,CAST(NULL AS VARCHAR) AS haswagesupportmolemployees
,CAST(NULL AS VARCHAR) AS calculatedeconomicvalue
,CAST(NULL AS VARCHAR) AS calculatedgrantamount
,CAST(NULL AS VARCHAR) AS applicationstatus  --join OSUSR_398_APPLICATIONSTATUS (CODE)
,CAST(NULL AS VARCHAR) AS ishipooption  --join OSUSR_MM5_YESNOOPTION(ID)
,CAST(NULL AS VARCHAR) AS iseligibleoption  --OSUSR_MM5_YESNOOPTION(ID)
,CAST(NULL AS VARCHAR) AS programcapid
,CAST(tmkn_primaryfirstname AS VARCHAR) AS primaryname
,CAST(tmkn_primaryemail AS VARCHAR) AS primaryemail
,CAST(NULL AS VARCHAR) AS primarygenderid
,CAST(NULL AS VARCHAR) AS primarymemberdesignation --join OSUSR_NTP_MEMBERDESIGNATION (CODE)
,CAST(NULL AS VARCHAR) AS primarymobilecountryprefix
,CAST(tmkn_primarymobilenumber AS VARCHAR) AS primarymobilenumber
,CAST(NULL AS VARCHAR) AS secondaryname
,CAST(NULL AS VARCHAR) AS secondaryemail
,CAST(NULL AS VARCHAR) AS secondarygenderid
,CAST(NULL AS VARCHAR) AS secondarymemberdesignation --join OSUSR_NTP_MEMBERDESIGNATION (CODE)
,CAST(NULL AS VARCHAR) AS secondarymobilecountryprefix
,CAST(NULL AS VARCHAR) AS secondarymobilenumber
,CAST(NULL AS VARCHAR) AS programgroupid
,CAST(NULL AS VARCHAR) AS applicationstepid
,CAST(NULL AS VARCHAR) AS step1completed
,CAST(NULL AS VARCHAR) AS step2completed
,CAST(NULL AS VARCHAR) AS step3completed
,CAST(NULL AS VARCHAR) AS createdby
,CAST(NULL AS VARCHAR) AS createdon
,CAST(NULL AS VARCHAR) AS updatedby
,CAST(NULL AS VARCHAR) AS updatedon ---End of first set
,CAST(NULL AS VARCHAR) AS userid
,CAST(NULL AS VARCHAR) AS programid
,CAST(NULL AS VARCHAR) AS applicationtypeid
,CAST(NULL AS VARCHAR) AS applicationloanstatusid
,CAST(NULL AS VARCHAR) AS applicationapprovaltypeid
,CAST(NULL AS VARCHAR) AS approverid
,CAST(NULL AS VARCHAR) AS assessorid
,CAST(NULL AS VARCHAR) AS rmid
,CAST(NULL AS VARCHAR) AS payabletoid
,CAST(tmkn_name AS VARCHAR) AS identifier
,CAST(tmkn_commercialname AS VARCHAR) AS commercialname
,CAST(tmkn_crnumbermain AS VARCHAR) AS cr
,CAST(tmkn_contractstartdate AS VARCHAR) AS contractstartdate
,CAST(tmkn_contractenddate AS VARCHAR) AS contractenddate
,CAST(tmkn_opperiodto AS VARCHAR) AS spendingperiodenddate
,CAST(NULL AS VARCHAR) AS financingapprovedon
,CAST(NULL AS VARCHAR) AS assessorrecomendation
,CAST(NULL AS VARCHAR) AS approverdecision
,CAST(NULL AS VARCHAR) AS isgrantapproved
,CAST(NULL AS VARCHAR) AS isinterestedinfinancing
,CAST(NULL AS VARCHAR) AS isfinancingapproved
,CAST(NULL AS VARCHAR) AS financingcontractstartdate
,CAST(NULL AS VARCHAR) AS financingcontractenddate
,CAST(NULL AS VARCHAR) AS isaccordingtomoldirection
,CAST(NULL AS VARCHAR) AS crmref
,CAST(NULL AS VARCHAR) AS crmentity
,CAST(NULL AS VARCHAR) AS applicationtype
,CAST(NULL AS VARCHAR) AS approver_name
,CAST(NULL AS VARCHAR) AS assessor_name
--,CAST(NULL AS VARCHAR) AS rmname  --column missing
,CAST(FALSE AS VARCHAR) AS is_deleted --end of second set
,CAST(tmkn_maincompany AS VARCHAR) AS tmkn_maincompany
,CAST(NULL AS VARCHAR) as tmkn_maincompanyname --no column in source table
,CAST(NULL AS VARCHAR) as tmkn_branchname --no column in source table
,CAST(tmkn_name AS VARCHAR) AS tmkn_name
,CAST(tmkn_applicantname AS VARCHAR) AS tmkn_applicantname
,CAST(tmkn_applicationdate AS VARCHAR) AS tmkn_applicationdate
,CAST(tmkn_effectivedate AS VARCHAR) AS tmkn_effectivedate
,CAST(tmkn_submittedon AS VARCHAR) AS tmkn_submittedon
,CAST(tmkn_approvedon AS VARCHAR) AS tmkn_approvedon
,CAST(tmkn_confirmedon AS VARCHAR) AS tmkn_confirmedon
,CAST(tmkn_estdateidle AS VARCHAR) AS tmkn_estdateidle
,CAST(tmkn_contractstartdate AS VARCHAR) AS tmkn_contractstartdate
,CAST(tmkn_contractenddate AS VARCHAR) AS tmkn_contractenddate
,CAST(tmkn_monitoringduedate AS VARCHAR) AS tmkn_monitoringduedate
,CAST(tmkn_billforthemonth AS VARCHAR) AS tmkn_billforthemonth
,CAST(tmkn_opperiodfrom AS VARCHAR) AS tmkn_opperiodfrom
,CAST(tmkn_opperiodto AS VARCHAR) AS tmkn_opperiodto
,CAST(tmkn_crregistrationdate AS VARCHAR) AS tmkn_crregistrationdate
,CAST(tmkn_crexpirydate AS VARCHAR) AS tmkn_crexpirydate
,CAST(tmkn_primarysmartcardexpirydate AS VARCHAR) AS tmkn_primarysmartcardexpirydate
,CAST(tmkn_authorizedsmartcardexpirydate AS VARCHAR) AS tmkn_authorizedsmartcardexpirydate
,CAST(tmkn_financialsyeart1 AS VARCHAR) AS tmkn_financialsyeart1
,CAST(tmkn_financialsyeart2 AS VARCHAR) AS tmkn_financialsyeart2
,CAST(tmkn_productservice AS VARCHAR) AS tmkn_productservice
,CAST(tmkn_crnumbermain AS VARCHAR) AS tmkn_crnumbermain
,CAST(tmkn_commercialnamear AS VARCHAR) AS tmkn_commercialnamear
,CAST(tmkn_primarycpr AS VARCHAR) AS tmkn_primarycpr
,CAST(tmkn_primaryfirstname AS VARCHAR) AS tmkn_primaryfirstname
,CAST(tmkn_primarylastname AS VARCHAR) AS tmkn_primarylastname
,CAST(NULL AS VARCHAR)as tmkn_primarynationalityname --No column in source table
,CAST(tmkn_authorizedfirstname AS VARCHAR) AS tmkn_authorizedfirstname
,CAST(tmkn_authorizedlastname AS VARCHAR) AS tmkn_authorizedlastname
,CAST(tmkn_authorizedemail AS VARCHAR) AS tmkn_authorizedemail
,CAST(tmkn_authorizedcpr AS VARCHAR) AS tmkn_authorizedcpr
,CAST(tmkn_authorizedmobilenumber AS VARCHAR) AS tmkn_authorizedmobilenumber
,CAST(tmkn_iban AS VARCHAR) AS tmkn_iban
,CAST(tmkn_revenuey1 AS VARCHAR) AS tmkn_revenuey1
,CAST(tmkn_revenuey2 AS VARCHAR) AS tmkn_revenuey2
,CAST(tmkn_revenuepctdifference AS VARCHAR) AS tmkn_revenuepctdifference
,CAST(tmkn_grossprofity1 AS VARCHAR) AS tmkn_grossprofity1
,CAST(tmkn_grossprofity2 AS VARCHAR) AS tmkn_grossprofity2
,CAST(tmkn_grossprofitmarginyr1 AS VARCHAR) AS tmkn_grossprofitmarginyr1
,CAST(tmkn_grossprofitmarginyr2 AS VARCHAR) AS tmkn_grossprofitmarginyr2
,CAST(tmkn_grossprofitpctdifference AS VARCHAR) AS tmkn_grossprofitpctdifference
,CAST(tmkn_grossprofitmargindifference AS VARCHAR) AS tmkn_grossprofitmargindifference
,CAST(tmkn_netprofity1 AS VARCHAR) AS tmkn_netprofity1
,CAST(tmkn_netprofity2 AS VARCHAR) AS tmkn_netprofity2
,CAST(tmkn_netprofitmarginyr1 AS VARCHAR) AS tmkn_netprofitmarginyr1
,CAST(tmkn_netprofitmarginyr2 AS VARCHAR) AS tmkn_netprofitmarginyr2
,CAST(tmkn_netprofitpctdifference AS VARCHAR) AS tmkn_netprofitpctdifference
,CAST(tmkn_netprofitmargindifference AS VARCHAR) AS tmkn_netprofitmargindifference
,CAST(tmkn_cogsy1 AS VARCHAR) AS tmkn_cogsy1
,CAST(tmkn_cogsy2 AS VARCHAR) AS tmkn_cogsy2
,CAST(tmkn_cogspctdifference AS VARCHAR) AS tmkn_cogspctdifference
,CAST(tmkn_totalassetsy1 AS VARCHAR) AS tmkn_totalassetsy1
,CAST(tmkn_totalassetsy2 AS VARCHAR) AS tmkn_totalassetsy2
,CAST(tmkn_totalassetspctdifference AS VARCHAR) AS tmkn_totalassetspctdifference
,CAST(tmkn_fixedassetsy1 AS VARCHAR) AS tmkn_fixedassetsy1
,CAST(tmkn_fixedassetsy2 AS VARCHAR) AS tmkn_fixedassetsy2
,CAST(tmkn_fixedassetspctdifference AS VARCHAR) AS tmkn_fixedassetspctdifference
,CAST(tmkn_currentassetsy1 AS VARCHAR) AS tmkn_currentassetsy1
,CAST(tmkn_currentassetsy2 AS VARCHAR) AS tmkn_currentassetsy2
,CAST(tmkn_currentassestspctdifference AS VARCHAR) AS tmkn_currentassestspctdifference
,CAST(tmkn_currentliabilitiesy1 AS VARCHAR) AS tmkn_currentliabilitiesy1
,CAST(tmkn_currentliabilitiesy2 AS VARCHAR) AS tmkn_currentliabilitiesy2
,CAST(tmkn_currentliabilitiespctdifference AS VARCHAR) AS tmkn_currentliabilitiespctdifference
,CAST(tmkn_noncurrentliabilitiesy1 AS VARCHAR) AS tmkn_noncurrentliabilitiesy1
,CAST(tmkn_noncurrentliabilitiesy2 AS VARCHAR) AS tmkn_noncurrentliabilitiesy2
,CAST(tmkn_noncurrentliabilitiespctdifference AS VARCHAR) AS tmkn_noncurrentliabilitiespctdifference
,CAST(tmkn_ownersequityy1 AS VARCHAR) AS tmkn_ownersequityy1
,CAST(tmkn_ownersequityy2 AS VARCHAR) AS tmkn_ownersequityy2
,CAST(tmkn_ownersequitypctdifference AS VARCHAR) AS tmkn_ownersequitypctdifference
,CAST(tmkn_totalliabilitiesownersequityy1 AS VARCHAR) AS tmkn_totalliabilitiesownersequityy1
,CAST(tmkn_totalliabilitiesownersequityy2 AS VARCHAR) AS tmkn_totalliabilitiesownersequityy2
,CAST(tmkn_totalliabilitiesandownersequitypctdiffere AS VARCHAR) AS tmkn_totalliabilitiesandownersequitypctdiffere
,CAST(tmkn_consolidatedratio AS VARCHAR) AS tmkn_consolidatedratio
,CAST(tmkn_scoringmodelbusiness AS VARCHAR) AS tmkn_scoringmodelbusiness
,CAST(tmkn_scoringmodelentrepreneur AS VARCHAR) AS tmkn_scoringmodelentrepreneur
,CAST(tmkn_scoringmodelfinancials AS VARCHAR) AS tmkn_scoringmodelfinancials
,CAST(tmkn_scoringmodelindustry AS VARCHAR) AS tmkn_scoringmodelindustry
,CAST(tmkn_grantcurrentbahrainizationrate AS VARCHAR) AS tmkn_grantcurrentbahrainizationrate
,CAST(tmkn_gbahrainizationresult AS VARCHAR) AS tmkn_gbahrainizationresult
,CAST(tmkn_humancapitalgrantpercentage AS VARCHAR) AS tmkn_humancapitalgrantpercentage
,CAST(tmkn_humancapitalgrant AS VARCHAR) AS tmkn_humancapitalgrant
,CAST(tmkn_gnoofbahemployees AS VARCHAR) AS tmkn_gnoofbahemployees
,CAST(tmkn_gnoofnonbahemployees AS VARCHAR) AS tmkn_gnoofnonbahemployees
,CAST(tmkn_noofdisabledbahrainis AS VARCHAR) AS tmkn_noofdisabledbahrainis
,CAST(tmkn_gnoofemployees AS VARCHAR) AS tmkn_gnoofemployees
,CAST(tmkn_totalworkers AS VARCHAR) AS tmkn_totalworkers
,CAST(tmkn_noofmonthsinoperations AS VARCHAR) AS tmkn_noofmonthsinoperations
,CAST(tmkn_siototalbahrainino AS VARCHAR) AS tmkn_siototalbahrainino
,CAST(tmkn_siototalexpatriatesno AS VARCHAR) AS tmkn_siototalexpatriatesno
,CAST(tmkn_totalemployeesallcrs AS VARCHAR) AS tmkn_totalemployeesallcrs
,CAST(tmkn_netexports AS VARCHAR) AS tmkn_netexports
,CAST(tmkn_totalbas AS VARCHAR) AS tmkn_totalbas
,CAST(tmkn_consumedbas AS VARCHAR) AS tmkn_consumedbas
,CAST(tmkn_availablebas AS VARCHAR) AS tmkn_availablebas
,CAST(tmkn_oldtotalbas AS VARCHAR) AS tmkn_oldtotalbas
,CAST(tmkn_oldconsumedbas AS VARCHAR) AS tmkn_oldconsumedbas
,CAST(tmkn_oldavailablebas AS VARCHAR) AS tmkn_oldavailablebas
,CAST(tmkn_totaltap AS VARCHAR) AS tmkn_totaltap
,CAST(tmkn_consumedtap AS VARCHAR) AS tmkn_consumedtap
,CAST(tmkn_availabletap AS VARCHAR) AS tmkn_availabletap
,CAST(tmkn_totalbds AS VARCHAR) AS tmkn_totalbds
,CAST(tmkn_consumedbds AS VARCHAR) AS tmkn_consumedbds
,CAST(tmkn_availablebds AS VARCHAR) AS tmkn_availablebds
,CAST(tmkn_totalqms AS VARCHAR) AS tmkn_totalqms
,CAST(tmkn_consumedqms AS VARCHAR) AS tmkn_consumedqms
,CAST(tmkn_availableqms AS VARCHAR) AS tmkn_availableqms
,CAST(tmkn_totalict AS VARCHAR) AS tmkn_totalict
,CAST(tmkn_consumedict AS VARCHAR) AS tmkn_consumedict
,CAST(tmkn_availableict AS VARCHAR) AS tmkn_availableict
,CAST(tmkn_totalmas AS VARCHAR) AS tmkn_totalmas
,CAST(tmkn_consumedmas AS VARCHAR) AS tmkn_consumedmas
,CAST(tmkn_availablemas AS VARCHAR) AS tmkn_availablemas
,CAST(tmkn_totalgap AS VARCHAR) AS tmkn_totalgap
,CAST(tmkn_consumedgap AS VARCHAR) AS tmkn_consumedgap
,CAST(tmkn_availablegap AS VARCHAR) AS tmkn_availablegap
,CAST(tmkn_totalccs AS VARCHAR) AS tmkn_totalccs
,CAST(tmkn_consumedccs AS VARCHAR) AS tmkn_consumedccs
,CAST(tmkn_availableccs AS VARCHAR) AS tmkn_availableccs
,CAST(tmkn_actplangrant AS VARCHAR) AS tmkn_actplangrant
,CAST(tmkn_actpaidamount AS VARCHAR) AS tmkn_actpaidamount
,CAST(tmkn_plangrant AS VARCHAR) AS tmkn_plangrant
,CAST(tmkn_ppe_2022 AS VARCHAR) AS tmkn_ppe_2022
,CAST(tmkn_ppe_2023 AS VARCHAR) AS tmkn_ppe_2023
,CAST(tmkn_ppe_2024 AS VARCHAR) AS tmkn_ppe_2024
,CAST(tmkn_capex_2022 AS VARCHAR) AS tmkn_capex_2022
,CAST(tmkn_capex_2023 AS VARCHAR) AS tmkn_capex_2023
,CAST(tmkn_capex_2024 AS VARCHAR) AS tmkn_capex_2024
from  dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".tmkn_applicationbase
),

silver_layer AS (
 select 
CAST(id AS VARCHAR) AS id
,CAST(referencenumber AS VARCHAR) AS referencenumber
,CAST(programversionid AS VARCHAR) AS programversionid
,CAST(decisionprogramversionid AS VARCHAR) AS decisionprogramversionid
,CAST(portaluserid AS VARCHAR) AS portaluserid
,CAST(customertype AS VARCHAR) AS customertype
,CAST(programcap AS VARCHAR) AS programcap
,CAST(applicationcap AS VARCHAR) AS applicationcap
,CAST(tkshareamt AS VARCHAR) AS tkshareamt
,CAST(applicationcapunutilized AS VARCHAR) AS applicationcapunutilized
,CAST(customershareamt AS VARCHAR) AS customershareamt
,CAST(totalcostwvat AS VARCHAR) AS totalcostwvat
,CAST(starton AS VARCHAR) AS starton
,CAST(endon AS VARCHAR) AS endon
,CAST(monitoringduedate AS VARCHAR) AS monitoringduedate
,CAST(spendingperiodduedate AS VARCHAR) AS spendingperiodduedate
,CAST(claimingperiodduedate AS VARCHAR) AS claimingperiodduedate
,CAST(duration AS VARCHAR) AS duration
,CAST(isactive AS VARCHAR) AS isactive
,CAST(submittedon AS VARCHAR) AS submittedon
,CAST(approvedon AS VARCHAR) AS approvedon
,CAST(amendappinstancedocgudi_ar AS VARCHAR) AS amendappinstancedocgudi_ar
,CAST(haswagesupportmolemployees AS VARCHAR) AS haswagesupportmolemployees
,CAST(calculatedeconomicvalue AS VARCHAR) AS calculatedeconomicvalue
,CAST(calculatedgrantamount AS VARCHAR) AS calculatedgrantamount
,CAST(applicationstatus AS VARCHAR) AS applicationstatus
,CAST(ishipooption AS VARCHAR) AS ishipooption
,CAST(iseligibleoption AS VARCHAR) AS iseligibleoption
,CAST(programcapid AS VARCHAR) AS programcapid
,CAST(primaryname AS VARCHAR) AS primaryname
,CAST(primaryemail AS VARCHAR) AS primaryemail
,CAST(primarygenderid AS VARCHAR) AS primarygenderid
,CAST(primarymemberdesignation AS VARCHAR) AS primarymemberdesignation
,CAST(primarymobilecountryprefix AS VARCHAR) AS primarymobilecountryprefix
,CAST(primarymobilenumber AS VARCHAR) AS primarymobilenumber
,CAST(secondaryname AS VARCHAR) AS secondaryname
,CAST(secondaryemail AS VARCHAR) AS secondaryemail
,CAST(secondarygenderid AS VARCHAR) AS secondarygenderid
,CAST(secondarymemberdesignation AS VARCHAR) AS secondarymemberdesignation
,CAST(secondarymobilecountryprefix AS VARCHAR) AS secondarymobilecountryprefix
,CAST(secondarymobilenumber AS VARCHAR) AS secondarymobilenumber
,CAST(programgroupid AS VARCHAR) AS programgroupid
,CAST(applicationstepid AS VARCHAR) AS applicationstepid
,CAST(step1completed AS VARCHAR) AS step1completed
,CAST(step2completed AS VARCHAR) AS step2completed
,CAST(step3completed AS VARCHAR) AS step3completed
,CAST(createdby AS VARCHAR) AS createdby
,CAST(createdon AS VARCHAR) AS createdon
,CAST(updatedby AS VARCHAR) AS updatedby
,CAST(updatedon AS VARCHAR) AS updatedon
,CAST(userid AS VARCHAR) AS userid
,CAST(programid AS VARCHAR) AS programid
,CAST(applicationtypeid AS VARCHAR) AS applicationtypeid
,CAST(applicationloanstatusid AS VARCHAR) AS applicationloanstatusid
,CAST(applicationapprovaltypeid AS VARCHAR) AS applicationapprovaltypeid
,CAST(approverid AS VARCHAR) AS approverid
,CAST(assessorid AS VARCHAR) AS assessorid
,CAST(rmid AS VARCHAR) AS rmid
,CAST(payabletoid AS VARCHAR) AS payabletoid
,CAST(identifier AS VARCHAR) AS identifier
,CAST(commercialname AS VARCHAR) AS commercialname
,CAST(cr AS VARCHAR) AS cr
,CAST(contractstartdate AS VARCHAR) AS contractstartdate
,CAST(contractenddate AS VARCHAR) AS contractenddate
,CAST(spendingperiodenddate AS VARCHAR) AS spendingperiodenddate
,CAST(financingapprovedon AS VARCHAR) AS financingapprovedon
,CAST(assessorrecomendation AS VARCHAR) AS assessorrecomendation
,CAST(approverdecision AS VARCHAR) AS approverdecision
,CAST(isgrantapproved AS VARCHAR) AS isgrantapproved
,CAST(isinterestedinfinancing AS VARCHAR) AS isinterestedinfinancing
,CAST(isfinancingapproved AS VARCHAR) AS isfinancingapproved
,CAST(financingcontractstartdate AS VARCHAR) AS financingcontractstartdate
,CAST(financingcontractenddate AS VARCHAR) AS financingcontractenddate
,CAST(isaccordingtomoldirection AS VARCHAR) AS isaccordingtomoldirection
,CAST(crmref AS VARCHAR) AS crmref
,CAST(crmentity AS VARCHAR) AS crmentity
,CAST(applicationtype AS VARCHAR) AS applicationtype
,CAST(approver_name AS VARCHAR) AS approver_name
,CAST(assessor_name AS VARCHAR) AS assessor_name
--rmname
,CAST(is_deleted AS VARCHAR) AS is_deleted
,CAST(tmkn_maincompany AS VARCHAR) AS tmkn_maincompany
,CAST(tmkn_maincompanyname AS VARCHAR) AS tmkn_maincompanyname
,CAST(tmkn_branchname AS VARCHAR) AS tmkn_branchname
,CAST(tmkn_name AS VARCHAR) AS tmkn_name
,CAST(tmkn_applicantname AS VARCHAR) AS tmkn_applicantname
,CAST(tmkn_applicationdate AS VARCHAR) AS tmkn_applicationdate
,CAST(tmkn_effectivedate AS VARCHAR) AS tmkn_effectivedate
,CAST(tmkn_submittedon AS VARCHAR) AS tmkn_submittedon
,CAST(tmkn_approvedon AS VARCHAR) AS tmkn_approvedon
,CAST(tmkn_confirmedon AS VARCHAR) AS tmkn_confirmedon
,CAST(tmkn_estdateidle AS VARCHAR) AS tmkn_estdateidle
,CAST(tmkn_contractstartdate AS VARCHAR) AS tmkn_contractstartdate
,CAST(tmkn_contractenddate AS VARCHAR) AS tmkn_contractenddate
,CAST(tmkn_monitoringduedate AS VARCHAR) AS tmkn_monitoringduedate
,CAST(tmkn_billforthemonth AS VARCHAR) AS tmkn_billforthemonth
,CAST(tmkn_opperiodfrom AS VARCHAR) AS tmkn_opperiodfrom
,CAST(tmkn_opperiodto AS VARCHAR) AS tmkn_opperiodto
,CAST(tmkn_crregistrationdate AS VARCHAR) AS tmkn_crregistrationdate
,CAST(tmkn_crexpirydate AS VARCHAR) AS tmkn_crexpirydate
,CAST(tmkn_primarysmartcardexpirydate AS VARCHAR) AS tmkn_primarysmartcardexpirydate
,CAST(tmkn_authorizedsmartcardexpirydate AS VARCHAR) AS tmkn_authorizedsmartcardexpirydate
,CAST(tmkn_financialsyeart1 AS VARCHAR) AS tmkn_financialsyeart1
,CAST(tmkn_financialsyeart2 AS VARCHAR) AS tmkn_financialsyeart2
,CAST(tmkn_productservice AS VARCHAR) AS tmkn_productservice
,CAST(tmkn_crnumbermain AS VARCHAR) AS tmkn_crnumbermain
,CAST(tmkn_commercialnamear AS VARCHAR) AS tmkn_commercialnamear
,CAST(tmkn_primarycpr AS VARCHAR) AS tmkn_primarycpr
,CAST(tmkn_primaryfirstname AS VARCHAR) AS tmkn_primaryfirstname
,CAST(tmkn_primarylastname AS VARCHAR) AS tmkn_primarylastname
,CAST(tmkn_primarynationalityname AS VARCHAR) AS tmkn_primarynationalityname
,CAST(tmkn_authorizedfirstname AS VARCHAR) AS tmkn_authorizedfirstname
,CAST(tmkn_authorizedlastname AS VARCHAR) AS tmkn_authorizedlastname
,CAST(tmkn_authorizedemail AS VARCHAR) AS tmkn_authorizedemail
,CAST(tmkn_authorizedcpr AS VARCHAR) AS tmkn_authorizedcpr
,CAST(tmkn_authorizedmobilenumber AS VARCHAR) AS tmkn_authorizedmobilenumber
,CAST(tmkn_iban AS VARCHAR) AS tmkn_iban
,CAST(tmkn_revenuey1 AS VARCHAR) AS tmkn_revenuey1
,CAST(tmkn_revenuey2 AS VARCHAR) AS tmkn_revenuey2
,CAST(tmkn_revenuepctdifference AS VARCHAR) AS tmkn_revenuepctdifference
,CAST(tmkn_grossprofity1 AS VARCHAR) AS tmkn_grossprofity1
,CAST(tmkn_grossprofity2 AS VARCHAR) AS tmkn_grossprofity2
,CAST(tmkn_grossprofitmarginyr1 AS VARCHAR) AS tmkn_grossprofitmarginyr1
,CAST(tmkn_grossprofitmarginyr2 AS VARCHAR) AS tmkn_grossprofitmarginyr2
,CAST(tmkn_grossprofitpctdifference AS VARCHAR) AS tmkn_grossprofitpctdifference
,CAST(tmkn_grossprofitmargindifference AS VARCHAR) AS tmkn_grossprofitmargindifference
,CAST(tmkn_netprofity1 AS VARCHAR) AS tmkn_netprofity1
,CAST(tmkn_netprofity2 AS VARCHAR) AS tmkn_netprofity2
,CAST(tmkn_netprofitmarginyr1 AS VARCHAR) AS tmkn_netprofitmarginyr1
,CAST(tmkn_netprofitmarginyr2 AS VARCHAR) AS tmkn_netprofitmarginyr2
,CAST(tmkn_netprofitpctdifference AS VARCHAR) AS tmkn_netprofitpctdifference
,CAST(tmkn_netprofitmargindifference AS VARCHAR) AS tmkn_netprofitmargindifference
,CAST(tmkn_cogsy1 AS VARCHAR) AS tmkn_cogsy1
,CAST(tmkn_cogsy2 AS VARCHAR) AS tmkn_cogsy2
,CAST(tmkn_cogspctdifference AS VARCHAR) AS tmkn_cogspctdifference
,CAST(tmkn_totalassetsy1 AS VARCHAR) AS tmkn_totalassetsy1
,CAST(tmkn_totalassetsy2 AS VARCHAR) AS tmkn_totalassetsy2
,CAST(tmkn_totalassetspctdifference AS VARCHAR) AS tmkn_totalassetspctdifference
,CAST(tmkn_fixedassetsy1 AS VARCHAR) AS tmkn_fixedassetsy1
,CAST(tmkn_fixedassetsy2 AS VARCHAR) AS tmkn_fixedassetsy2
,CAST(tmkn_fixedassetspctdifference AS VARCHAR) AS tmkn_fixedassetspctdifference
,CAST(tmkn_currentassetsy1 AS VARCHAR) AS tmkn_currentassetsy1
,CAST(tmkn_currentassetsy2 AS VARCHAR) AS tmkn_currentassetsy2
,CAST(tmkn_currentassestspctdifference AS VARCHAR) AS tmkn_currentassestspctdifference
,CAST(tmkn_currentliabilitiesy1 AS VARCHAR) AS tmkn_currentliabilitiesy1
,CAST(tmkn_currentliabilitiesy2 AS VARCHAR) AS tmkn_currentliabilitiesy2
,CAST(tmkn_currentliabilitiespctdifference AS VARCHAR) AS tmkn_currentliabilitiespctdifference
,CAST(tmkn_noncurrentliabilitiesy1 AS VARCHAR) AS tmkn_noncurrentliabilitiesy1
,CAST(tmkn_noncurrentliabilitiesy2 AS VARCHAR) AS tmkn_noncurrentliabilitiesy2
,CAST(tmkn_noncurrentliabilitiespctdifference AS VARCHAR) AS tmkn_noncurrentliabilitiespctdifference
,CAST(tmkn_ownersequityy1 AS VARCHAR) AS tmkn_ownersequityy1
,CAST(tmkn_ownersequityy2 AS VARCHAR) AS tmkn_ownersequityy2
,CAST(tmkn_ownersequitypctdifference AS VARCHAR) AS tmkn_ownersequitypctdifference
,CAST(tmkn_totalliabilitiesownersequityy1 AS VARCHAR) AS tmkn_totalliabilitiesownersequityy1
,CAST(tmkn_totalliabilitiesownersequityy2 AS VARCHAR) AS tmkn_totalliabilitiesownersequityy2
,CAST(tmkn_totalliabilitiesandownersequitypctdiffere AS VARCHAR) AS tmkn_totalliabilitiesandownersequitypctdiffere
,CAST(tmkn_consolidatedratio AS VARCHAR) AS tmkn_consolidatedratio
,CAST(tmkn_scoringmodelbusiness AS VARCHAR) AS tmkn_scoringmodelbusiness
,CAST(tmkn_scoringmodelentrepreneur AS VARCHAR) AS tmkn_scoringmodelentrepreneur
,CAST(tmkn_scoringmodelfinancials AS VARCHAR) AS tmkn_scoringmodelfinancials
,CAST(tmkn_scoringmodelindustry AS VARCHAR) AS tmkn_scoringmodelindustry
,CAST(tmkn_grantcurrentbahrainizationrate AS VARCHAR) AS tmkn_grantcurrentbahrainizationrate
,CAST(tmkn_gbahrainizationresult AS VARCHAR) AS tmkn_gbahrainizationresult
,CAST(tmkn_humancapitalgrantpercentage AS VARCHAR) AS tmkn_humancapitalgrantpercentage
,CAST(tmkn_humancapitalgrant AS VARCHAR) AS tmkn_humancapitalgrant
,CAST(tmkn_gnoofbahemployees AS VARCHAR) AS tmkn_gnoofbahemployees
,CAST(tmkn_gnoofnonbahemployees AS VARCHAR) AS tmkn_gnoofnonbahemployees
,CAST(tmkn_noofdisabledbahrainis AS VARCHAR) AS tmkn_noofdisabledbahrainis
,CAST(tmkn_gnoofemployees AS VARCHAR) AS tmkn_gnoofemployees
,CAST(tmkn_totalworkers AS VARCHAR) AS tmkn_totalworkers
,CAST(tmkn_noofmonthsinoperations AS VARCHAR) AS tmkn_noofmonthsinoperations
,CAST(tmkn_siototalbahrainino AS VARCHAR) AS tmkn_siototalbahrainino
,CAST(tmkn_siototalexpatriatesno AS VARCHAR) AS tmkn_siototalexpatriatesno
,CAST(tmkn_totalemployeesallcrs AS VARCHAR) AS tmkn_totalemployeesallcrs
,CAST(tmkn_netexports AS VARCHAR) AS tmkn_netexports
,CAST(tmkn_totalbas AS VARCHAR) AS tmkn_totalbas
,CAST(tmkn_consumedbas AS VARCHAR) AS tmkn_consumedbas
,CAST(tmkn_availablebas AS VARCHAR) AS tmkn_availablebas
,CAST(tmkn_oldtotalbas AS VARCHAR) AS tmkn_oldtotalbas
,CAST(tmkn_oldconsumedbas AS VARCHAR) AS tmkn_oldconsumedbas
,CAST(tmkn_oldavailablebas AS VARCHAR) AS tmkn_oldavailablebas
,CAST(tmkn_totaltap AS VARCHAR) AS tmkn_totaltap
,CAST(tmkn_consumedtap AS VARCHAR) AS tmkn_consumedtap
,CAST(tmkn_availabletap AS VARCHAR) AS tmkn_availabletap
,CAST(tmkn_totalbds AS VARCHAR) AS tmkn_totalbds
,CAST(tmkn_consumedbds AS VARCHAR) AS tmkn_consumedbds
,CAST(tmkn_availablebds AS VARCHAR) AS tmkn_availablebds
,CAST(tmkn_totalqms AS VARCHAR) AS tmkn_totalqms
,CAST(tmkn_consumedqms AS VARCHAR) AS tmkn_consumedqms
,CAST(tmkn_availableqms AS VARCHAR) AS tmkn_availableqms
,CAST(tmkn_totalict AS VARCHAR) AS tmkn_totalict
,CAST(tmkn_consumedict AS VARCHAR) AS tmkn_consumedict
,CAST(tmkn_availableict AS VARCHAR) AS tmkn_availableict
,CAST(tmkn_totalmas AS VARCHAR) AS tmkn_totalmas
,CAST(tmkn_consumedmas AS VARCHAR) AS tmkn_consumedmas
,CAST(tmkn_availablemas AS VARCHAR) AS tmkn_availablemas
,CAST(tmkn_totalgap AS VARCHAR) AS tmkn_totalgap
,CAST(tmkn_consumedgap AS VARCHAR) AS tmkn_consumedgap
,CAST(tmkn_availablegap AS VARCHAR) AS tmkn_availablegap
,CAST(tmkn_totalccs AS VARCHAR) AS tmkn_totalccs
,CAST(tmkn_consumedccs AS VARCHAR) AS tmkn_consumedccs
,CAST(tmkn_availableccs AS VARCHAR) AS tmkn_availableccs
,CAST(tmkn_actplangrant AS VARCHAR) AS tmkn_actplangrant
,CAST(tmkn_actpaidamount AS VARCHAR) AS tmkn_actpaidamount
,CAST(tmkn_plangrant AS VARCHAR) AS tmkn_plangrant
,CAST(tmkn_ppe_2022 AS VARCHAR) AS tmkn_ppe_2022
,CAST(tmkn_ppe_2023 AS VARCHAR) AS tmkn_ppe_2023
,CAST(tmkn_ppe_2024 AS VARCHAR) AS tmkn_ppe_2024
,CAST(tmkn_capex_2022 AS VARCHAR) AS tmkn_capex_2022
,CAST(tmkn_capex_2023 AS VARCHAR) AS tmkn_capex_2023
,CAST(tmkn_capex_2024 AS VARCHAR) AS tmkn_capex_2024
--source_system_name
--dbt_updated_at
	from 
	dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".APPLICATION_BASE
)

-- ✅ COUNT VALIDATION
SELECT 'COUNT_VALIDATION', COUNT(*), (SELECT COUNT(*) FROM silver_layer)
FROM bronze_layer




