WITH bronze_layer AS (
    SELECT
 ID
,REFERENCENUMBER
,SURVEYYEAR
,APPLICATIONID
,APPLICATIOMONITORINGSTATUSID
,PROCESSID
,FINANCIALRECORDTYPEID
,MONTHID
,ENTERPRISEAUDITEDTYPEID
,FOLLOWUPDATE
,ID
,APPLICATIONID
--,REPORTINGYEAR
--,APPLICATIONMONITORINGID
--,[YEAR]
--,REVENUE
--,DIRECTCOST
--,GROSSPROFIT
--,OVERHEAD
--,NETPROFIT
--,ISACTIVE
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_765_APPLICATIONMONITORING

    ),

silver_layer AS (
select
ID
,REFERENCENUMBER
,SURVEYYEAR
,APPLICATIONID
,APPLICATIOMONITORINGSTATUSID
,PROCESSID
--,FINANCIALRECORDTYPEID
,MONTHID
,ENTERPRISEAUDITEDTYPEID
,FOLLOWUPDATE
,ID
,APPLICATIONID
--,REPORTINGYEAR
--,APPLICATIONMONITORINGID
--,[year]
--,REVENUE
--,DIRECTCOST
--,GROSSPROFIT
--,OVERHEAD
--,NETPROFIT
--,ISACTIVE
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".APPLICATION_MONITORING_BASE

)

-- 🔍 FINAL COMPARISON
SELECT 'BRONZE_NOT_IN_SILVER' AS diff_type, *
FROM bronze_layer

EXCEPT

SELECT 'BRONZE_NOT_IN_SILVER', *
FROM silver_layer

UNION ALL

SELECT 'SILVER_NOT_IN_BRONZE' AS diff_type, *
FROM silver_layer

EXCEPT

SELECT 'SILVER_NOT_IN_BRONZE', *
FROM bronze_layer;