WITH source_cte AS (
    SELECT
        ae.ID,
        ae.CODE,
        ae.NAME,
        ae.MOLCODE,
        ae.CUSTOMERID,
        ae.NAMEAR,
        ae.DISPLAYNAME,
        ae.DISPLAYNAMEAR,
        ae.LOCATION,
        ae.ADDRESS,
        ae.MOBILECOUNTRYPREFIX,
        ae.MOBILENUMBER,
        ae.EMAILADRESS,
        ae.DESCRIPTION,
        ae.ONLINEPRESENCE,
        ae.DESCRIPTIONAR,
        ae.LOCATIONAR,
        ae.VACANCIES,
        ae.CREATEDON,
        ae.UPDATEDON,
        pt.LABEL  AS PROFILETYPEID,
        st.LABEL  AS AUTHORIZEDENTITIESSTATUS,
        pst.LABEL AS PARTNERSHIPSUBTYPE,
        ROW_NUMBER() OVER (
            PARTITION BY ae.ID
            ORDER BY ae.CREATEDON DESC, ae.UPDATEDON DESC
        ) AS RNK
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_GUR_AUTHORIZEDENTITIES ae

    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_ZMZ_PROFILETYPE pt
        ON pt.CODE = ae.PROFILETYPEID

    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_GUR_AUTHORIZEDENTITIESSTATUS st
        ON st.CODE = ae.STATUSID

    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_GUR_PARTNERSHIPSUBTYPE pst
        ON pst.CODE = ae.PARTNERSHIPSUBTYPEID
),

bronze_layer AS (
    SELECT
        ID, CODE, NAME, MOLCODE, CUSTOMERID,
        NAMEAR, DISPLAYNAME, DISPLAYNAMEAR,
        LOCATION, ADDRESS, MOBILECOUNTRYPREFIX, MOBILENUMBER,
        EMAILADRESS, DESCRIPTION, ONLINEPRESENCE,
        DESCRIPTIONAR, LOCATIONAR, VACANCIES,
        PROFILETYPEID, AUTHORIZEDENTITIESSTATUS, PARTNERSHIPSUBTYPE,
        CREATEDON, UPDATEDON,
        FALSE AS IS_DELETED
    FROM source_cte
    WHERE RNK = 1
),

silver_layer AS (
    SELECT
        ID, CODE, NAME, MOLCODE, CUSTOMERID,
        NAMEAR, DISPLAYNAME, DISPLAYNAMEAR,
        LOCATION, ADDRESS, MOBILECOUNTRYPREFIX, MOBILENUMBER,
        EMAILADRESS, DESCRIPTION, ONLINEPRESENCE,
        DESCRIPTIONAR, LOCATIONAR, VACANCIES,
        PROFILETYPEID, AUTHORIZEDENTITIESSTATUS, PARTNERSHIPSUBTYPE,
        CREATEDON, UPDATEDON, IS_DELETED
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".GUR_AUTHORIZED_ENTITIES_BASE
)

-- =========================================
-- VALIDATION
-- =========================================

-- 1. COUNT
SELECT 'COUNT_VALIDATION', COUNT(*), (SELECT COUNT(*) FROM silver_layer)
FROM bronze_layer

UNION ALL

-- 2. DUPLICATES
SELECT 'DUPLICATE_BRONZE', COUNT(*), NULL
FROM (SELECT id FROM bronze_layer GROUP BY id HAVING COUNT(*) > 1)

UNION ALL

SELECT 'DUPLICATE_SILVER', COUNT(*), NULL
FROM (SELECT id FROM silver_layer GROUP BY id HAVING COUNT(*) > 1)

UNION ALL

-- 3. PK NULL
SELECT 'PK_NULL_BRONZE', COUNT(*), NULL FROM bronze_layer WHERE id IS NULL
UNION ALL
SELECT 'PK_NULL_SILVER', COUNT(*), NULL FROM silver_layer WHERE id IS NULL

UNION ALL

-- 4. BRONZE NOT IN SILVER
SELECT 'BRONZE_NOT_IN_SILVER', COUNT(*), NULL
FROM (
    SELECT 
        CAST(ID AS VARCHAR),
        CAST(CODE AS VARCHAR),
        CAST(NAME AS VARCHAR),
        CAST(MOLCODE AS VARCHAR),
        CAST(CUSTOMERID AS VARCHAR),
        CAST(PROFILETYPEID AS VARCHAR),
        CAST(AUTHORIZEDENTITIESSTATUS AS VARCHAR),
        CAST(PARTNERSHIPSUBTYPE AS VARCHAR),
        CAST(UPDATEDON AS VARCHAR)
    FROM bronze_layer

    EXCEPT

    SELECT 
        CAST(ID AS VARCHAR),
        CAST(CODE AS VARCHAR),
        CAST(NAME AS VARCHAR),
        CAST(MOLCODE AS VARCHAR),
        CAST(CUSTOMERID AS VARCHAR),
        CAST(PROFILETYPEID AS VARCHAR),
        CAST(AUTHORIZEDENTITIESSTATUS AS VARCHAR),
        CAST(PARTNERSHIPSUBTYPE AS VARCHAR),
        CAST(UPDATEDON AS VARCHAR)
    FROM silver_layer
)

UNION ALL

-- 5. SILVER NOT IN BRONZE
SELECT 'SILVER_NOT_IN_BRONZE', COUNT(*), NULL
FROM (
    SELECT 
        CAST(ID AS VARCHAR),
        CAST(CODE AS VARCHAR),
        CAST(NAME AS VARCHAR),
        CAST(MOLCODE AS VARCHAR),
        CAST(CUSTOMERID AS VARCHAR),
        CAST(PROFILETYPEID AS VARCHAR),
        CAST(AUTHORIZEDENTITIESSTATUS AS VARCHAR),
        CAST(PARTNERSHIPSUBTYPE AS VARCHAR),
        CAST(UPDATEDON AS VARCHAR)
    FROM silver_layer

    EXCEPT

    SELECT 
        CAST(ID AS VARCHAR),
        CAST(CODE AS VARCHAR),
        CAST(NAME AS VARCHAR),
        CAST(MOLCODE AS VARCHAR),
        CAST(CUSTOMERID AS VARCHAR),
        CAST(PROFILETYPEID AS VARCHAR),
        CAST(AUTHORIZEDENTITIESSTATUS AS VARCHAR),
        CAST(PARTNERSHIPSUBTYPE AS VARCHAR),
        CAST(UPDATEDON AS VARCHAR)
    FROM bronze_layer
)

UNION ALL

-- 6. COLUMN MISMATCH
SELECT 'COLUMN_MISMATCH_COUNT', COUNT(*), NULL
FROM (
    SELECT *
    FROM bronze_layer b
    JOIN silver_layer s ON b.id = s.id
    WHERE
        COALESCE(CAST(b.code AS VARCHAR), '') <> COALESCE(CAST(s.code AS VARCHAR), '')
     OR COALESCE(CAST(b.name AS VARCHAR), '') <> COALESCE(CAST(s.name AS VARCHAR), '')
     OR COALESCE(CAST(b.molcode AS VARCHAR), '') <> COALESCE(CAST(s.molcode AS VARCHAR), '')
     OR COALESCE(CAST(b.customerid AS VARCHAR), '') <> COALESCE(CAST(s.customerid AS VARCHAR), '')
     OR COALESCE(CAST(b.profiletypeid AS VARCHAR), '') <> COALESCE(CAST(s.profiletypeid AS VARCHAR), '')
     OR COALESCE(CAST(b.authorizedentitiesstatus AS VARCHAR), '') <> COALESCE(CAST(s.authorizedentitiesstatus AS VARCHAR), '')
     OR COALESCE(CAST(b.partnershipsubtype AS VARCHAR), '') <> COALESCE(CAST(s.partnershipsubtype AS VARCHAR), '')
     OR COALESCE(CAST(b.updatedon AS VARCHAR), '') <> COALESCE(CAST(s.updatedon AS VARCHAR), '')
) t;