WITH bronze_layer AS (
SELECT
    id,
    paymentreferencenumber,
    paymenttovendortypeid,
    paymentrequeststatusid,
    createdon,
    totalamount,
    payeeid,
    applicationid,
    CAST(NULL AS decimal(37,8)) AS IBANID2,
    vendorname,
    ibanid,
    currency,
    paymenttypeid,
    claimedbyvendor,
    inspectionagentid,
    monitoringagentid,
    approverid,
    vendorid,
    customerid,
    submittedtocustomeron,
    paymentauditorid,
    submittedon,
    correctionteammemberid,
    approvedon,
    approvedby,
    totalitemnetcost,
    totalvataumount,
    totalitemstamkeenshare,
    totalitemsapplicantsharewvat,
    sentbacktocustomeron,
    sentbacktocustomerby,
    updatedon,
    erpbatchid,
    erpinvoiceid,
    reason,
    hcmonitoringagentid,
    isneedattention,
    paymentrequesttype,
    submissioncount,
    achievementrequestid,
    monitoringapproverid,
    supportcategory,
    trainingproviderid,
    duedate,
    monitoringagentremarks,
    hcmonitoringagentreviewer,
    crmguid,
    crmref,
    crmentity,
    erp_batch,
    erp_invoice,
    payment_status,
    payment_type,
    payment_share,
    payment_request_type,
    CAST(NULL AS varchar)   AS payeetype,
    CAST(NULL AS varchar)   AS processreference,
    CAST(NULL AS decimal(37,8)) AS totalcostvalue,
    CAST(NULL AS decimal(37,8)) AS tamkeensharevalue,
    CAST(NULL AS decimal(37,8)) AS customersharevalue,
    CAST(NULL AS varchar)   AS fawateerreference,
    CAST(NULL AS boolean)   AS isbeingprocessed,
    CAST(NULL AS timestamp(6)) AS reconciliationdate,
    CAST(NULL AS varchar)   AS paymentidentifier,
    CAST(NULL AS varchar)   AS cashrequirementnumber,
    CAST(NULL AS timestamp(6)) AS lastsubmissiondate,
    CAST(NULL AS timestamp(6)) AS sendtoinforon,
    CAST(NULL AS timestamp(6)) AS processedon,
    CAST(NULL AS boolean)   AS frombank,
    CAST(NULL AS boolean)   AS issampling,
    CAST(NULL AS varchar)   AS paymentrequestparenttype,
    CAST(NULL AS varchar)   AS paymentstage,
    CAST(NULL AS varchar)   AS SUPPORTAREA,
    CAST(NULL AS varchar)   AS ELIGIBILITYSTATUS,
    CAST(NULL AS varchar)   AS AITOOLRESULT,
	CAST(NULL AS varchar)   AS MIS_PAYMENTREQID,
	--CAST(NULL AS TIMESTAMP(6)) AS CREATEDON,
    CAST(NULL AS INTEGER) AS STATECODE,
    CAST(NULL AS BOOLEAN)    AS MIS_PAYMENTPROCESSED,
    CAST(NULL AS TIMESTAMP(6)) AS MIS_SUBMITTEDFORAPPROVALON,
    CAST(NULL AS timestamp(6)) as MIS_APPROVEDON,
    CAST(NULL AS timestamp(6)) as MIS_DELIVEREDON,
    CAST(NULL AS timestamp(6)) as MIS_SUBMITTEDTOFINANCEON,
   -- CAST(NULL AS DECIMAL(19,4)) AS MIS_TOTALAMOUNT,
    CAST(NULL AS varchar) as MIS_NAME,
    CAST(NULL AS INTEGER) AS TMKN_VIOLATIONSTATUS,
    CAST(NULL AS INTEGER) AS MIS_PAYABLETO,
    CAST(NULL AS INTEGER) AS MIS_PAYMENTTYPE,
    CAST(NULL AS INTEGER) AS MIS_HASCOMMITEDTOGP,
    CAST(NULL AS BOOLEAN)    AS MIS_SENTBACKBEFORE,
    --CAST(NULL AS varchar)   AS MIS_INDIVIDUALAPPLICATIONNAME,
    CAST(NULL AS INTEGER) AS STATUSCODE,
    CAST(NULL AS varchar)   AS TMKN_ACCOUNTANT,
    CAST(NULL AS varchar)   AS TMKN_VERIFYINGUSER,
    CAST(NULL AS varchar)   AS TMKN_AUBPAYMENT,
    CAST(NULL AS varchar)   AS TMKN_GPINVOICE,
    CAST(NULL AS INTEGER) AS TMKN_FINANCEAPPROVAL,
    CAST(NULL AS varchar)   AS TMKN_FCUSER,
    CAST(NULL AS TIMESTAMP(6)) AS  TMKN_APPROVEDBYFCTIME,
    CAST(NULL AS TIMESTAMP(6)) AS TMKN_CHECKEDBYACCOUNTANT,
    CAST(NULL AS DECIMAL(19,4)) AS MIS_RECEIPTAMOUNT,
    CAST(NULL AS varchar)   AS MIS_RECEIPTNO1,
    CAST(NULL AS DECIMAL)   AS MIS_RECEIPTAMOUNT1,
    CAST(NULL AS varchar)   AS MIS_RECEIPT1DESC,
    CAST(NULL AS DECIMAL(19,4)) AS MIS_RECEIPT1TBP,
    CAST(NULL AS varchar)   AS MIS_RECEIPTNO2,
    CAST(NULL AS varchar)   AS MIS_INVOICENO1,
    CAST(NULL AS varchar)   AS OWNERID,
    CAST(NULL AS integer)   AS MIS_PAYMENTSTATUS,
    CAST(NULL AS TIMESTAMP(6)) AS TMKN_DUEDATE,
    CAST(NULL AS varchar)   AS MIS_INDIVIDUALAPPLICATION,
    'NEO1' AS SOURCE_SYSTEM_NAME
    --cast(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".payment_request_base_os1
union all
SELECT
    CAST(NULL AS BIGINT)   AS id,
    CAST(NULL AS varchar)   AS paymentreferencenumber,
    CAST(NULL AS integer)   AS paymenttovendortypeid,
    CAST(NULL AS integer)   AS paymentrequeststatusid,
    CAST(NULL AS timestamp(6)) AS createdon,
    CAST(totalcostvalue AS decimal(37,8)) AS totalamount,
    CAST(NULL AS integer)   AS payeeid,
    CAST(NULL AS BIGINT)   AS applicationid,
    CAST(NULL AS decimal(37,8)) AS IBANID2,
    CAST(NULL AS varchar)   AS vendorname,
    CAST(NULL AS bigint)    AS ibanid,
    CAST(NULL AS varchar)   AS currency,
    CAST(NULL AS integer)   AS paymenttypeid,
    CAST(NULL AS boolean)   AS claimedbyvendor,
    CAST(NULL AS integer)   AS inspectionagentid,
    CAST(NULL AS integer)   AS monitoringagentid,
    CAST(NULL AS integer)   AS approverid,
    CAST(NULL AS bigint)    AS vendorid,
    CAST(NULL AS integer)   AS customerid,
    CAST(NULL AS timestamp(6)) AS submittedtocustomeron,
    CAST(NULL AS integer)   AS paymentauditorid,
    CAST(NULL AS timestamp(6)) AS submittedon,
    CAST(NULL AS integer)   AS correctionteammemberid,
    CAST(NULL AS timestamp(6)) AS approvedon,
    CAST(NULL AS integer)   AS approvedby,
    CAST(NULL AS decimal(37,8)) AS totalitemnetcost,
    CAST(NULL AS decimal(37,8)) AS totalvataumount,
    CAST(NULL AS decimal(37,8)) AS totalitemstamkeenshare,
    CAST(NULL AS decimal(37,8)) AS totalitemsapplicantsharewvat,
    CAST(NULL AS timestamp(6)) AS sentbacktocustomeron,
    CAST(NULL AS integer)   AS sentbacktocustomerby,
    CAST(NULL AS timestamp(6)) AS updatedon,
    CAST(NULL AS bigint)    AS erpbatchid,
    CAST(NULL AS bigint)    AS erpinvoiceid,
    CAST(NULL AS varchar)   AS reason,
    CAST(NULL AS integer)   AS hcmonitoringagentid,
    CAST(NULL AS boolean)   AS isneedattention,
    CAST(NULL AS integer)   AS paymentrequesttype,
    CAST(NULL AS integer)   AS submissioncount,
    CAST(NULL AS bigint)    AS achievementrequestid,
    CAST(NULL AS integer)   AS monitoringapproverid,
    CAST(NULL AS integer)   AS supportcategory,
    CAST(NULL AS bigint)    AS trainingproviderid,
    CAST(NULL AS timestamp(6)) AS duedate,
    CAST(NULL AS varchar)   AS monitoringagentremarks,
    CAST(NULL AS integer)   AS hcmonitoringagentreviewer,
    CAST(NULL AS varchar)   AS crmguid,
    CAST(NULL AS varchar)   AS crmref,
    CAST(NULL AS varchar)   AS crmentity,
    CAST(NULL AS varchar)   AS erp_batch,
    CAST(NULL AS varchar)   AS erp_invoice,
    CAST(NULL AS varchar)   AS payment_status,
    CAST(NULL AS varchar)   AS payment_type,
    CAST(NULL AS varchar)   AS payment_share,
    CAST(NULL AS varchar)   AS payment_request_type,
    payeetype,
    processreference,
    CAST(totalcostvalue AS decimal(37,8)),
    CAST(tamkeensharevalue AS decimal(37,8)),
    CAST(customersharevalue AS decimal(37,8)),
    fawateerreference,
    isbeingprocessed,
    reconciliationdate,
    paymentidentifier,
    cashrequirementnumber,
    lastsubmissiondate,
    sendtoinforon,
    processedon,
    frombank,
    issampling,
    paymentrequestparenttype,
    paymentstage,
    SUPPORTAREA,
    ELIGIBILITYSTATUS,
    AITOOLRESULT,
	CAST(NULL AS varchar)   AS MIS_PAYMENTREQID,
	--CAST(NULL AS TIMESTAMP(6)) AS CREATEDON,
    CAST(NULL AS INTEGER) AS STATECODE,
    CAST(NULL AS BOOLEAN)    AS MIS_PAYMENTPROCESSED,
    CAST(NULL AS TIMESTAMP(6)) AS MIS_SUBMITTEDFORAPPROVALON,
    CAST(NULL AS timestamp(6)) as MIS_APPROVEDON,
    CAST(NULL AS timestamp(6)) as MIS_DELIVEREDON,
    CAST(NULL AS timestamp(6)) as MIS_SUBMITTEDTOFINANCEON,
  --  CAST(NULL AS DECIMAL(19,4)) AS MIS_TOTALAMOUNT,
    CAST(NULL AS varchar) as MIS_NAME,
    CAST(NULL AS INTEGER) AS TMKN_VIOLATIONSTATUS,
    CAST(NULL AS INTEGER) AS MIS_PAYABLETO,
    CAST(NULL AS INTEGER) AS MIS_PAYMENTTYPE,
    CAST(NULL AS INTEGER) AS MIS_HASCOMMITEDTOGP,
    CAST(NULL AS BOOLEAN)    AS MIS_SENTBACKBEFORE,
    --CAST(NULL AS varchar)   AS MIS_INDIVIDUALAPPLICATIONNAME,
    CAST(NULL AS INTEGER) AS STATUSCODE,
    CAST(NULL AS varchar)   AS TMKN_ACCOUNTANT,
    CAST(NULL AS varchar)   AS TMKN_VERIFYINGUSER,
    CAST(NULL AS varchar)   AS TMKN_AUBPAYMENT,
    CAST(NULL AS varchar)   AS TMKN_GPINVOICE,
    CAST(NULL AS INTEGER) AS TMKN_FINANCEAPPROVAL,
    CAST(NULL AS varchar)   AS TMKN_FCUSER,
    CAST(NULL AS TIMESTAMP(6)) AS  TMKN_APPROVEDBYFCTIME,
    CAST(NULL AS TIMESTAMP(6)) AS TMKN_CHECKEDBYACCOUNTANT,
    CAST(NULL AS DECIMAL(19,4)) AS MIS_RECEIPTAMOUNT,
    CAST(NULL AS varchar)   AS MIS_RECEIPTNO1,
    CAST(NULL AS DECIMAL)   AS MIS_RECEIPTAMOUNT1,
    CAST(NULL AS varchar)   AS MIS_RECEIPT1DESC,
    CAST(NULL AS DECIMAL(19,4)) AS MIS_RECEIPT1TBP,
    CAST(NULL AS varchar)   AS MIS_RECEIPTNO2,
    CAST(NULL AS varchar)   AS MIS_INVOICENO1,
    CAST(NULL AS varchar)   AS OWNERID,
    CAST(NULL AS integer)   AS MIS_PAYMENTSTATUS,
    CAST(NULL AS TIMESTAMP(6)) AS TMKN_DUEDATE,
    CAST(NULL AS varchar)   AS MIS_INDIVIDUALAPPLICATION,
    'NEO2' AS SOURCE_SYSTEM_NAME
    --cast(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".payment_request_base_os2
UNION ALL
SELECT
    CAST(NULL AS bigint)    AS id,
    CAST(NULL AS varchar)   AS paymentreferencenumber,
    CAST(NULL AS integer)   AS paymenttovendortypeid,
    CAST(NULL AS integer)   AS paymentrequeststatusid,
    CAST(NULL AS timestamp(6)) AS createdon,
    CAST(NULL AS decimal(37,8)) AS totalamount,
    CAST(NULL AS integer)   AS payeeid,
    CAST(NULL AS bigint)   AS applicationid,
    CAST(NULL AS decimal)   AS IBANID2,
    CAST(NULL AS varchar)   AS vendorname,
    CAST(NULL AS bigint)    AS ibanid,
    CAST(NULL AS varchar)   AS currency,
    CAST(NULL AS integer)   AS paymenttypeid,
    CAST(NULL AS boolean)   AS claimedbyvendor,
    CAST(NULL AS integer)   AS inspectionagentid,
    CAST(NULL AS integer)   AS monitoringagentid,
    CAST(NULL AS integer)   AS approverid,
    CAST(NULL AS bigint)    AS vendorid,
    CAST(NULL AS integer)   AS customerid,
    CAST(NULL AS timestamp(6)) AS submittedtocustomeron,
    CAST(NULL AS integer)   AS paymentauditorid,
    CAST(NULL AS timestamp(6)) AS submittedon,
    CAST(NULL AS integer)   AS correctionteammemberid,
    CAST(NULL AS timestamp(6)) AS approvedon,
    CAST(NULL AS integer)   AS approvedby,
    CAST(NULL AS decimal(37,8)) AS totalitemnetcost,
    CAST(NULL AS decimal(37,8)) AS totalvataumount,
    CAST(NULL AS decimal(37,8)) AS totalitemstamkeenshare,
    CAST(NULL AS decimal(37,8)) AS totalitemsapplicantsharewvat,
    CAST(NULL AS timestamp(6)) AS sentbacktocustomeron,
    CAST(NULL AS integer)   AS sentbacktocustomerby,
    CAST(NULL AS timestamp(6)) AS updatedon,
    CAST(NULL AS bigint)    AS erpbatchid,
    CAST(NULL AS bigint)    AS erpinvoiceid,
    CAST(NULL AS varchar)   AS reason,
    CAST(NULL AS integer)   AS hcmonitoringagentid,
    CAST(NULL AS boolean)   AS isneedattention,
    CAST(NULL AS integer)   AS paymentrequesttype,
    CAST(NULL AS integer)   AS submissioncount,
    CAST(NULL AS bigint)    AS achievementrequestid,
    CAST(NULL AS integer)   AS monitoringapproverid,
    CAST(NULL AS integer)   AS supportcategory,
    CAST(NULL AS bigint)    AS trainingproviderid,
    CAST(NULL AS timestamp(6)) AS duedate,
    CAST(NULL AS varchar)   AS monitoringagentremarks,
    CAST(NULL AS integer)   AS hcmonitoringagentreviewer,
    CAST(NULL AS varchar)   AS crmguid,
    CAST(NULL AS varchar)   AS crmref,
    CAST(NULL AS varchar)   AS crmentity,
    CAST(NULL AS varchar)   AS erp_batch,
    CAST(NULL AS varchar)   AS erp_invoice,
    CAST(NULL AS varchar) AS payment_status,
    CAST(NULL AS varchar)  AS payment_type,
    CAST(NULL AS varchar)   AS payment_share,
    CAST(NULL AS varchar)   AS payment_request_type,
    CAST(NULL AS varchar)   AS payeetype,
    CAST(NULL AS varchar)   AS processreference,
    CAST(NULL AS decimal(37,8)) as totalcostvalue,
    CAST(NULL AS decimal(37,8)) as tamkeensharevalue,
    CAST(NULL AS decimal(37,8)) as customersharevalue,
    CAST(NULL AS varchar)   AS fawateerreference,
    CAST(NULL AS BOOLEAN)   AS isbeingprocessed,
    CAST(NULL AS timestamp(6)) AS reconciliationdate,
    CAST(NULL AS varchar)   AS paymentidentifier,
    CAST(NULL AS varchar)   AS cashrequirementnumber,
    CAST(NULL AS timestamp(6)) AS lastsubmissiondate,
    CAST(NULL AS timestamp(6)) AS sendtoinforon,
    CAST(NULL AS timestamp(6)) AS processedon,
    CAST(NULL AS BOOLEAN)   AS frombank,
    CAST(NULL AS BOOLEAN)   AS issampling,
    CAST(NULL AS varchar)   AS paymentrequestparenttype,
    CAST(NULL AS varchar)   AS paymentstage,
    CAST(NULL AS varchar)   AS SUPPORTAREA,
    CAST(NULL AS varchar)   AS ELIGIBILITYSTATUS,
    CAST(NULL AS varchar)   AS AITOOLRESULT,
	CAST( MIS_PAYMENTREQID AS varchar)   as MIS_PAYMENTREQID,
    --CAST(CREATEDON AS timestamp(6)) as CREATEDON,
    CAST(STATECODE AS integer)   as STATECODE,
    CAST(MIS_PAYMENTPROCESSED AS BOOLEAN)   as MIS_PAYMENTPROCESSED,
    CAST(MIS_SUBMITTEDFORAPPROVALON AS timestamp(6)) as MIS_SUBMITTEDFORAPPROVALON,
    CAST(MIS_APPROVEDON AS timestamp(6)) as MIS_APPROVEDON,
    CAST(MIS_DELIVEREDON AS timestamp(6)) as MIS_DELIVEREDON,
    CAST(MIS_SUBMITTEDTOFINANCEON AS timestamp(6)) as MIS_SUBMITTEDTOFINANCEON,
  --  CAST(MIS_TOTALAMOUNT AS DECIMAL) as MIS_TOTALAMOUNT,
    CAST(MIS_NAME AS VARCHAR) as MIS_NAME,
    CAST(TMKN_VIOLATIONSTATUS AS INTEGER) AS TMKN_VIOLATIONSTATUS,
    CAST(MIS_PAYABLETO AS INTEGER) AS MIS_PAYABLETO,
    CAST(MIS_PAYMENTTYPE AS INTEGER) AS MIS_PAYMENTTYPE,
    CAST(MIS_HASCOMMITEDTOGP AS INTEGER) AS MIS_HASCOMMITEDTOGP,
    CAST(MIS_SENTBACKBEFORE AS BOOLEAN) AS MIS_SENTBACKBEFORE,
    --MIS_INDIVIDUALAPPLICATIONNAME,
    CAST(STATUSCODE AS INTEGER) AS STATUSCODE,
    CAST(TMKN_ACCOUNTANT AS VARCHAR)  as TMKN_ACCOUNTANT,
    CAST(TMKN_VERIFYINGUSER AS VARCHAR)  as TMKN_VERIFYINGUSER,
    CAST(TMKN_AUBPAYMENT AS VARCHAR)  as TMKN_AUBPAYMENT,
    CAST(TMKN_GPINVOICE AS VARCHAR)  as TMKN_GPINVOICE,
    CAST(NULL AS INTEGER) AS TMKN_FINANCEAPPROVAL,
    CAST(TMKN_FCUSER AS VARCHAR)  as  TMKN_FCUSER,
    CAST(TMKN_APPROVEDBYFCTIME AS timestamp(6)) AS TMKN_APPROVEDBYFCTIME,
    CAST(TMKN_CHECKEDBYACCOUNTANT AS timestamp(6)) AS TMKN_CHECKEDBYACCOUNTANT,
    CAST(MIS_RECEIPTAMOUNT AS DECIMAL)  as  MIS_RECEIPTAMOUNT,
    CAST(TMKN_FCUSER AS VARCHAR)  as  MIS_RECEIPTNO1,
    CAST(MIS_RECEIPTAMOUNT1 AS DECIMAL) AS MIS_RECEIPTAMOUNT1,
    CAST(MIS_RECEIPT1DESC AS VARCHAR)  as MIS_RECEIPT1DESC,
    CAST(MIS_RECEIPT1TBP AS DECIMAL)  as MIS_RECEIPT1TBP,
    CAST(MIS_RECEIPTNO2 AS VARCHAR)  as MIS_RECEIPTNO2,
    CAST(MIS_INVOICENO1 AS VARCHAR)  as MIS_INVOICENO1,
    CAST(OWNERID AS VARCHAR)  as OWNERID,
    CAST(MIS_PAYMENTSTATUS AS INTEGER)  as MIS_PAYMENTSTATUS,
    CAST(TMKN_DUEDATE AS timestamp(6)) as TMKN_DUEDATE,
    CAST(MIS_INDIVIDUALAPPLICATION AS VARCHAR) AS MIS_INDIVIDUALAPPLICATION,
    'MIS' AS SOURCE_SYSTEM_NAME
   -- cast(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS timestamp) AS DBT_UPDATED_AT
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".payment_request_base_mis
 ),
silver_layer AS (
    SELECT *
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".PAYMENT_REQUEST_BASE
),

-- =========================
-- VALIDATIONS
-- =========================
count_validation AS (
    SELECT 'COUNT_VALIDATION' AS check_name,
           (SELECT COUNT(*) FROM bronze_layer) AS value1,
           (SELECT COUNT(*) FROM silver_layer) AS value2
),

duplicate_bronze AS (
    SELECT 'DUPLICATE_BRONZE' AS check_name, COUNT(*) AS value1
    FROM (SELECT id FROM bronze_layer GROUP BY id HAVING COUNT(*) > 1)
),

duplicate_silver AS (
    SELECT 'DUPLICATE_SILVER' AS check_name, COUNT(*) AS value1
    FROM (SELECT id FROM silver_layer GROUP BY id HAVING COUNT(*) > 1)
),

null_bronze AS (
    SELECT 'PK_NULL_BRONZE' AS check_name, COUNT(*) AS value1
    FROM bronze_layer WHERE id IS NULL
),

null_silver AS (
    SELECT 'PK_NULL_SILVER' AS check_name, COUNT(*) AS value1
    FROM silver_layer WHERE id IS NULL
),

comparison AS (
    SELECT
        b.id,
        CASE WHEN b.totalamount = s.totalamount THEN 1 ELSE 0 END AS amount_match,
        CASE WHEN b.vendorid = s.vendorid THEN 1 ELSE 0 END AS vendor_match,
        CASE WHEN b.createdon = s.createdon THEN 1 ELSE 0 END AS created_match,
        CASE WHEN b.updatedon = s.updatedon THEN 1 ELSE 0 END AS updated_match
    FROM bronze_layer b
    JOIN silver_layer s ON b.id = s.id
),

mismatch_count AS (
    SELECT 'MISMATCH_COUNT' AS check_name, COUNT(*) AS value1
    FROM comparison
    WHERE amount_match = 0
       OR vendor_match = 0
       OR created_match = 0
       OR updated_match = 0
),

orphan_checks AS (
    SELECT 'IN_BRONZE_NOT_SILVER' AS check_name, COUNT(*) AS value1
    FROM bronze_layer b
    WHERE NOT EXISTS (SELECT 1 FROM silver_layer s WHERE s.id = b.id)

    UNION ALL

    SELECT 'IN_SILVER_NOT_BRONZE' AS check_name, COUNT(*) AS value1
    FROM silver_layer s
    WHERE NOT EXISTS (SELECT 1 FROM bronze_layer b WHERE b.id = s.id)
)

-- =========================
-- FINAL OUTPUT
-- =========================
SELECT check_name, value1, value2 FROM count_validation
UNION ALL
SELECT check_name, value1, NULL FROM duplicate_bronze
UNION ALL
SELECT check_name, value1, NULL FROM duplicate_silver
UNION ALL
SELECT check_name, value1, NULL FROM null_bronze
UNION ALL
SELECT check_name, value1, NULL FROM null_silver
UNION ALL
SELECT check_name, value1, NULL FROM mismatch_count
UNION ALL
SELECT check_name, value1, NULL FROM orphan_checks
ORDER BY check_name;