WITH source_cte AS (
    SELECT
        SC.ID,
        APPLICATIONID,
        CHEQUEREFNUMBER,
        SECURITYNUMBER,
        SECURITYAMOUNT,
        SECURITYDATE,
        B.BANKNAME AS BANKID,
        SCS.LABEL AS SECURITYCHEQUESTATUS,
        ST.LABEL AS SECURITYTYPE,
        CM.LABEL AS COLLECTIONMETHOD,
        CAST(NULL AS VARCHAR) AS OS1_COLLECTIONMETHOD,
        SL.LABEL AS SUBMITTEDLOCATION,
        CAST(NULL AS VARCHAR) AS OS1_SUBMITTEDLOCATION,
        CAST(NULL AS VARCHAR) AS REPLACEMENTSTATUS,
        CAST(NULL AS INTEGER) AS ISSUEDBY,
        CAST(NULL AS INTEGER) AS COLLECTEDTHROUGH,
        SC.CREATEDON,
        SC.UPDATEDON,
        SECURITYID,
        ISSUEDATE,
        SS.LABEL AS SECURITYSTATUS,
        SC.ISACTIVE,
        U.NAME AS CREATEDBY,
        UPDATEDBY,
        RELEASEDON,
        REPLACEDON,
        PORTALUSER,
        SCP.LABEL AS SECURITYCHEQUEPROCESSINGSTEP,
        ECPEE.LABEL AS ECHEQUEPROCESSEXTERNALEVENTS,
        RELEASEAGENTUSERID,
        RELEASECOMMENTS,
        DM.LABEL AS DELIVERYMETHOD,
        COLLECTORCPR,
        COLLECTORNAME,
        CRTE.LABEL AS COLLECTORSRELATIONSHIPTOENTE,
        FALSE AS IS_DELETED,
        'NEO2' AS SOURCE_SYSTEM_NAME,
        CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) AS DBT_UPDATED_AT,
        ROW_NUMBER() OVER (
            PARTITION BY SC.ID 
            ORDER BY SC.UPDATEDON DESC, SC.CREATEDON DESC
        ) AS RNK
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_SECURITYCHEQUE SC

    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_COLLECTIONMETHOD CM
        ON SC.COLLECTIONMETHODID = CM.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_SECURITYTYPE ST
        ON SC.SECURITYTYPEID = ST.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_TLV_BANK B
        ON SC.BANKID = B.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_SUBMITTEDLOCATION SL
        ON SC.SUBMITTEDLOCATIONID = SL.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_SECURITYSTATUS SS
        ON SC.SECURITYSTATUSID = SS.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSSYS_USER U
        ON SC.CREATEDBY = U.USERNAME
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_SECURITYCHEQUESTATUS SCS
        ON SC.SECURITYCHEQUESTATUS = SCS.CODE
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_SECURITYCHEQUEPROCESSINGSTEP SCP
        ON SC.SECURITYCHEQUEPROCESSINGSTEP = SCP.CODE
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_ECHEQUEPROCESSEXTERNALEVENTS ECPEE
        ON SC.ECHEQUEPROCESSEXTERNALEVENTS = ECPEE.CODE
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_DELIVERYMETHOD1 DM
        ON SC.DELIVERYMETHODID = DM.ID
    LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_5HX_COLLECTORSRELATIONSHIPTOENTERPRISE2 CRTE
        ON SC.COLLECTORSRELATIONSHIPTOENTE = CRTE.CODE
),

bronze_layer AS (

    SELECT * FROM (

        -- NEO1
        SELECT
            SC.ID,
            APPLICATIONID,
            CHEQUEID,
            CAST(CHEQUENUMBER AS VARCHAR),
            CHEQUEAMOUNT,
            CHEQUEDATE,
            BANKNAMES.LABEL,
            SQ.LABEL,
            SCQ.LABEL,
            CAST(NULL AS VARCHAR),
            CAST(NULL AS VARCHAR),
            CAST(SUBMITTEDBRANCHLOCATION AS VARCHAR),
            CAST(SUBMITTEDBRANCHLOCATION AS VARCHAR),
            SCRS.LABEL,
            ISSUEDBY,
            COLLECTEDTHROUGH,
            CREATIONDATETIME,
            UPDATEDDATETIME,
            CAST(NULL AS VARCHAR),
            CAST('1900-01-01' AS DATE),
            CAST(NULL AS VARCHAR),
            CAST(FALSE AS BOOLEAN),
            CAST(NULL AS VARCHAR),
            CAST(NULL AS VARCHAR),
            CAST('1900-01-01' AS DATE),
            CAST('1900-01-01' AS DATE),
            CAST(NULL AS INTEGER),
            CAST(NULL AS VARCHAR),
            CAST(NULL AS VARCHAR),
            CAST(NULL AS INTEGER),
            CAST(NULL AS VARCHAR),
            CAST(NULL AS VARCHAR),
            CAST(NULL AS VARCHAR),
            CAST(NULL AS VARCHAR),
            CAST(NULL AS VARCHAR),
            FALSE,
            'NEO1',
            CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)

        FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_PX1_SECURITYCHEQUE SC
        LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_PX1_BANKNAMES BANKNAMES
            ON BANKNAMES.ID = SC.BANKID
        LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_PX1_SECURITYCHEQUESTATUS SQ
            ON SQ.ID = SC.STATUSID
        LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_PX1_SECURITYCHEQUETYPE SCQ
            ON SCQ.ID = SC.CHEQUETYPEID
        LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_PX1_SECURITYCHEQUECOLLECTIONMETHOD SCQM
            ON SCQM.ID = SC.COLLECTIONMETHODID
        LEFT JOIN dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".OSUSR_PX1_SECURITYCHEQUEREPLACEMENTSTATUS SCRS
            ON SCRS.ID = SC.ID

        UNION ALL

        -- NEO2
        SELECT
            ID, APPLICATIONID, CHEQUEREFNUMBER, SECURITYNUMBER, SECURITYAMOUNT,
            SECURITYDATE, BANKID, SECURITYCHEQUESTATUS, SECURITYTYPE,
            COLLECTIONMETHOD, OS1_COLLECTIONMETHOD, SUBMITTEDLOCATION,
            OS1_SUBMITTEDLOCATION, REPLACEMENTSTATUS, ISSUEDBY,
            COLLECTEDTHROUGH, CREATEDON, UPDATEDON, SECURITYID,
            ISSUEDATE, SECURITYSTATUS, ISACTIVE, CREATEDBY,
            UPDATEDBY, RELEASEDON, REPLACEDON, PORTALUSER,
            SECURITYCHEQUEPROCESSINGSTEP, ECHEQUEPROCESSEXTERNALEVENTS,
            RELEASEAGENTUSERID, RELEASECOMMENTS, DELIVERYMETHOD,
            COLLECTORCPR, COLLECTORNAME, COLLECTORSRELATIONSHIPTOENTE,
            IS_DELETED, SOURCE_SYSTEM_NAME, DBT_UPDATED_AT
        FROM source_cte
        WHERE RNK = 1

    )

),

silver_layer AS (
    SELECT * 
    FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".SECURITY_CHEQUE_BASE
)

-- =========================================
-- FINAL VALIDATION
-- =========================================

SELECT 'COUNT_VALIDATION', COUNT(*), (SELECT COUNT(*) FROM silver_layer)
FROM bronze_layer

UNION ALL

SELECT 'DUPLICATE_BRONZE', COUNT(*), NULL
FROM (SELECT id FROM bronze_layer GROUP BY id HAVING COUNT(*) > 1)

UNION ALL

SELECT 'DUPLICATE_SILVER', COUNT(*), NULL
FROM (SELECT id FROM silver_layer GROUP BY id HAVING COUNT(*) > 1)

UNION ALL

SELECT 'COLUMN_MISMATCH_COUNT', COUNT(*), NULL
FROM (
    SELECT *
    FROM bronze_layer b
    JOIN silver_layer s ON b.id = s.id
    WHERE
        COALESCE(CAST(b.applicationid AS VARCHAR), '') <> COALESCE(CAST(s.applicationid AS VARCHAR), '')
        --OR COALESCE(CAST(b.chequerefnumber AS VARCHAR), '') <> COALESCE(CAST(s.chequerefnumber AS VARCHAR), '')
) t

UNION ALL

SELECT 'BRONZE_NOT_IN_SILVER', COUNT(*), NULL
FROM (
    SELECT * FROM bronze_layer
    EXCEPT
    SELECT * FROM silver_layer
) t

UNION ALL

SELECT 'SILVER_NOT_IN_BRONZE', COUNT(*), NULL
FROM (
    SELECT * FROM silver_layer
    EXCEPT
    SELECT * FROM bronze_layer
) t;