SELECT
    extract_date,
    project_id,
    project_name,
    program_name,
    application_no,
    cpr,
    indvidual_name,
    gender,
    date_of_birth,
    individual_segment,
    highest_education_qualification,
    specialization,
    gradudation_date,
    whitelisting,
    approved as is_approved,
    decision_date_approved_on_or_rejected_on as decision_date,
    type_of_opportunity,
    mobile,
    office,
    email,
    first_joining_date,
    joining_date_current,
    cr_license_no_current,
    commercial_name_current,
    job_title_current,
    salary_current,
    total_months_of_work_experience,
    joining_date_new_placement,
    cr_license_no_new_placement,
    commercial_name_new_placement,
    job_title_new_placement,
    placement_location,
    placement_region,
    placement_country,
    wage_support_type,
    total_monthly_offer_bhd,
    months_of_support,
    subsidy,
    total_monthly_subsidy_bhd_tamkeen as total_monthly_subsidy_tamkeen,
    total_salary_support_bhd_tamkeen as total_salary_support_tamkeen,
    travelcap_amount as travel_cap,
    travelactual_amount as travel_actual,
    travel_tamkeen_support as travel_support,
    visacap_amount as visa_cap,
    visaactual_amount as visa_actual  ,
    visa_tamkeen_support as visa_support,
    accommodationcap_amount as accommodation_cap,
    accommodationactual_amount as accommodation_actual,
    accommodationtamkeen_support as accommodation_support,
    transportcap_amount as transport_cap,
    transportactual_amount as transport_actual, 
    transport_tamkeen_support as transport_support,
    per_diemcap_amount as per_diem_cap,
    per_diemactual_amount as per_diem_actual,
    per_diemtamkeen_support as per_diem_support,
    program_costcap as program_cost_cap ,
    program_costactual_amount as program_cost_actual,
    program_cost_tamkeen_supprot ,
    total_support_bhd_tamkeen as total_support_tamkeen,
    start_date_wage_support ,
    end_date_wage_support ,
    joining_date_new_employment,
    cr_license_no_new_employment,
    commercial_name_new_employment,
    job_title_new_employment,
    total_offer_bhd_new_employment,
    total_months_of_experience_new_employment,
    created_on,
    created_by,
    application_format,
    approved_by,
    CAST('OFFLINE_SHEETS' AS VARCHAR) AS source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".offline_sheets_grtandgre_individuals;

SELECT
    extract_date,
    project_id,
    project_name,
    program_name,
    application_no,
    cpr,
    indvidual_name,
    gender,
    date_of_birth,
    individual_segment,
    highest_education_qualification,
    specialization,
    gradudation_date,
    whitelisting,
    is_approved,
    decision_date,
    type_of_opportunity,
    mobile,
    office,
    email,
    first_joining_date,
    joining_date_current,
    cr_license_no_current,
    commercial_name_current,
    job_title_current,
    salary_current,
    total_months_of_work_experience,
    joining_date_new_placement,
    cr_license_no_new_placement,
    commercial_name_new_placement,
    job_title_new_placement,
    placement_location,
    placement_region,
    placement_country,
    wage_support_type,
    total_monthly_offer_bhd,
    months_of_support,
    subsidy,
    total_monthly_subsidy_tamkeen,
    total_salary_support_tamkeen,
    travel_cap,
    travel_actual,
    travel_support,
    visa_cap,
    visa_actual,
    visa_support,
    accommodation_cap,
    accommodation_actual,
    accommodation_support,
    transport_cap,
    transport_actual,
    transport_support,
    per_diem_cap,
    per_diem_actual,
    per_diem_support,
    program_cost_cap,
    program_cost_actual,
    program_cost_tamkeen_support,
    total_support_tamkeen,
    start_date_wage_support,
    end_date_wage_support,
    joining_date_new_employment,
    cr_license_no_new_employment,
    commercial_name_new_employment,
    job_title_new_employment,
    total_offer_bhd_new_employment,
    total_months_of_experience_new_employment,
    created_on,
    created_by,
    application_format,
    approved_by,
    --dbt_updated_on,
    source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".offline_sheets_grtandgre_individuals;
