SELECT
    extract_date,
    job_center,
    date AS activity_date,
    walk_ins,
    walk_ins_comments_if_any AS walk_ins_comments,
    appointments_and_calls_mol_list_total AS appointments_mol_list_total,
    appointments_mol_list_virtual,
    appointments_mol_list_physical,
    appointments_and_calls_tamkeen_system_total AS appointments_tamkeen_system_total,
    appointments_tamkeen_system_virtual AS appointments_tamkeen_virtual,
    appointments_tamkeen_system_physical AS appointments_tamkeen_physical,
    appointments_comments_if_any AS appointments_comments,
    job_interviews_conducted_mol_list_total AS interviews_mol_total,
    job_interviews_conducted_mol_list_virtual AS interviews_mol_virtual,
    job_interviews_conducted_mol_list_physical AS interviews_mol_physical,
    mol_details_of_the_interviews_company_role_etc AS interviews_mol_details,
    job_interviews_conducted_tamkeen_system_total AS interviews_tamkeen_total,
    job_interviews_conducted_tamkeen_system_virtual AS interviews_tamkeen_virtual,
    job_interviews_conducted_tamkeen_system_physical AS interviews_tamkeen_physical,
    tamkeen_details_of_the_interviews_company_role_etc AS interviews_tamkeen_details,
    number_of_trainings_conducted_on_the_premises AS no_of_trainings_on_premises,
    type_of_training_subject_quality_participants_etc AS training_type_details,
    number_of_job_matches,
    issues_to_flag_in_general AS issues_to_flag,
    start_time,
    completion_time,
    email AS officer_email,
    name AS officer_name,
    id AS record_id,
    --current_timestamp AS dbt_updated_on,
    CAST('OFFLINE_SHEETS' AS VARCHAR) AS source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".offline_sheets_job_seeker_and_walkins_job_centers_details;


SELECT
    extract_date,
    job_center,
    activity_date,
    walk_ins,
    walk_ins_comments,
    appointments_mol_list_total,
    appointments_mol_list_virtual,
    appointments_mol_list_physical,
    appointments_tamkeen_system_total,
    appointments_tamkeen_virtual,
    appointments_tamkeen_physical,
    appointments_comments,
    interviews_mol_total,
    interviews_mol_virtual,
    interviews_mol_physical,
    interviews_mol_details,
    interviews_tamkeen_total,
    interviews_tamkeen_virtual,
    interviews_tamkeen_physical,
    interviews_tamkeen_details,
    no_of_trainings_on_premises,
    training_type_details,
    number_of_job_matches,
    issues_to_flag,
    start_time,
    completion_time,
    officer_email,
    officer_name,
    record_id,
    --dbt_updated_on,
    source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".offline_sheets_job_seeker_and_walkins_job_centers_details;