SELECT
    extract_date,
    application_no,
    validation_note,
    cpr,
    individual_name,
    application_status,
    application_approved_on,
    joining_date,
    mol_registered,
    job_center,
    basic_salary,
    allowances,
    total_salary,
    job_title,
    company,
    cr_license_no,
    contract_type,
    contract_signed,
    contract_link,
    assessor_name,
    approval_name,
    ad_approval,
    additional_comments,
    --current_timestamp AS dbt_updated_at,
    CAST('OFFLINE_SHEETS' AS VARCHAR) AS source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".offline_sheets_placement_and_approved_jobs_plus_applications;


SELECT
    extract_date,
    application_no,
    validation_note,
    cpr,
    individual_name,
    application_status,
    application_approved_on,
    joining_date,
    mol_registered,
    job_center,
    basic_salary,
    allowances,
    total_salary,
    job_title,
    company,
    cr_license_no,
    contract_type,
    contract_signed,
    contract_link,
    assessor_name,
    approval_name,
    ad_approval,
    additional_comments,
    dbt_updated_at,
    source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".offline_sheets_placement_and_approved_jobs_plus_applications;