SELECT
    extract_date,
    id,
    application_no,
    application_id,
    cpr,
    individual_name,
    joining_date,
    mol_registered,
    job_center,
    basic_salary,
    allowances,
    position,
    company,
    cr_license_no,
    contract_type,
    application_status,
    contract_signed,
    additional_comments,
    mol_registered_jobseeker_for_3plus_years AS mol_registered_3plus_years,
    --current_timestamp AS dbt_updated_on,
    CAST('OFFLINE_SHEETS' AS VARCHAR) AS source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".offline_sheets_job_seeker_and_walkins_applications_tracker_v2;

SELECT
    extract_date,
    id,
    application_no,
    application_id,
    cpr,
    individual_name,
    joining_date,
    mol_registered,
    job_center,
    basic_salary,
    allowances,
    position,
    company,
    cr_license_no,
    contract_type,
    application_status,
    contract_signed,
    additional_comments,
    mol_registered_3plus_years,
    --dbt_updated_on,
    source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".offline_sheets_job_seeker_and_walkins_applications_tracker_v2;