SELECT
    extract_month,
    branch_cr_number,
    branch_cr_number_main_cr,
    branch_cr_number_branch_cr,
    employer_number,
    branch_number,
    employer_insurance_type_description_english AS employer_insurance_type,
    branch_name_english AS branch_name,
    branch_nationality_english_description AS branch_nationality,
    economic_activity_english_description AS economic_activity,
    worker_cpr,
    nationality_b_nb AS is_bahraini,
    worker_date_of_birth,
    worker_insurance_start_date,
    worker_gender_description AS worker_gender,
    job_position_description_english AS job_position,
    worker_qualification_english_description AS worker_qualification,
    job_start_date_employer_and_branch AS job_start_date,
    job_end_date,
    job_terminiation_code,
    job_terminiation_english AS job_termination_reason,
    sio_salary_ranges_tamkeen AS sio_salary_range,
    number_of_months_approximation,
    current_timestamp AS dbt_updated_on,
    CAST('OFFLINE_SHEETS' AS VARCHAR) AS source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".offline_sheets_external_data_sio_employees;

SELECT
    extract_month,
    branch_cr_number,
    branch_cr_number_main_cr,
    branch_cr_number_branch_cr,
    employer_number,
    branch_number,
    employer_insurance_type,
    branch_name,
    branch_nationality,
    economic_activity,
    worker_cpr,
    is_bahraini,
    worker_date_of_birth,
    worker_insurance_start_date,
    worker_gender,
    job_position,
    worker_qualification,
    job_start_date,
    job_end_date,
    job_terminiation_code,
    job_termination_reason,
    sio_salary_range,
    number_of_months_approximation,
    dbt_updated_on,
    source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".offline_sheets_sio_employees;