SELECT
    extract_date,
    project_details_project_owner AS project_owner,
    project_details_project_id AS project_id,
    project_details_project_name AS project_name,
    project_details_project_manager AS project_manager,
    project_details_project_segment AS project_segment,
    project_details_support_area AS support_area,
    project_details_responsible_department AS responsible_department,
    project_details_project_brief AS project_brief,
    project_details_project_objectives AS project_objectives,
    project_details_requested_human_capital AS requested_human_capital,
    project_details_requested_amount AS requested_amount,
    project_details_workflow_status AS workflow_status,
    project_details_gl_account AS gl_account,
    partner_details_cr_license_number AS cr_license_number,
    partner_details_commercial_name AS commercial_name,
    partner_details_partner_location AS partner_location,
    partner_details_partner_region AS partner_region,
    partner_details_partner_country AS partner_country,
    partner_details_company_type AS company_type,
    partner_details_registration_date AS registration_date,
    partner_details_enterprise_gender AS enterprise_gender,
    partner_details_enterprise_type AS enterprise_type,
    partner_details_sector AS sector,
    partner_details_conducting_business_overseas AS conducting_business_overseas,
    employment_and_salary_details_no_of_bahraini_employees AS no_of_bahraini_employees,
    employment_and_salary_details_no_of_non_bahriani_employees AS no_of_non_bahraini_employees,
    employment_and_salary_details_total_no_of_employees AS total_no_of_employees,
    employment_and_salary_details_no_of_bahraini_female_employees AS no_of_bahraini_female_employees,
    employment_and_salary_details_total_bahraini_salaries AS total_bahraini_salaries,
    employment_and_salary_details_total_non_bahraini_salaries AS total_non_bahraini_salaries,
    employment_and_salary_details_total_salaries AS total_salaries,
    contract_details_contract_reference AS contract_reference,
    contract_details_target_intake AS target_intake,
    contract_details_target_segment AS target_segment,
    contract_details_target_sector AS target_sector,
    contract_details_start_date AS contract_start_date,
    contract_details_end_date AS contract_end_date,
    contract_details_total_budget AS total_budget,
    contract_details_utilized_budget AS utilized_budget,
    contract_details_remaining_budget AS remaining_budget,
    enterprise_contact_details_name AS contact_name,
    enterprise_contact_details_designation AS contact_designation,
    enterprise_contact_details_mobile AS contact_mobile,
    enterprise_contact_details_office AS contact_office,
    enterprise_contact_details_email AS contact_email,
    partner_address_flat AS address_flat,
    partner_address_building AS address_building,
    partner_address_road AS address_road,
    partner_address_block AS address_block,
    partner_address_area AS address_area,
    admin_created_on AS created_on,
    admin_created_by AS created_by,
    admin_approved_on AS approved_on,
    admin_approved_by AS approved_by,
    --current_timestamp AS dbt_updated_on,
    CAST('OFFLINE_SHEETS' AS VARCHAR) AS source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".offline_sheets_grtandgre_project_details;

SELECT
    extract_date,
    project_owner,
    project_id,
    project_name,
    project_manager,
    project_segment,
    support_area,
    responsible_department,
    project_brief,
    project_objectives,
    requested_human_capital,
    requested_amount,
    workflow_status,
    gl_account,
    cr_license_number,
    commercial_name,
    partner_location,
    partner_region,
    partner_country,
    company_type,
    registration_date,
    enterprise_gender,
    enterprise_type,
    sector,
    conducting_business_overseas,
    no_of_bahraini_employees,
    no_of_non_bahraini_employees,
    total_no_of_employees,
    no_of_bahraini_female_employees,
    total_bahraini_salaries,
    total_non_bahraini_salaries,
    total_salaries,
    contract_reference,
    target_intake,
    target_segment,
    target_sector,
    contract_start_date,
    contract_end_date,
    total_budget,
    utilized_budget,
    remaining_budget,
    contact_name,
    contact_designation,
    contact_mobile,
    contact_office,
    contact_email,
    address_flat,
    address_building,
    address_road,
    address_block,
    address_area,
    created_on,
    created_by,
    approved_on,
    approved_by,
    --dbt_updated_on,
    source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".offline_sheets_grtandgre_project_details;