SELECT
    extract_month,
    cr_no,
    branch_no,
    cr_status,
    status_en,
    status_ar,
    commercial_name_en,
    commercial_name_ar,
    cr_type,
    company_type_ar,
    company_type_en,
    previous_company_type_ar,
    previous_company_type_en,
    type_change_date,
    reg_date,
    expiry_date,
    flat_shop_no AS address_flat_shop,
    building AS address_building,
    road_street AS address_road,
    block AS address_block,
    town AS address_town,
    municipality_en,
    municipality_ar,
    phone,
    mobile,
    email,
    isic4,
    activity_en,
    activity_ar,
    sector_en,
    sector_ar,
    cr_class,
    ownership,
    gender,
    issued_capital_bd,
    authorized_capital_bd,
    sijili_date,
    deletion_date,
    conventional_date,
    current_timestamp AS dbt_updated_at,
    CAST('OFFLINE_SHEETS' AS VARCHAR) AS source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-bronze".offline_sheets_moic_active_and_deleted_crs; 

SELECT
    extract_month,
    cr_no,
    branch_no,
    cr_status,
    status_en,
    status_ar,
    commercial_name_en,
    commercial_name_ar,
    cr_type,
    company_type_ar,
    company_type_en,
    previous_company_type_ar,
    previous_company_type_en,
    type_change_date,
    reg_date,
    expiry_date,
    address_flat_shop,
    address_building,
    address_road,
    address_block,
    address_town,
    municipality_en,
    municipality_ar,
    phone,
    mobile,
    email,
    isic4,
    activity_en,
    activity_ar,
    sector_en,
    sector_ar,
    cr_class,
    ownership,
    gender,
    issued_capital_bd,
    authorized_capital_bd,
    sijili_date,
    deletion_date,
    conventional_date,
    dbt_updated_at,
    source_system_name
FROM dev_iceberg."tmkn-aws-dwh-dev-iceberg-silver".offline_sheets_moic_active_and_deleted_crs;